src/objects/Active_Trigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Traffic cop for Triggers</description>
    <fields>
        <fullName>Promo_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Promo Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Active Trigger</label>
</CustomObject>

src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Location</label>
        <referenceTo>Deposition_Location__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Notes__c</fullName>
        <label>Billing Notes</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deposition_Location__c</fullName>
        <label>Deposition Location</label>
        <scale>14</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Generate_Change_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this field is checked, the trigger runs and computes the values that are changed, enable selectively for testing and debugging first.</description>
        <inlineHelpText>When this field is checked, the trigger runs and computes the values that are changed, enable selectively</inlineHelpText>
        <label>Generate Change Log</label>
        <type>Checkbox</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deposition_Location__c.object
<CustomObject>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Deposition Locations</relationshipLabel>
        <relationshipName>Deposition_Location</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deposition Location</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposition Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Promo_Email__c.object
<CustomObject>
    <description>Object to manage customized email blasts to specific clients on specific cases.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Promo Emails</relationshipLabel>
        <relationshipName>Promo_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promo Email</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Promo Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_Triggers.cls
@isTest
private class Test_Triggers {
  
  @isTest
  private static void Test_PromoEmailTrigger() {
    TestUtils utils = new TestUtils();
    Account account = utils.insertAccount();
    Contact contact = utils.insertContact(account.Id);
    
    Active_Trigger__c activeTrigger = Active_Trigger__c.getInstance();
    if(activeTrigger == null) {
      activeTrigger = new Active_Trigger__c();
    }
    activeTrigger.Promo_Email__c = true;
    upsert activeTrigger;
    
    Promo_Email__c promoEmail = new Promo_Email__c(Contact__c = contact.Id);
    insert promoEmail;
  }
  
  @isTest
  private static void Test_AttendeeTrigger() {
    TestUtils utils = new TestUtils();
    Account account = utils.insertAccount();
    Contact contact = utils.insertContact(account.Id);
    
    Deposition__c deposition = utils.insertDeposition(account.ID);
    deposition.Generate_Change_Log__c = true;
    deposition.Billing_Notes__c = 'Changd';
    
    update deposition;
    
    Deposition_Location__c depositionLocation = utils.createDepositionLocation(deposition);
    Attendee__c attendee = utils.insertAttendee(contact.Id, deposition.ID);
    
  }
  
  @isTest
  private static void Test_TaskTrigger() {
    Account account = new Account(Name = 'ssssss');
    insert account;
  
    Contact contact = new Contact(LastName = 'SSSS');
    insert contact;
    
    Task task = new task(Subject = 'sss',ActivityDate = System.today());
    task.WhoId = contact.Id;
    insert task;
  }
}