src/objects/Amazon_S3_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Amazon S3 Configuration</label>
</CustomObject>

src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposition Notice</fullName>
                </value>
                <value>
                    <fullName>Exhibit</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Signature Page</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Turn-in Sheet</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Upload_Email_Notification__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email_For_All_File_Type__c</fullName>
        <label>Email For All File Type</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_For_Invoice__c</fullName>
        <label>Email For Invoice</label>
        <type>Email</type>
    </fields>
    <label>Upload Email Notification</label>
</CustomObject>

src/classes/TestUploadFilesController.cls
@isTest
private class TestUploadFilesController {
  
  @isTest
  private static void Test_UploadFiles(){
    Amazon_S3_Configuration__c awsKey = new Amazon_S3_Configuration__c(Key__c='test',Secret__c='test');  
    insert awsKey;
    AWS_S3_ExampleController c = new AWS_S3_ExampleController();
    
    c.constructor();
    c.createBucket();
    Upload_Email_Notification__c emailNotification = new Upload_Email_Notification__c(Email_For_All_File_Type__c='test@gmail.com',Email_For_Invoice__c='test@gmail.com');
    insert emailNotification ;
    TestUtils tUtils = new TestUtils();
    Deposition__c deposition = tUtils.createDeposition();
    
    UploadFilesController fileController = new UploadFilesController();
    fileController.initForUploadPage();
    
    fileController.uploadFiles.Deposition_Number__c = 'aaaaa';
    fileController.SaveFiles();
    
    String name = [SELECT Name from Deposition__c WHERE ID = :deposition.Id].Name;
    fileController.uploadFiles.Deposition_Number__c = name;
    
    fileController.SaveFiles();
    
    Account account = tUtils.insertAccount();
    Contact contact = tUtils.insertContact(account.ID);
    tUtils.insertAttendee(contact.Id, deposition.ID);
    
    
     
    
    fileController.uploadFiles.Email__c = contact.Email;
    fileController.SaveFiles();
     ApexPages.currentPage().getParameters().put('id',fileController.uploadFiles.id);
    fileController.dragDropUploadInit();
    UploadFilesController.fetchFileNameWithVersionRemote('Test.jpg','testBucket');
    UploadFilesController.createAwsS3Object('Test.jpg','testfolder', 'test123', fileController.uploadFiles.id,'', 'test',
                                          100,1);
    UploadFilesController.createAwsS3Object('Test.jpg','testfolder', 'test124', fileController.uploadFiles.id,'', 'test',
                                          100,1);
    UploadFilesController.createAwsS3Object('Test.jpg','testfolder',  'test125', fileController.uploadFiles.id,'', 'test',
                                          100,1);                                                                    
    UploadFilesController.fetchFileNameWithVersionRemote('Test.jpg','testBucket');
    fileController.fetchAWSS3Objects();
    Integer i= 1;
    for(AWS_S3_Object__c obj : fileController.lstAWSS3Objects){
        if(i==1 ) obj.File_Type__c = 'Invoices';
        if(i==2 ) obj.File_Type__c = 'Transcript';
        if(i==3 ) obj.File_Type__c = 'Exhibit';
        i++;
    }
    List<Attendee__c> lstAttendee =[SELECT Id,Email__c,Role__c FROM Attendee__c WHERE Deposition__c = :deposition.ID];
    if(lstAttendee.size()>0){
        lstAttendee[0].Role__c = 'Videographer/Technician';
        update lstAttendee;
    }
    fileController.saveAndSendEmail();
    if(lstAttendee.size()>0){
        lstAttendee[0].Role__c = 'Court Reporter';
        update lstAttendee;
    } 
    
    fileController.saveAndSendEmail();
    fileController.SaveFiles();
    
    ApexPages.currentPage().getParameters().put('id',name );
    ApexPages.currentPage().getParameters().put('email',contact.Email);
    fileController = new UploadFilesController();
    fileController.initForUploadPage();
  }
  
  
  @isTest
  private static void Test_UploadFile(){
    Amazon_S3_Configuration__c awsKey = new Amazon_S3_Configuration__c(Key__c='test',Secret__c='test');  
    insert awsKey;
    AWS_S3_ExampleController c = new AWS_S3_ExampleController();
    
    c.constructor();
    c.createBucket();
    Upload_Email_Notification__c emailNotification = new Upload_Email_Notification__c(Email_For_All_File_Type__c='test@gmail.com',Email_For_Invoice__c='test@gmail.com');
    insert emailNotification ;
    TestUtils tUtils = new TestUtils();
    
    
    UploadFilesController fileController = new UploadFilesController();
    fileController.init();
    fileController.initForUploadPageWithoutTemplate();
    
    
    fileController.SaveFiles();
    
    
    fileController.SaveFiles();
    
    Account account = tUtils.insertAccount();
    Contact contact = tUtils.insertContact(account.ID);
    
    fileController.uploadFiles.Email__c = 'test12@gmail.com';
    fileController.SaveFiles();
    ApexPages.currentPage().getParameters().put('id',fileController.uploadFiles.id);
    fileController.dragDropUploadInit();
    UploadFilesController.fetchFileNameWithVersionRemote('Test.jpg','testBucket');
    UploadFilesController.createAwsS3Object('Test.jpg','testfolder', 'test123', fileController.uploadFiles.id,'', 'test',
                                          100,1);
    UploadFilesController.createAwsS3Object('Test.jpg','testfolder', 'test124', fileController.uploadFiles.id,'', 'test',
                                          100,1);
    UploadFilesController.createAwsS3ObjectAmazon('Test.jpg','testfolder',  'test125', fileController.uploadFiles.id,'', 'test',
                                          100,1);                                      
    UploadFilesController.fetchFileNameWithVersionRemote('Test.jpg','testBucket');
    fileController.fetchAWSS3Objects();
    Integer i= 1;
    for(AWS_S3_Object__c obj : fileController.lstAWSS3Objects){
        if(i==1 ) obj.File_Type__c = 'Invoices';
        if(i==2 ) obj.File_Type__c = 'Transcript';
        if(i==3 ) obj.File_Type__c = 'Exhibit';
        i++;
    }
    fileController.saveAndSendEmail();
    fileController.SaveFiles();
  }
}