src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Court_Reporter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Industry</field>
                <operation>equals</operation>
                <value>Court Reporting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees (Court Reporter)</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Videographer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Videographer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Industry</field>
                <operation>equals</operation>
                <value>Court Reporting, Videography</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees (Videographer)</relationshipLabel>
        <relationshipName>Attendees1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Duration__c</fullName>
        <description>How long does the client expect this event to last?</description>
        <label>Estimated Duration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GuestName__c</fullName>
        <label>Scheduler Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Firm__c</fullName>
        <label>Hiring Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DepositionAssignmentCntrl.cls
/**
                                                Name             : DepositionAssignmentCntrl 
                                                Date             : 11 Jan 2015
                                                Descripotion     : This class is used by "DepositionAssignment" VF page.
                                                                 That page will enable us to assign reporters and videographers in bulk.
 
                                                                The user would go to a page which shows all of tomorrow’s jobs with the following columns:
                                                                -          Court Reporter (If there is an attendee whose role = court reporter, their name should
                                                                           be listed as a read only text field. If there is no court reporter assigned, there should be a lookup box 
                                                                           where the user can enter a court reporter. Ideally, it would have a filter field which would only show 
                                                                           contacts whose account = court reporting.)
                                                                
                                                                -          Videographer (If there is an attendee whose role = Videographer/Technician, their name should be listed as a 
                                                                           read only text field. If there is no Videographer/Technician assigned, there should be a lookup box where the 
                                                                           user can enter a court reporter. Ideally, it would have a filter field which would only show contacts whose 
                                                                           account industry = court reporting or Videography.)
                                                                
                                                                -          Case caption (Read only)
                                                                
                                                                -          Depo Start Time (Read only)
                                                                
                                                                -          Estimated Duration
                                                                
                                                                -          Hiring Firm (Read only)
                                                                
                                                                -          Hiring Attorney (Read only)
                                                                
                                                                -          Deposition Services (Read only)
                                                                -          Scheduler Name
*/
public class DepositionAssignmentCntrl {

    public List<DepositionModel>lstTomorrowDepositions{get;set;}
    
    public Deposition__c dep{get;set;}
    public List<SelectOption>lstFirms{get;set;}
    public string selectedFirm{get;set;}
    public DepositionAssignmentCntrl(){
        dep = new Deposition__c ();
        dep.Deposition_Date__c = System.Today()+1;
        fetchFirms();
        loadDepositions();
    }
    
    private void fetchFirms(){
        lstFirms = new List<SelectOption>();
        User usr = [select Default_CR_Firm__c FROM User WHERE Id =:UserInfo.getUserId() ];
        if(usr.Default_CR_Firm__c == NULL)
            usr.Default_CR_Firm__c = 'NextGen Reporting';
        for(Firm__c firm : [select id,Name From Firm__c LIMIT 100]){
            if( usr.Default_CR_Firm__c.equalsIgnoreCase(firm.Name))
                selectedFirm = firm.id;
            lstFirms.add(new SelectOption(firm.id,firm.Name));
        }
    }
    
    public void loadDepositions(){
        lstTomorrowDepositions = new List<DepositionModel>();
        
        for(Deposition__c dep : [select id,Name,Case_Name__c,Deposition_Time__c,Estimated_Duration__c,Hiring_Firm__c,
                                Hiring_Attorney__c,Deposition_Services__c,GuestName__c,
                                (select id,Contact__c,Role__c,Court_Reporter__c,Videographer__c
                                  From Deposition_Roles__r WHERE Role__c IN('Court Reporter','Videographer/Technician') )
                                From Deposition__c  WHERE  Deposition_Date__c != NULL 
                                AND Deposition_Status__c != 'Cancelled' AND Deposition_Date__c=:dep.Deposition_Date__c
                                 AND Primary_Court_Reporting_Firm__c=:selectedFirm ]){
                DepositionModel depModel = new DepositionModel();
                depModel.deposition = dep;
                depModel.reporter= new Attendee__c();
                depModel.videographer= new Attendee__c();
                for(Attendee__c attendee : dep.Deposition_Roles__r ){
                    if(attendee.Role__c =='Court Reporter')
                        depModel.reporter=  attendee;
                    else if(attendee.Role__c =='Videographer/Technician')
                        depModel.videographer= attendee;
                }
                
                lstTomorrowDepositions.add(depModel);
        }
    }
    
    public void saveDepositions(){
        Savepoint sp = Database.setSavepoint();
        try{
            List<Attendee__c>lstAttendeeNeedInsert = new List<Attendee__c>();
            for(DepositionModel depModel : lstTomorrowDepositions){
                // Reporter
                if(depModel.reporter.Court_Reporter__c != NULL){
                    depModel.reporter.Contact__c = depModel.reporter.Court_Reporter__c;
                    depModel.reporter.Court_Reporter__c = NULL;
                    depModel.reporter.Deposition__c = depModel.deposition.id;
                    depModel.reporter.Role__c= 'Court Reporter';
                    lstAttendeeNeedInsert.add(depModel.reporter);
                }
                
                //Videographer/Technician
                if(depModel.videographer.Videographer__c != NULL){
                    depModel.videographer.Contact__c = depModel.videographer.Videographer__c;
                    depModel.videographer.Videographer__c= NULL;
                    depModel.videographer.Deposition__c = depModel.deposition.id;
                    depModel.videographer.Role__c= 'Videographer/Technician';
                    lstAttendeeNeedInsert.add(depModel.videographer);
                }
            }
            if(lstAttendeeNeedInsert.size()>0){
                insert lstAttendeeNeedInsert;
                AttendeeHelper.sendEmailAlertToReporterAndVideographer(lstAttendeeNeedInsert);
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Changes successfully saved.'));
            
        }Catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,e.getMessage()));
            Database.rollback(sp);
        }
    }
    public class DepositionModel{
        public Deposition__c deposition{get;set;}
        public Attendee__c reporter{get;set;}
        public Attendee__c videographer{get;set;}
    }
}