src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Location</label>
        <referenceTo>Deposition_Location__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_locked_to_Create_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is locked to Create Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locked_By__c</fullName>
        <label>Locked By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standing_Orders_del__c</fullName>
        <formula>BLANKVALUE( Contact__r.Standing_Orders__c , &quot;&quot;)
&amp;
 BLANKVALUE( Contact__r.Account.Standing_Orders__c , &quot;&quot;)</formula>
        <label>Standing Orders</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <formula>IF(ISBlank(TEXT(Contact__r.VIP_Level__c)),Text(Contact__r.Account.VIP_Level__c),Text(Contact__r.VIP_Level__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIP Level</label>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <fields>
        <fullName>Billing_Notes__c</fullName>
        <label>Billing Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <label>VIP Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP 1</fullName>
                </value>
                <value>
                    <fullName>VIP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Notes__c</fullName>
        <label>Billing Notes</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <label>Claims Professional</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Client_Source__c</fullName>
        <label>Corporate Client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AIG</fullName>
                </value>
                <value>
                    <fullName>Allstate</fullName>
                </value>
                <value>
                    <fullName>Amica</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T (Troy)</fullName>
                </value>
                <value>
                    <fullName>BASF</fullName>
                </value>
                <value>
                    <fullName>Cardinal Health</fullName>
                </value>
                <value>
                    <fullName>CSAA Insurance</fullName>
                </value>
                <value>
                    <fullName>DuPont</fullName>
                </value>
                <value>
                    <fullName>Electric Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Erie Insurance</fullName>
                </value>
                <value>
                    <fullName>Farmers Insurance</fullName>
                </value>
                <value>
                    <fullName>Fireman’s Fund</fullName>
                </value>
                <value>
                    <fullName>Gateway Risk Services</fullName>
                </value>
                <value>
                    <fullName>GEICO</fullName>
                </value>
                <value>
                    <fullName>Global Indemnity</fullName>
                </value>
                <value>
                    <fullName>Horace Mann</fullName>
                </value>
                <value>
                    <fullName>HPE</fullName>
                </value>
                <value>
                    <fullName>Liberty Mutual</fullName>
                </value>
                <value>
                    <fullName>Markel</fullName>
                </value>
                <value>
                    <fullName>Mass Mutual</fullName>
                </value>
                <value>
                    <fullName>Medical Protective</fullName>
                </value>
                <value>
                    <fullName>Mercury Insurance</fullName>
                </value>
                <value>
                    <fullName>National Indemnity Company of the South</fullName>
                </value>
                <value>
                    <fullName>National Liability &amp; Fire Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>No Corporate Client</fullName>
                </value>
                <value>
                    <fullName>North American Risk Services</fullName>
                </value>
                <value>
                    <fullName>Old Republic Contractors</fullName>
                </value>
                <value>
                    <fullName>Pioneer</fullName>
                </value>
                <value>
                    <fullName>Preferred Mutual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Location__c</fullName>
        <label>Deposition Location</label>
        <scale>14</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type_Lowercase__c</fullName>
        <formula>CASE( Event_Type__c , &quot;Deposition&quot;, &quot;deposition&quot;, &quot;Arbitration&quot;, &quot;arbitration&quot;, &quot;Demo&quot;, &quot;demo&quot;, &quot;Other&quot; , &quot;event&quot; , &quot;Examination Under Oath&quot; , &quot;examination under oath&quot;, &quot;Statement Under Oath&quot; , &quot;statement under oath&quot;, &quot;Mediation&quot; , &quot;mediation&quot;, &quot;Trial&quot; , &quot;trial&quot;, &quot;Hearing&quot; , &quot;hearing&quot;, &quot;Video Playback&quot; , &quot;video playback&quot;, &quot;Auction&quot; , &quot;auction&quot;, &quot;event&quot;)</formula>
        <label>Event Type Lowercase</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Claim_Info__c</fullName>
        <label>Insurance Claim Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Matter_Number__c</fullName>
        <label>Matter Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_CR_Firm__c</fullName>
        <description>The court reporting firm for which we&apos;re handling this deposition.</description>
        <label>Networking/Covering For</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deposition_Location__c.object
<CustomObject>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Deposition Locations</relationshipLabel>
        <relationshipName>Deposition_Location</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deposition Location</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposition Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateInvoice_Ctrl.cls
/**
Name             : CreateInvoice_Ctrl
Date             : 19 Nov 2015
Descripition     : This class is used by CreateInvoice VF page for creating a invoice record
for a attendee and allow user to select rate sheet for invoice.

*/ 
public class CreateInvoice_Ctrl{
    
    public String selectedRateSheet {
        get;
        set;
    }
    
    string attendeeID;
    public Boolean isAttendeeLocked{get;set;}
    public Attendee__c attendee {
        get;
        set;
    }
    public Contact tempContact {
        get;
        set;
    }
    public boolean showLookupRateSheet {
        get;
        set;
    }
    public Deposition__c dep{get;set;}
    public State_Rules__c stateRules{get;set;}
    public String type {get;set;}
    public boolean showTypelookup {get;set;}
    
    public CreateInvoice_Ctrl() {
        isAttendeeLocked = false;
        attendeeID = apexpages.currentpage().getparameters().get('id');
        stateRules = new State_Rules__c();
        attendee = new Attendee__c ();
        dep = new Deposition__c();
        showTypelookup=false;
        type='';
        
        if (attendeeID != null && attendeeID != '') {
            attendee = [select id, name, Deposition_Location__c,Is_locked_to_Create_Invoice__c,Locked_By__c, Deposition_Location__r.name, Deposition__r.Deposition_Location__c, 
                        Deposition__r.State__c, Contact__r.name, Contact__r.Rate_Sheet__c, Contact__r.Rate_Sheet__r.name, 
                        Contact__r.AccountId, Contact__r.Account.Rate_Sheet__c, Contact__r.Account.Rate_Sheet__r.name,Contact__r.Account.Name,
                        Account_Name__c, Deposition__r.Case_Name__c, Deposition__r.Deposition_Group__r.name,
                        Deposition__r.Deposition_Group__r.Rate_Sheet__c, Deposition__r.Deposition_Group__r.Rate_Sheet__r.name,
                        Deposition__r.Corporate_Client_Source__c, Deposition__r.Billing_Notes__c, Standing_Orders_del__c,
                        Contact__r.Account.Industry,Deposition__r.Event_Location__c,Deposition__c,Deposition__r.Event_Type_Lowercase__c,Deposition__r.Primary_CR_Firm__c
                        ,Deposition__r.Insurance_Claim_Info__c,Deposition__r.Claims_Professional__c,Deposition__r.Matter_Number__c
                        ,Deposition__r.VIP_Level__c,Deposition__r.Attorney_Count__c ,Deposition__r.Deposition_Group__c,
                        Contact__r.Account.Financial_Notes__c, Contact__r.Financial_Notes__c
                        FROM Attendee__c where id = : attendeeID
                       ];
            dep.id = attendee.Deposition__c;
            dep.State__c = attendee.Deposition__r.State__c;
            if(dep.State__c == NULL ||dep.State__c == '')
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'To create this invoice, please select the state where the '+ attendee.Deposition__r.Event_Type_Lowercase__c+' occurred.'));
            if(attendee.Is_locked_to_Create_Invoice__c & attendee.Locked_By__c != UserInfo.getName()){
                isAttendeeLocked = true;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This Attendee is locked, '+ attendee.Locked_By__c +' is trying to create invoice for this Attendee.'));
            }
            
                

        }
        tempContact = new Contact();
        showLookupRateSheet = false;
        loadStateRules();
        
        if(attendee!=null && attendee.Contact__c!=null && attendee.Contact__r.Account.Industry!=null && 
           attendee.Contact__r.Account.Industry=='Court Reporting' && attendee.Deposition__c!=null && 
           string.isnotBlank(attendee.Deposition__r.Primary_CR_Firm__c) && 
           !(attendee.Contact__r.Account.Name.containsIgnoreCase('Lexitas')|| attendee.Contact__r.Account.Name.containsIgnoreCase('NextGen') 
             ||attendee.Contact__r.Account.Name.containsIgnoreCase('Independent Court Reporters') ||attendee.Contact__r.Account.Name.containsIgnoreCase('Jensen') 
             ||attendee.Contact__r.Account.Name.containsIgnoreCase('Deitz')) ){
                 showTypelookup=true;
             }
    }
    public void lockInvoice(){
        if(!attendee.Is_locked_to_Create_Invoice__c){
                Attendee__c lockAttendee = new Attendee__c(Id = attendeeID, Is_locked_to_Create_Invoice__c = true, Locked_By__c = UserInfo.getName() );
                update lockAttendee;
            }
    }
    public void saveDeposition(){
        try{
            update dep;
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
    }
    private void loadStateRules(){
        if (attendee.Deposition__r.State__c != null) {
            List<State_Rules__c>lstStateRules = [select id,Rule__c From State_Rules__c 
                                                 WHERE Name =:attendee.Deposition__r.State__c];
            if(lstStateRules.size()>0){
                stateRules = lstStateRules[0];
            }
        }
    }
    public List < SelectOption > getInvoiceTypes() {
        List < SelectOption > options = new List < SelectOption > ();
        options.add(new SelectOption('Client', 'Client:We are providing court reporting services on a networked job.'));
        options.add(new SelectOption('Reporter', 'Reporter: We hired them as the court reporter.'));
        options.add(new SelectOption('Video/Tech', 'Video/Tech'));
        
        return options;
    }
    
    public List < SelectOption > getRateSheets() {
        
        List < SelectOption > options = new List < SelectOption > ();
        //options.add(new SelectOption('', '--None--'));
        
        if (attendee.Deposition__r.Deposition_Group__c != null && attendee.Deposition__r.Deposition_Group__r.Rate_Sheet__c != null) {
            options.add(new SelectOption(attendee.Deposition__r.Deposition_Group__r.Rate_Sheet__c, attendee.Deposition__r.Deposition_Group__r.Rate_Sheet__r.name));
        }
        if (attendee.Contact__c != null && attendee.Contact__r.Rate_Sheet__c != null) {
            options.add(new SelectOption(attendee.Contact__r.Rate_Sheet__c, attendee.Contact__r.Rate_Sheet__r.name));
        }
        if (attendee.Contact__c != null && attendee.Contact__r.Account != null && attendee.Contact__r.Account.Rate_Sheet__c != null) {
            options.add(new SelectOption(attendee.Contact__r.Account.Rate_Sheet__c, attendee.Contact__r.Account.Rate_Sheet__r.name));
        }
        if (attendee.Deposition__r.Corporate_Client_Source__c != null) {
            List < Rate_Sheet__c > rateSheets = Database.query('SELECT Id,name FROM Rate_Sheet__c WHERE Name LIKE \'' + '%' + attendee.Deposition__r.Corporate_Client_Source__c + '%\' or Name = \'Copy Side\'');
            for (Rate_Sheet__c curRateSheet: rateSheets) {
                options.add(new SelectOption(curRateSheet.id, curRateSheet.name));
            }
        }
        String standardRatesheetName = '';
        if (attendee.Contact__r.Account.Industry == 'Court Reporting') {
            type = 'Reporter';
            standardRatesheetName  = 'Rack Rate Sheet - Reporter';
        } else if (attendee.Contact__r.Account.Industry == 'Law Firm' || 
                   attendee.Contact__r.Account.Industry == 'Corporation'
                   || attendee.Contact__r.Account.Industry == 'Insurance'
                   || attendee.Contact__R.Account.Industry =='Government/Courts') {
                       type = 'Client';
                       standardRatesheetName  = 'Rack Rate Sheet - Client';
                   }if (attendee.Contact__r.Account.Industry == 'Videography') {
                       type = 'Video/Tech';
                       standardRatesheetName  = 'Rack Rate Sheet - Videographer';
                   }     
        if (attendee.Deposition__r.State__c != null) {
            if (type != null) {
                string queryString = 'SELECT Id, name FROM Rate_Sheet__c WHERE Type__c=\'' + type + '\' and  Name LIKE \'' + '%' + attendee.Deposition__r.State__c + '%\'';
                List < Rate_Sheet__c > rateSheets = Database.query(queryString);
                for (Rate_Sheet__c curRateSheet: rateSheets) {
                    options.add(new SelectOption(curRateSheet.id, curRateSheet.name));
                } 
            }
        }
        if(options.size()==1){
            List < Rate_Sheet__c > rateSheets = Database.query('SELECT Id,name FROM Rate_Sheet__c WHERE Type__c=\'' + type + '\' and  Name LIKE \'%Standard%\'');
            for (Rate_Sheet__c curRateSheet: rateSheets) {
                options.add(new SelectOption(curRateSheet.id, curRateSheet.name));
            }
        }
        if(options.size()==0){
            if( standardRatesheetName != ''){
                for (Rate_Sheet__c curRateSheet: [select id,Name FROM Rate_Sheet__c WHERE Name=:standardRatesheetName ]) {
                    options.add(new SelectOption(curRateSheet.id, curRateSheet.name));
                }
            }
        }
        options.add(new SelectOption('Other', 'Other'));
        if(options.size()==1){
            showLookupRateSheet = true;
            
            
            
        }
        if(type =='')
            showTypelookup = true;
        system.debug('$$$'+showTypelookup );
        return options;
    }
    public PageReference deSelectPicklistRateSheet() {
        if (tempContact.Rate_Sheet__c != null)
            selectedRateSheet = '';
        return null;
    }
    
    public PageReference deSelectLookupRateSheet() {
        if (selectedRateSheet != null)
            tempContact.Rate_Sheet__c = null;
        
        if (selectedRateSheet == 'Other') {
            showLookupRateSheet = true;
        } else {
            showLookupRateSheet = false;
        }
        
        return null;
    }
    
    public PageReference PrepareInvoice() {
        string selectedRateSheetID = (selectedRateSheet != 'Other' ? selectedRateSheet : tempContact.Rate_Sheet__c);
        
        if (selectedRateSheetID != null) {
            PageReference nextPageRef = new PageReference('/apex/PrepareInvoice?rateSheetId=' + selectedRateSheetID + '&attendeeId=' + attendee.id+'&type='+type);
            nextPageRef.setRedirect(true);
            return nextPageRef;
        } else {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a Rate sheet to proceed.');
            ApexPages.addMessage(myMsg);
            return null;
        }
        
    }
    
    public PageReference Cancel() {
        PageReference nextPageRef = new PageReference('/' + attendee.Deposition__c);
        nextPageRef.setRedirect(true);
        return nextPageRef;
    }
}