src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Location Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Confirm_Interpreter__c</fullName>
        <label>Confirm - Interpreter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type_Lowercase__c</fullName>
        <formula>CASE( Event_Type__c , &quot;Deposition&quot;, &quot;deposition&quot;, &quot;Arbitration&quot;, &quot;arbitration&quot;, &quot;Demo&quot;, &quot;demo&quot;, &quot;Other&quot; , &quot;event&quot; , &quot;Examination Under Oath&quot; , &quot;examination under oath&quot;, &quot;Statement Under Oath&quot; , &quot;statement under oath&quot;, &quot;Mediation&quot; , &quot;mediation&quot;, &quot;Trial&quot; , &quot;trial&quot;, &quot;Hearing&quot; , &quot;hearing&quot;, &quot;Video Playback&quot; , &quot;video playback&quot;, &quot;Auction&quot; , &quot;auction&quot;, &quot;event&quot;)</formula>
        <label>Event Type Lowercase</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Deposition</fullName>
                    <default>true</default>
                    <label>Deposition</label>
                </value>
                <value>
                    <fullName>Examination Under Oath</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Statement Under Oath</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Video Playback</fullName>
                </value>
                <value>
                    <fullName>Client Meeting</fullName>
                </value>
                <value>
                    <fullName>Captioned Meeting</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Intra-co</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite Level (Business Days)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Same day turnaround</fullName>
                </value>
                <value>
                    <fullName>Next day turnaround</fullName>
                </value>
                <value>
                    <fullName>2 day turnaround</fullName>
                </value>
                <value>
                    <fullName>3 day turnaround</fullName>
                </value>
                <value>
                    <fullName>4 day turnaround</fullName>
                </value>
                <value>
                    <fullName>5 day turnaround</fullName>
                </value>
                <value>
                    <fullName>6 day turnaround</fullName>
                </value>
                <value>
                    <fullName>7 day turnaround</fullName>
                </value>
                <value>
                    <fullName>8 day turnaround</fullName>
                </value>
                <value>
                    <fullName>9 day turnaround</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Firm__c</fullName>
        <label>Hiring Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Contact__c</fullName>
        <label>Location Contact</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transcript_Due_From_Reporter_Computed__c</fullName>
        <inlineHelpText>Business days</inlineHelpText>
        <label>Transcript Due From Reporter (Computed)</label>
        <type>Date</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OnSiteConfirmationController.cls
/**
    Name        :        OnSiteConfirmationController
    Date        :        5 Feb 2019
    Description :        Schedule class to send email and sms reminder one day before deposition
    Developer
*/
public class OnSiteConfirmationController{
    private String depositionId;
    private String contactId;
    private Attendee__c attendee;
    
    //Intsance Variables
    public Deposition__c deposition{get;set;}
    public Firm__c firm{get;set;}
    public Boolean isError{get;set;}
    
    public OnSiteConfirmationController(){
        depositionId = ApexPages.currentPage().getParameters().get('depositionId');
        contactId = ApexPages.currentPage().getParameters().get('contactId');
        firm = DepositionHelper.fetchFirm( 'NextGen Reporting' );
        isError = false;
        if( String.isNotBlank( contactId ) && String.isNotBlank( depositionId ) ){
            List<Deposition__c> depos = [ SELECT Id, Confirm_Reporter__c, Confirm_Video_Tech__c, Confirm_Interpreter__c, Deposition_Date__c,
                           Deposition_Time__c,Event_Location__c, Case_Name__c, Deponent_Name__c, Hiring_Attorney__c, Hiring_Firm__c,
                           Deposition_Services__c, Event_Type__c, Expedite__c, Transcript_Due_From_Reporter_Computed__c,
                           Event_type_lowercase__c, Time_Zone__c, Location_Contact__c,
                           Primary_Court_Reporting_Firm__c,
                           ( SELECT Id, Role__c  FROM Deposition_Roles__r WHERE Contact__c  =: contactId ) 
                           FROM Deposition__c WHERE Id =: depositionId LIMIT 1];
            if(!depos.isEmpty()){
                deposition = depos[0];
            }else{
                isError = true;
                return;
            }
            
            firm = [SELECT Id, Name, Community_Header__c,Community_Footer__c, Web_Page_Footer_HTML__c , Web_Page_Header_HTML__c,
                    Scheduling_Email_Address__c, Phone__c
                        FROM Firm__c 
                        WHERE Id=: deposition.Primary_Court_Reporting_Firm__c  LIMIT 1];
                            
            List<Attendee__c> attendees = [SELECT Id, Arrival_Time__c 
                                            FROM Attendee__c WHERE Deposition__c =: depositionId AND Contact__c =: contactId LIMIT 1];
            if(!attendees.isEmpty()){
                attendee = attendees[0];
            }
        }
    }
    
    //Update On site check in date time
    public void manitainAttendee(){
        if( deposition != NULL && attendee != NULL ){
            try{
                attendee.On_site_Check_In__c = System.now();
                UPDATE attendee;
                isError = FALSE;
            }catch(Exception excep ){
                isError = true;
            }
        }
    }
}