src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Id__c</fullName>
        <externalId>true</externalId>
        <label>File Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposition Notice</fullName>
                </value>
                <value>
                    <fullName>Exhibit</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Signature Page</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Turn-in Sheet</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_Files__c</fullName>
        <label>Upload Batches</label>
        <referenceTo>Upload_Files__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Google_Drive_Folder_Id__c</fullName>
        <label>Google Drive Folder Id</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/File_Access__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipName>S3_File_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ Attendee__r.Contact__c ,   Attendee__r.Contact__r.FirstName  +&apos; &apos;+ Attendee__r.Contact__r.LastName,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <label>File</label>
        <referenceTo>AWS_S3_Object__c</referenceTo>
        <relationshipLabel>File Access</relationshipLabel>
        <relationshipName>S3_File_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File Access</label>
    <nameField>
        <displayFormat>SFA-{00000000}</displayFormat>
        <label>S3 File Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Upload_Files__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Upload_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Upload_Files1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Upload Batches</label>
    <nameField>
        <displayFormat>UB-{0000000}</displayFormat>
        <label>Upload Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestGrantingFileAccessToUsersExtn.cls
/**************************************************
                Name        : TestGrantingFileAccessToUsersExtn
                Author      : Rajendra Rathore
                Purpose     : Test class for GrantingFileAccessToUsersExtn Apex class
                Created Date: 13 JUNE  2016
                
                Modification History:
*****************************************************/
@isTest
public  class TestGrantingFileAccessToUsersExtn{
  @isTest
  private static void Test_GrantingFileAccessToUsersExtn(){
      Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
      Deposition__c dep = TestUtility.createDeposition(null);
      dep.Case_Name__c='Test';
      insert dep;
      
      dep.GOOGLE_DRIVE_FOLDER_ID__C  = 'testFolderId';
      update dep;
      ApexPages.currentPage().getParameters().put('folderId','testfolderId');
      User usr = TestUtility.createCommunityUser();
      
      Contact con = new Contact(LastName='Test',Email='test@gmail.com');
      insert con;
      Attendee__c attendee = TestUtility.createAttendee(con.id,dep.id);
      insert attendee;
      
          ApexPages.currentPage().getParameters().put('searchText','9 day turnaround');
          GrantingFileAccessToUsersExtn cntrl = new GrantingFileAccessToUsersExtn(new ApexPages.StandardController(dep));
          system.runAs(new User(Id=UserInfo.getUserId())){
              Test.startTest();
                  cntrl.init();
                  cntrl = new GrantingFileAccessToUsersExtn(new ApexPages.StandardController(dep));
                  cntrl.callInitFullTextSearch();
                  if( cntrl.lstFiles == NULL){
                       cntrl.lstFiles = new List<S3FileModel >();
                       cntrl.lstFiles.add(new S3FileModel(new AWS_S3_Object__c(File_Name__c='test',File_Id__c='test'),false))   ;
                  }
                  for(S3FileModel s3File : cntrl.lstFiles){
                      s3File.isSelected= true;
                  }
                  cntrl.saveFiles();  
                  cntrl.selectedUsers = new List<SelectOption>();
                  cntrl.selectedUsers.add(new selectOption(attendee.id,attendee.id));
                  cntrl.NotifyRecipients=true;
                  cntrl.fetchUploadBatch();
                  cntrl.grantAccess();
             Test.stoptest();
         }
         
         GrantedFilesCntrl cntrl2 = new GrantedFilesCntrl ();
         cntrl2.getAccessFiles();
         
  }
  
  
  @isTest
  private static void Test_method2(){
      Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
      Deposition__c dep = TestUtility.createDeposition(null);
      dep.Case_Name__c='Test';
      /*insert dep;
      ApexPages.currentPage().getParameters().put('folderId','testfolderId');
      User usr = TestUtility.createCommunityUser();
      
      Contact con = [select id,accountId From Contact LIMIT 1];
      Attendee__c attendee = TestUtility.createAttendee(con.id,dep.id);
      insert attendee;*/
      Test.startTest();
          ApexPages.currentPage().getParameters().put('searchText','9 day turnaround');
          GrantingFileAccessToUsersExtn cntrl = new GrantingFileAccessToUsersExtn(new ApexPages.StandardController(dep));
          system.runAs(new User(Id=UserInfo.getUserId())){
              
              cntrl.init();
              cntrl = new GrantingFileAccessToUsersExtn(new ApexPages.StandardController(dep));
              cntrl.callInitFullTextSearch();
              if( cntrl.lstFiles == NULL)
                   cntrl.lstFiles = new List<S3FileModel >();
              
         }
  }
    @isTest
    private static void Test_manual(){
      Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        TestFactory tFact = new TestFactory();
        List<Invoice_Item__c> items = tFact.invoiceItems;
        List<Contact> contacts = tFact.contacts;
        List<Deposition__c> depositions = tFact.depositions;
        List<Attendee__c> attendees = tFact.attendees;
        
        
        Upload_Files__c upFile = new Upload_Files__c (Contact__c=contacts[0].Id, Deposition__c  = depositions[0].Id);
        insert upFile;
        List<AWS_S3_Object__c> s3 = new List<AWS_S3_Object__c>();
        s3.add(new AWS_S3_Object__c(File_Type__c='Deposition Notice', Deposition__c= depositions[0].Id, 
                                    File_Name__c='test',Upload_Files__c=upFile.id ));
        insert s3;
        File_Access__c fl =  new File_Access__c(Attendee__c=attendees[0].Id, File__c =s3[0].Id);
        insert fl;
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('fileId',s3[0].Id);
        GrantingFileAccessToUsersExtn cntrl = new GrantingFileAccessToUsersExtn(new ApexPages.StandardController(depositions[0]));
        cntrl.goBack();
        cntrl.callInitFullTextSearch();
        if( cntrl.lstFiles == NULL || cntrl.lstFiles.isEmpty()){
            cntrl.lstFiles = new List<S3FileModel >();
            cntrl.lstFiles.add(new S3FileModel(new AWS_S3_Object__c(File_Name__c='test',File_Id__c='test',Upload_Files__c=upFile.id),false));
            cntrl.lstFiles.add(new S3FileModel(new AWS_S3_Object__c(File_Name__c='test2',File_Id__c='test2',Upload_Files__c=upFile.id),false));
        }
        cntrl.init();
        cntrl.initFullTextSearch(new Set<String>{'s'});
        cntrl.loadS3Files(new Set<String>{'s'});
        for(S3FileModel s3File : cntrl.lstFiles){
            s3File.isSelected= true;
        }
        cntrl.saveFiles();
        cntrl.selectedDepFileIndex=0;
        cntrl.updateDepFileType();
        cntrl.fetchUploadBatch();
        cntrl.grantAccess();
        
        Test.stopTest();
    }
}