src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Location</label>
        <referenceTo>Deposition_Location__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>CR_Email_Address__c</fullName>
        <label>CR Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Location__c</fullName>
        <label>Deposition Location</label>
        <scale>14</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite Level (Business Days)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Same day turnaround</fullName>
                </value>
                <value>
                    <fullName>Next day turnaround</fullName>
                </value>
                <value>
                    <fullName>2 day turnaround</fullName>
                </value>
                <value>
                    <fullName>3 day turnaround</fullName>
                </value>
                <value>
                    <fullName>4 day turnaround</fullName>
                </value>
                <value>
                    <fullName>5 day turnaround</fullName>
                </value>
                <value>
                    <fullName>6 day turnaround</fullName>
                </value>
                <value>
                    <fullName>7 day turnaround</fullName>
                </value>
                <value>
                    <fullName>8 day turnaround</fullName>
                </value>
                <value>
                    <fullName>9 day turnaround</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vidyo_Room__c</fullName>
        <label>Vidyo Room</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NextGen</fullName>
                </value>
                <value>
                    <fullName>Caren</fullName>
                </value>
                <value>
                    <fullName>Michele</fullName>
                </value>
                <value>
                    <fullName>Scot</fullName>
                </value>
                <value>
                    <fullName>Scott</fullName>
                </value>
                <value>
                    <fullName>Ken</fullName>
                </value>
                <value>
                    <fullName>Jason</fullName>
                </value>
                <value>
                    <fullName>Brennan</fullName>
                </value>
                <value>
                    <fullName>Jerry</fullName>
                </value>
                <value>
                    <fullName>Jeremy</fullName>
                </value>
                <value>
                    <fullName>Troy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deposition_Location__c.object
<CustomObject>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Deposition Locations</relationshipLabel>
        <relationshipName>Deposition_Location</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <label>Room</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>nextgen 1</fullName>
                </value>
                <value>
                    <fullName>nextgen 2</fullName>
                </value>
                <value>
                    <fullName>nextgen 3</fullName>
                </value>
                <value>
                    <fullName>nextgen 4</fullName>
                </value>
                <value>
                    <fullName>nextgen 5</fullName>
                </value>
                <value>
                    <fullName>nextgen 6</fullName>
                </value>
                <value>
                    <fullName>nextgen 7</fullName>
                </value>
                <value>
                    <fullName>nextgen 8</fullName>
                </value>
                <value>
                    <fullName>nextgen 9</fullName>
                </value>
                <value>
                    <fullName>nextgen10</fullName>
                </value>
                <value>
                    <fullName>nextgen 11</fullName>
                </value>
                <value>
                    <fullName>nextgen 12</fullName>
                </value>
                <value>
                    <fullName>nextgen 13</fullName>
                </value>
                <value>
                    <fullName>nextgen 14</fullName>
                </value>
                <value>
                    <fullName>nextgen 15</fullName>
                </value>
                <value>
                    <fullName>nextgen 16</fullName>
                </value>
                <value>
                    <fullName>nextgen 17</fullName>
                </value>
                <value>
                    <fullName>nextgen 18</fullName>
                </value>
                <value>
                    <fullName>nextgen 19</fullName>
                </value>
                <value>
                    <fullName>nextgen 20</fullName>
                </value>
                <value>
                    <fullName>nextgen 21</fullName>
                </value>
                <value>
                    <fullName>nextgen 22</fullName>
                </value>
                <value>
                    <fullName>nextgen 23</fullName>
                </value>
                <value>
                    <fullName>nextgen 24</fullName>
                </value>
                <value>
                    <fullName>nextgen 25</fullName>
                </value>
                <value>
                    <fullName>nextgen 26</fullName>
                </value>
                <value>
                    <fullName>nextgen 27</fullName>
                </value>
                <value>
                    <fullName>nextgen 28</fullName>
                </value>
                <value>
                    <fullName>nextgen 29</fullName>
                </value>
                <value>
                    <fullName>nextgen 30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition Location</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposition Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Signature__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Signature</label>
    <nameField>
        <label>Signature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUtils.cls
/*****************************************************************
*Created on : July 23rd, 2012
*Purpose : A testing utils class to generate records for testing 
******************************************************************/
public class TestUtils {
  
  public Contact insertContact(ID accountID) {
    Contact contact = new Contact(LastName = 'AAAAAA',Email = 'a@a.com',CR_Status__c = 'A - Great');
    contact.AccountId = accountId;
    insert contact;
    
    return contact;
  }
  
  public Account insertAccount() {
    Account account = new Account(Name = 'AAAAA',Industry = 'Court Reporting');
    insert account;
    
    return account;
  }
  
  public Deposition__c createDeposition() {
    Account account = insertAccount();
    Deposition__c deposition = insertDeposition(account.Id);
    
    return deposition;
  }
  
  public Deposition__c insertDeposition(Id accountId) {
    List<Deposition__c>lstDeposition = new List<Deposition__c >();
    List<Deposition__c>lstDeleteDepostions = [select id from Deposition__c];
    if(lstDeleteDepostions.size()>0)
        delete lstDeleteDepostions ;
    Deposition__c deposition = new Deposition__c(Expedite__c = '9 day turnaround',Deposition_Date__c = System.today(),
                                                 CR_Email_Address__c='test@gmail.com',Vidyo_Room__c='1');
    lstDeposition.add(deposition);
    
    Deposition__c deposition1 = new Deposition__c(Expedite__c = '9 day turnaround',Deposition_Date__c = Date.today().addDays(-1),
                                               CR_Email_Address__c='test2@gmail.com',Vidyo_Room__c='2');
    lstDeposition.add(deposition1 );
    insert lstDeposition;
    
    return deposition;
  }
  public Static Deposition__c insertDepositionWithDepostionGroup(Id accountId,Id caseId,Integer vidyoRoom) {
    List<Deposition__c>lstDeposition = new List<Deposition__c >();
    Deposition__c deposition = new Deposition__c(Deposition_Group__c=caseId,Expedite__c = '9 day turnaround',Deposition_Date__c = System.today(),
                                                CR_Email_Address__c='test@gmail.com',Vidyo_Room__c=vidyoRoom+'');
    Deposition__c deposition1 = new Deposition__c(Deposition_Group__c=caseId,Expedite__c = '9 day turnaround',Deposition_Date__c = System.today(),
                                                 CR_Email_Address__c='test@gmail.com',Vidyo_Room__c=vidyoRoom+1+'');
    lstDeposition.add(deposition);
    lstDeposition.add(deposition1);
    insert lstDeposition;
    
    return deposition;
  }
  
  public Deposition_Location__c createDepositionLocation(Deposition__c deposition) {
    Deposition_Location__c location =  new Deposition_Location__c(Deposition__c = deposition.Id);
    location.Room__c = 'Hello';
    
    insert location;
    
    return location;
  }
  
  public Attendee__c insertAttendee(Id contactId,Id depositionID) {
    Attendee__c attendee = new Attendee__c(Contact__c = contactId,Deposition__c = depositionID);
    insert attendee;
    
    Attendee__c attendee1 = new Attendee__c(Contact__c = contactId,Deposition__c = depositionID);
    insert attendee1;
    
    return attendee;
  }
  
  public Static Signature__c createSignature(){
      Signature__c signature = new Signature__c(Name='Test Signature',Active__c=true);
      return signature;
  }
}