src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attendee_Role__c</fullName>
        <formula>TEXT( Attendee__r.Role__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attendee Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conga_Firm_Name__c</fullName>
        <formula>Deposition__r.Primary_Court_Reporting_Firm__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Conga Firm Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <formula>Invoice_Amount__c - Paid_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>IF(Paid_Amount__c&gt;= Invoice_Amount__c,&apos;Paid&apos;,IF(Paid_Amount__c==0,&apos;Unpaid&apos;,IF(Paid_Amount__c&gt;0,&apos;Partial&apos;,&apos;&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Reporter</fullName>
                </value>
                <value>
                    <fullName>Transcription</fullName>
                </value>
                <value>
                    <fullName>Video/Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Paid_in_Full__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paid in Full</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                    <default>true</default>
                    <label>Check</label>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Misc. Receivables</fullName>
                </value>
                <value>
                    <fullName>Write Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Payment</fullName>
                    <default>true</default>
                    <label>Payment</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Finance Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResourcePaymentCtlr.cls
public class ResourcePaymentCtlr {
    public static final Integer QUERY_LIMIT = 10000;
    public static final Integer PAGE_SIZE = (test.isRunningTest() ? 1 : Integer.valueOf(System.label.ManageInvoicePaymentsPageSize));

    public Map<String, List<InvoicePaymentWrapper>> firmToInvoicesMap{get;set;}
    public List<InvoicePaymentWrapper> invoices{get;set;}
    public List<PaymentData> paymentData{get;set;}
    public List<Payment__c> payments{get;set;}
    public String startDate{get;set;}
    public String endDate{get;set;}
    
    public Boolean isPaymentDone{get;set;}
    
    public String sortExp = 'Invoice_Date__c';
    public String sortDirection{
        get{
            //if not column is selected 
            if (sortExpression == null || sortExpression == '')
                sortDirection = 'ASC';
            if( sortDirection == null)
                sortDirection = 'ASC';
            return sortDirection;
        }set;
    }
    public String sortExpression{
        get{
            return sortExp;
        }
        set{
            //if the column is clicked on then switch between Ascending and Descending modes
            if (value == sortExp)
                sortDirection = (sortDirection == 'ASC')? 'DESC' : 'ASC';
            else
                sortDirection = 'ASC';
            sortExp = value;
        }
    }
    public String header{
        get{
            return 'Account Name,Invoice #,Deposition #,Contact Name,Date of Deposition,Amount,Unique identifier for this person,Role,Attendee Role,Conga Firm Name,Invoice date, Payment date, Payment Type';
        }set;
    }
    
    public class InvoicePaymentWrapper{
        public boolean isSelect {get;set;}
        public Invoice__c inv{get;set;}
        public InvoicePaymentWrapper(Invoice__c inv){
            isSelect=true;
            this.inv=inv;
        }
    }
    public class PaymentData{
        public String pdate{get;set;}
        public String invName{get;set;}
        public String pType{get;set;}
        public Invoice__c inv{get;set;}
        public PaymentData(String pdate, String invName, String pType, Invoice__c inv){
            this.pdate = pdate;
            this.invName = invName;
            this.pType = pType;
            this.inv = inv;
        }
    }
    
    public ResourcePaymentCtlr() {
        isPaymentDone = false;
        init();
    }
    
    public void init(){
        prepareRecord();
    }
    void prepareRecord(){
        invoices = new List<InvoicePaymentWrapper>();
        
        firmToInvoicesMap = new Map<String, List<InvoicePaymentWrapper>>();
        try{
            for (Invoice__c inv : (List<Invoice__c>)setCon.getRecords()){
                invoices.add(new InvoicePaymentWrapper(inv));
            }
        }catch(Exception excp){
            System.debug(excp.getStackTraceString());
        }
    }
    /** Instantiate the StandardSetController from a query locater*/
    ApexPages.StandardSetController setCon {
        get {
            if (setCon == null) {
                prepareSetCon();
            }
            return setCon;
        }
        set;
    }
    String addInvoiceDateFilter(String val, String op, Boolean isStart){
        String filter ='';
        if(String.isNotBlank(val)){
            List<String> dateParts = val.split('/');
            if(dateParts.size() == 3){
                // 4/26/2019
                //2019-4-26
                Integer day = Integer.valueOf(dateParts[1]);
                Integer mon = Integer.valueOf(dateParts[0]);
                Integer year = Integer.valueOf(dateParts[2]);
                filter+=' AND Invoice_Date__c'+op+year+'-'+(mon<10 ? '0':'')+mon+'-'+ (day<10 ? '0':'')+day;

                if(isStart){
                    InvoiceEmailNotificationQueueable.MIN_DATE = Date.newInstance(year,mon,day);
                }else{
                    InvoiceEmailNotificationQueueable.MAX_DATE = Date.newInstance(year,mon,day);
                }
            }
        }
        return filter;
    }
    void prepareSetCon(){
        String query = 'SELECT Id, Name, Deposition__c, Account__c,Conga_Firm_Name__c,Attendee_Role__c'
                    +', Contact__c, Contact__r.Name,Contact__r.Payment_Method__c, Contact__r.ADP_ID__c,Contact__r.Account.Name '
                    +', Deposition__r.Name, Deposition__r.Deposition_Date__c, Invoice_Date__c, Due_Amount__c  '
                    +', Deposition__r.Primary_Court_Reporting_Firm__r.Name'
                    +', Attendee__c,Attendee__r.Role__c'
                    +' FROM Invoice__c ';
        
        query+=' WHERE Type__c!=\'Client\' AND Payment_Status__c !=\'Paid\' AND Status__c=\'Valid\' AND Deposition__c != NULL'
            +' AND Deposition__r.Primary_Court_Reporting_Firm__c!=null ';
        System.debug(startDate);
        System.debug(endDate);
        InvoiceEmailNotificationQueueable.MIN_DATE = null;
        query += addInvoiceDateFilter(startDate, '>=', true);
        InvoiceEmailNotificationQueueable.MAX_DATE = null;
        query += addInvoiceDateFilter(endDate, '<=', false);
        query += ' ORDER BY ' + sortExpression + ' ' + sortDirection + ' NULLS LAST';
        query +=' LIMIT : QUERY_LIMIT';
        system.debug('query::' + query);
        
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(query));

        setCon.setPageSize(PAGE_SIZE);
    }
    
    /** indicates whether there are more records after the current page set.*/
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }
    
    /** indicates whether there are more records before the current page set.*/
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }
    
    /** returns the page number of the current page set*/
    public Integer pageNumber {
        get {
            return setCon.getPageNumber();
        }
        set;
    }
    
    /** return total number of pages for page set*/
    Public Integer getTotalPages(){
        Decimal totalSize = setCon.getResultSize();
        Decimal pageSize = setCon.getPageSize();
        Decimal pages = totalSize/pageSize;
        return (Integer)pages.round(System.RoundingMode.CEILING);
    }
    
    /** returns the first page of the page set*/
    public void first() {
        setCon.first();
        init();
    }
    
    /** returns the last page of the page set*/
    public void last() {
        setCon.last();
        init();
    }
    
    /** returns the previous page of the page set*/
    public void previous() {
        setCon.previous();
        init();
    }
    
    /** returns the next page of the page set*/
    public void next() {
        setCon.next();
        init();
    }
    
    /*public void setSelectedDateforAll(){
        for(List<InvoicePaymentWrapper> InvoiceList : firmToInvoicesMap.values()){
            for(InvoicePaymentWrapper wrapItem :InvoiceList ){
                // wrapItem.payment.Date__c = selectedPaymentDate;
            }
        }
    }*/
    public void doSort (){
        prepareSetCon();
        first();
    }
    public void onSearch(){
        prepareSetCon();
        prepareRecord();
    }
    
    public void onPay(){
        Boolean isSelected = false;
        payments = new List<Payment__c>();
        paymentData = new List<PaymentData>();
        for(InvoicePaymentWrapper invData:invoices){
            if(invData.isSelect){
                isSelected = true;
                Payment__c pay = new Payment__c(Invoice__c = invData.inv.Id, Date__c = System.today(), Amount__c = invData.inv.Due_Amount__c,
                        Paid_in_Full__c = true, Payment_Type__c = invData.inv.Contact__r.Payment_Method__c);
                
                payments.add(pay);
                pay.Invoice__r = invData.inv;
                paymentData.add(new PaymentData(pay.Date__c.format(), invData.inv.Name, pay.Payment_Type__c, invData.inv));
            }
        }
        if(!isSelected){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Select at least one invoice to pay!'));
            return;
        }
        try{
            InvoiceEmailNotificationQueueable.MIN_DATE = null;
            addInvoiceDateFilter(startDate, '>=', true);
            InvoiceEmailNotificationQueueable.MAX_DATE = null;
            addInvoiceDateFilter(endDate, '<=', false);
            insert payments;
            isPaymentDone = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'payment Done!'));

        }catch(Exception excp){
            ApexPages.addMessages(excp);
        }
    }
    
    public PageReference onExport(){
        return new PageReference('/apex/ResourcePayment?isExport=true');
    }
}