src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VideoLinkExtn.cls
/**
                                Name             : VideoLinkExtn
                                Date             : 10 MARCH 2016
                                Description      : That class is used by VideoLink VF Page for redirect user to ZOOM ID URL
                                                   IF deposition date = today
*/
public class VideoLinkExtn {
    public Boolean isAttendeeFound{get;set;}
    public VideoLinkExtn(ApexPages.StandardController sc) {
        isAttendeeFound = false;
        
        List<Attendee__c>lstAttendees = new List<Attendee__c>();
        String attendeeId = ApexPages.CurrentPage().getParameters().get('attendeeId');
        String contactid = ApexPages.CurrentPage().getParameters().get('contactid');
        if(contactid != NULL && contactid.trim().length()>0){
             lstAttendees = [select Id From Attendee__c 
                           WHERE Deposition__c =: sc.getId() AND 
                           Contact__c=:contactid ];
        }else{
            lstAttendees = [select Id From Attendee__c 
                           WHERE Deposition__c =: sc.getId() AND 
                           Name=:attendeeId ];
        }                         
        if(lstAttendees.size()>0)
           isAttendeeFound = true;
      
    }

}