src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Confirm_Interpreter__c</fullName>
        <label>Confirm - Interpreter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestConfirmEmailCtrl.cls
/**************************************************
                Name        : TestConfirmEmailCtrl
                Author      : Lalit karamchandani
                Purpose     : This is used to allow user to select deposition and attendee(s) and send email confirmation/recap
                Created Date: 22 Apr 2019
                
                
*****************************************************/
public class TestConfirmEmailCtrl {

    public Invoice__c inv{get;set;}
    public Deposition__c dep{get;set;}
    public String selectedAttendees{get;set;}
    
    public List<SelectOption> attendees{get;set;}
    public Map<Id, Attendee__c> attendeeMap{get;set;}
    
    public TestConfirmEmailCtrl(){
        inv = new Invoice__c();
        resetAttendees();
    }
    
    void resetAttendees(){
        attendees = new List<SelectOption>{new SelectOption('','--none--')};
        attendeeMap = new Map<Id, Attendee__c>();
        selectedAttendees = '';
    }
    /*
    public void onSendTest(){
        Map<Deposition__c, List<Attendee__c>> depositionAttendeeMap = new Map<Deposition__c, List<Attendee__c>>();
        depositionAttendeeMap.put(new Deposition__c(Id=inv.Deposition__c),new List<Attendee__c>{new Attendee__c(Contact__c = inv.Contact__c)});
        DepositionReminderScheduler reminder = new DepositionReminderScheduler();
        reminder.sendDepositionEmail(depositionAttendeeMap);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Contact will get an Email, check the email'));
    }
    */
    public void onDepChange(){
        resetAttendees();
        dep = NULL;
        if(inv.Deposition__c!=NULL){
            dep = [SELECT Id, Confirm_Reporter__c, Confirm_Video_Tech__c, Confirm_Interpreter__c, Deposition_Status__C
                    FROM Deposition__c WHERE Id=:inv.Deposition__c];
            
            for(Attendee__c att : [SELECT Id, Contact__c, Contact__r.Name, Role__c 
                                    From Attendee__c WHERE Deposition__c = : inv.Deposition__c
                                    AND Role__c in ('Court Reporter','Videographer/Technician','Interpreter')]){
                attendees.add(new SelectOption(att.Id, att.Contact__r.Name+'('+att.Role__c+')'));
                attendeeMap.put(att.Id,att);
            }
            
        }
    }
    public void onSendConfirmationNotification(){
        // System.debug(selectedAttendees);
        if(String.isNotBlank(selectedAttendees)){
            String conId = attendeeMap.get(selectedAttendees).Contact__c;
            // System.debug(conId);
            DepositionReminderScheduler reminder = new DepositionReminderScheduler();
            reminder.setIncludeTimeZone(false);
            reminder.setContactIds(new Set<Id>{conId});
            reminder.processNotification(new set<Id>{inv.Deposition__c});
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Contact will get an Email AND SMS, check the email'));
        }
    }
    public void onSendRecapNotification(){
        if(String.isNotBlank(selectedAttendees)){
            String conId = attendeeMap.get(selectedAttendees).Contact__c;
            DepositionDayReminderScheduler reminder = new DepositionDayReminderScheduler();
            reminder.setIncludeTimeZone(false);
            reminder.setContactIds(new Set<Id>{conId});
            reminder.processNotification(new set<Id>{inv.Deposition__c});
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Contact will get an Email AND SMS, check the email'));
        }
    }
}