src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Received</fullName>
                    <default>true</default>
                    <label>Not Received</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Id__c</fullName>
        <externalId>true</externalId>
        <label>File Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposition Notice</fullName>
                </value>
                <value>
                    <fullName>Exhibit</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Signature Page</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Turn-in Sheet</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Folder_Id__c</fullName>
        <formula>Deposition__r.Google_Drive_Folder_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Folder Id</label>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Status_Reporter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Received - Reporter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Status_Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Received - Video</label>
        <type>Checkbox</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FilesTriggerHandler.cls
/**************************************************
                Name        : FilesTriggerHandler
                Purpose     : Files object Trigger handler
                Created Date: 19 FEB 2017
                
                Modification History:
*****************************************************/

public class FilesTriggerHandler extends TriggerHandler {

    public FilesTriggerHandler() {}

    /* context overrides */
    protected override  void afterUpdate() {
        updateDepositonInformation();
        Map<Id,AWS_S3_Object__c>oldMap = (Map<id,AWS_S3_Object__c>)trigger.oldmap;
        List<AWS_S3_Object__c>lstFiles = new List<AWS_S3_Object__c>();
        for(AWS_S3_Object__c file: (List<AWS_S3_Object__c>)trigger.new){
            if( file.File_Id__c != '' && file.File_Id__c != NULL && (file.File_name__c !=oldmap.get(file.id).File_Name__c
            || file.Deposition__c!=oldmap.get(file.id).Deposition__c) ){
                lstFiles.add(file);
            }
        }
        if(lstFiles.size()>0){
            if(System.isBatch() || System.isFuture())
                callUpdateFileOnGoogleDrive(Json.serialize(lstFiles));
            else
                futureCallUpdateFileOnGoogleDrive(Json.serialize(lstFiles));
        }
    }
    protected override  void afterdelete() {
        set<String>setFileIds = new Set<String>();
        
        for(AWS_S3_Object__c file: (List<AWS_S3_Object__c>)trigger.old){
            if( file.File_Id__c != '' && file.File_Id__c != NULL){
                setFileIds.add(file.File_Id__c );
            }
        }
        if(setFileIds.size()>0){
            if(System.isBatch() || System.isFuture())
                callDeleteFileFromGoogleDrive(setFileIds);
            else
                futureCallDeleteFileFromGoogleDrive(setFileIds);
        }
        
    }
    

    /* private methods */
    
    private static void updateDepositonInformation() {
        set<Id>setDepIds = new Set<Id>();
        Map<Id,AWS_S3_Object__c>oldMap = (Map<Id,AWS_S3_Object__c>)trigger.oldmap;
        for(AWS_S3_Object__c file: (List<AWS_S3_Object__c>)trigger.new){
            if( file.File_Type__c =='Invoice' && file.File_Type__c!= oldmap.get(file.id).File_Type__c){
                setDepIds.add(file.Deposition__c);
            }
        }
        if(setDepIds.size()>0){
            User Usr = [select id,ContactId From User WHERE Id=:Userinfo.getUserId()];
            if(usr.Contactid != NULL){
                List<Attendee__c>lstAttendees = [select Id,Role__c,Invoice_Status__c From Attendee__c WHERE Deposition__c IN:setDepIds
                                                 AND Contact__c=:usr.ContactId AND Role__c IN ('Videographer/Technician','Court Reporter') ];
                if(lstAttendees.size()>0){
                    List<Deposition__c>lstDepNeedUpdate = new List<Deposition__c>();
                    map<Id,Attendee__c>mapAttendeesNeedUpdate = new Map<Id,Attendee__c>();
                    for(Id depId : setDepIds){
                        Boolean updateDep = false;
                        Deposition__c dep = new Deposition__c(Id= depId);
                        for(Attendee__c attendee : lstAttendees){
                            if(attendee.Role__c=='Court Reporter'){
                                dep.Invoice_Status_Reporter__c = true;
                                updateDep=true;
                            }else if(attendee.Role__c=='Videographer/Technician'){
                                dep.Invoice_Status_Video__c= true;
                                updateDep=true;
                            }
                            if(attendee.Invoice_Status__c !='Received'){
                                attendee.Invoice_Status__c = 'Received';
                                mapAttendeesNeedUpdate.put(attendee.id,attendee);
                            }
                            
                        }
                        if(updateDep)
                           lstDepNeedUpdate.add(dep); 
                        if(mapAttendeesNeedUpdate.size()>0)
                            update mapAttendeesNeedUpdate.values();
                    }
                    
                    if(lstDepNeedUpdate.size()>0)
                        update lstDepNeedUpdate;
                }
            }
        }
        
    }
    
    //Delete a file from Google Drive
    private static void deleteFileFromGoogleDrive(Set<String>setFileIds) {
        
            String accessToken = '';
            if(Test.isRunningTest())
                accessToken = 'Testing';    
            else 
                accessToken =GoogleDriveAuthenticationCntrl.getAccessToken();
    
            for(String fileId : setFileIds){
            
                try{
                    HttpRequest req = new HttpRequest();
                    req.setMethod('POST');
                    req.setEndpoint('https://www.googleapis.com/drive/v2/files/'+fileId+'/trash' );
                    req.setHeader('Authorization', 'Bearer '+accessToken);
                    req.setBody('');
                    req.setTimeout(60*1000);
                    
                    Http h = new Http();
                    String resp;
                    HttpResponse res = new HttpResponse();
                    if(Test.isRunningTest()==false)
                        res = h.send(req);
                    resp = res.getBody();
                    
                }Catch(Exception e ){
                    System.debug('Error in Google Drive delete File '+e.getMessage());
                }
            }
              
                    
       
    }
    
    private void callDeleteFileFromGoogleDrive(Set<String>setFileIds){
        deleteFileFromGoogleDrive(setFileIds);
        
    }
    @future(callout=true)
    private static void futureCallDeleteFileFromGoogleDrive(Set<String>setFileIds){
        deleteFileFromGoogleDrive(setFileIds);
    }
    
    //Delete a file from Google Drive
    private static void UpdateFileOnGoogleDrive(List<AWS_S3_object__c>lstFiles) {
        
            String accessToken = '';
            if(Test.isRunningTest())
                accessToken = 'Testing';    
            else 
                accessToken =GoogleDriveAuthenticationCntrl.getAccessToken();
    
            for(AWS_S3_Object__c file : lstFiles){
            
                try{
                    HttpRequest req = new HttpRequest();
                    
                    req.setEndpoint('https://www.googleapis.com/drive/v2/files/'+file.File_Id__c );
                    req.setHeader('Authorization', 'Bearer '+accessToken);
                    String fileBody = '{"title": "' +file.File_Name__c+ '"';
                    
                    if(file.Parent_Folder_Id__c != NULL && file.Parent_Folder_Id__c != '')
                        fileBody +=',"parents" : [{ "id": "'+file.Parent_Folder_Id__c +'" }]';
                        
                    fileBody +='}';
                    req.setBody(fileBody);
                    req.setHeader('Content-Type', 'application/json');
                    req.setHeader('X-HTTP-Method-Override','PATCH');
                    req.setMethod('POST');
                    req.setTimeout(60*1000);
                    
                    Http h = new Http();
                    String resp;
                    HttpResponse res = new HttpResponse();
                    if(Test.isRunningTest()==false)
                        res = h.send(req);
                    resp = res.getBody();
                    
                }Catch(Exception e ){
                    System.debug('Error in Google Drive delete File '+e.getMessage());
                }
            }
              
                    
       
    }
    
    private void callUpdateFileOnGoogleDrive(String jsonString){
        // Deserialize the list  from the JSON string.
         List<AWS_S3_Object__c> lstFiles=
          (List<AWS_S3_Object__c>)JSON.deserialize(jsonString, List<AWS_S3_Object__c>.class);
        UpdateFileOnGoogleDrive(lstFiles);
    }
    @future(callout=true)
    private static void futureCallUpdateFileOnGoogleDrive(string jsonString){
        // Deserialize the list  from the JSON string.
         List<AWS_S3_Object__c> lstFiles=
          (List<AWS_S3_Object__c>)JSON.deserialize(jsonString, List<AWS_S3_Object__c>.class);
        UpdateFileOnGoogleDrive(lstFiles);
    }
    
}