src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <formula>IF(ISBlank(TEXT(Contact__r.VIP_Level__c)),Text(Contact__r.Account.VIP_Level__c),Text(Contact__r.VIP_Level__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIP Level</label>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>CR_Email_Address__c</fullName>
        <label>CR Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite Level (Business Days)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Same day turnaround</fullName>
                </value>
                <value>
                    <fullName>Next day turnaround</fullName>
                </value>
                <value>
                    <fullName>2 day turnaround</fullName>
                </value>
                <value>
                    <fullName>3 day turnaround</fullName>
                </value>
                <value>
                    <fullName>4 day turnaround</fullName>
                </value>
                <value>
                    <fullName>5 day turnaround</fullName>
                </value>
                <value>
                    <fullName>6 day turnaround</fullName>
                </value>
                <value>
                    <fullName>7 day turnaround</fullName>
                </value>
                <value>
                    <fullName>8 day turnaround</fullName>
                </value>
                <value>
                    <fullName>9 day turnaround</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <label>VIP Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP 1</fullName>
                </value>
                <value>
                    <fullName>VIP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Videographer_Email_Address__c</fullName>
        <label>Videographer Email</label>
        <type>Email</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CommunitiesCalendarCntrl.cls
/**
                                    Name             : CommunitiesCalendarCntrl
                                    Date             : 08 JUNE 2018
                                    Descripition     : That Class is used by "CommunitiesCalendar" vf page for display a calendar and allow
                                                       User to select a date in calendar and it will load depositions records that are exits on that date
                                                       as well as alllow them to modify this field values:
                                                        -          State
                                                        -          Event location
                                                        -          Reporter assigned (either their name from the attendee record or CR Email address)
                                                        -          Videographer/tech assigned (either their name from the attendee record or CR Email address)
                                                        -          VIP Status
                                                        -          Case (Deposition Group)
                                                        -          Expedite Level
                                                        -          Deposition Services
                                                        -          Source
                                                        -          Due Date to Client
                                                        -          Corporate Client
                                                        -          Special Instructions
                                                        -          Networking/Covering For
                                                        -          Deposition Time
                                                        -          Esimate Duration
*/     
public class CommunitiesCalendarCntrl{
    public List<Deposition__c>lstDepositions {get;set;}
    public string selectedDate{get;set;}
    Date dt;
    public string SelectedType{get;set;}
    public string selctedBrand{get;set;}
    Public User currentUser{get;set;}
    public CommunitiesCalendarCntrl(){
        currentUser = [select id,Name,Contact.Account.Name,ContactId From User WHERE id=:UserInfo.getUserId()];
        
        selectedDate = System.today().month()+'/'+System.today().day()+'/'+System.today().year();
        selectedType = ApexPages.currentPage().getParameters().get('SelectedType');
        if(selectedType==null || selectedType.trim().length()==0)
            selectedType='Show all Jobs';
        selctedBrand = ApexPages.currentPage().getParameters().get('firm');
        if(selctedBrand == NULL)
            selctedBrand = '';
        system.debug('$$selctedBrand '+selctedBrand );
        fetchDayDepositions();
        
    }
    
    public void fetchDayDepositions(){
        dt = Date.parse(selectedDate);
        lstDepositions = fetchDepositions(dt);
    }
    
    @RemoteAction
    public static string eventdata(String startDate,String endDate,String selectedType,String selctedBrand){
    
        User usr = [select Id,ContactId,Contact.AccountId From User WHERE Id=:Userinfo.getUserId()];
        
        CalEvent[] events = new CalEvent[]{};
        String query = 'select Deposition_Time__c, Deposition_Date__c,Deponent_Name__c '; 
        query += ' From  Deposition__c WHERE  Deposition_Date__c != NULL '; 
        query += ' AND Deposition_Status__c != \'Cancelled\'';
        Date dtStart;
        Date dtEnd;
        if(startDate == '') 
            query += ' AND Deposition_Date__c =THIS_MONTH';
        else{
            dtStart = date.parse(startDate );
            dtEnd = date.parse(endDate);
            query += ' AND Deposition_Date__c >=:dtStart AND Deposition_Date__c <=:dtEnd';
            
        }
        if(selctedBrand!= NULL && selctedBrand.trim().length()>0)
            query += ' AND Primary_Court_Reporting_Firm__r.Name=:selctedBrand ';
        if(selectedType!='Show all Jobs' && selectedType !='All_Account_Depositions')
            query += ' AND VIP_Level__c != NULL '; 
       
        if(usr.ContactId != NULL){
            
           String attendeeQuery = 'select Id,Deposition__c From Attendee__c WHERE'+
                                   ' Deposition__r.Deposition_Date__c  >=Last_Month AND Deposition__r.Deposition_Date__c <=Next_Month';
           if(selectedType =='All_Account_Depositions')
               attendeeQuery +=' AND Contact__r.AccountId=\''+usr.Contact.AccountId+'\'';
           else
               attendeeQuery +=' AND Contact__c =\'' +usr.ContactId +'\'';
            Set<Id>setDepositionIds = new Set<Id>();
            for(Attendee__c attendee : Database.Query(attendeeQuery )){
                setDepositionIds.add(attendee.Deposition__c ) ;
            }
            query += ' AND (OwnerId =\''+ usr.Id+'\'  OR ID IN:setDepositionIds) ';
        }
        
        system.debug('$$$'+query );
        for(Deposition__c  dep: Database.Query(query )){
            
            calEvent myEvent = new calEvent();
            myEvent.title = '';
            if(dep.Deposition_Time__c != NULL)
                myEvent.title = dep.Deposition_Time__c ;
            if(dep.Deponent_Name__c == NULL)
                dep.Deponent_Name__c = '';
            if(myEvent.title != '')
                myEvent.title += ' - ';
            myEvent.title +=dep.Deponent_Name__c;
            myEvent.startString = ''+dep.Deposition_Date__c;
            myEvent.startString = myEvent.startString.split(' ')[0];
            events.add(myEvent);
        }

        string jsonEvents = JSON.serialize(events);
        jsonEvents = jsonEvents.replace('startString','start');
        return jsonEvents;
    }
    
     // Class to hold calendar event data
    public class CalEvent {
        public String title {get;set;}
        public String startString {get;set;}
    }
    private List<Deposition__c> fetchDepositions(Date dt){
        String query =  'select id,Name,Deposition_Date__c,State__c,Event_Location__c,CR_Email_Address__c,';
        query+=' Videographer_Email_Address__c,VIP_Level__c,Expedite__c,Deposition_Services__c,';
        query+=' Source__c,Corporate_Client_Source__c,';
        query+=' Primary_CR_Firm__c,Primary_Court_Reporting_Firm__c,Firm_Name__c,';
        query+='  Case_Name__c,Hiring_Firm__c,Deposition_Time__c,Estimated_Duration__c,Time_Zone__c,Deponent_Name__c';
        query+='  From Deposition__c WHERE Deposition_Date__c =:dt ';
        query+=' AND Deposition_Status__c != \'Cancelled\'  ';
        if(selectedType!='Show all Jobs' && selectedType !='All_Account_Depositions')
            query += ' AND VIP_Level__c != NULL ';
        if(selctedBrand!= NULL && selctedBrand.trim().length()>0)
            query += ' AND Primary_Court_Reporting_Firm__r.Name=:selctedBrand ';   
        
        if(currentUser.ContactId != NULL){
            
            String attendeeQuery = 'select Id,Deposition__c From Attendee__c WHERE'+
                                   ' Deposition__r.Deposition_Date__c =:dt';
           if(selectedType =='All_Account_Depositions')
               attendeeQuery +=' AND Contact__r.AccountId=\''+currentUser.Contact.AccountId+'\'';
           else
               attendeeQuery +=' AND Contact__c =\'' +currentUser.ContactId +'\'';
            Set<Id>setDepositionIds = new Set<Id>();
            for(Attendee__c attendee : Database.Query(attendeeQuery )){
                setDepositionIds.add(attendee.Deposition__c ) ;
            }
            query += ' AND (OwnerId =\''+ currentUser.Id+'\'  OR ID IN:setDepositionIds) ';
        }
        system.debug('$$'+query);
        
        query+=' ORDER By Name';
        return Database.Query(query);
    }
    public void saveDepositions(){
        try{
            List<Deposition__c>lstDepositionsNeedUpdate = new List<Deposition__c>();
            Map<Id,Deposition__c>mapDepositions = new Map<Id,Deposition__c>(fetchDepositions(dt));
            for(Deposition__c dep : lstDepositions ){
                Deposition__c oldDep = mapDepositions.get(dep.id);
                if(oldDep.State__c != dep.State__c || oldDep.Event_Location__c != dep.Event_Location__c || oldDep.CR_Email_Address__c != dep.CR_Email_Address__c|| 
                    oldDep.Videographer_Email_Address__c != dep.Videographer_Email_Address__c || oldDep.VIP_Level__c!= dep.VIP_Level__c|| 
                    oldDep.Expedite__c!= dep.Expedite__c|| 
                    oldDep.Deposition_Services__c!= dep.Deposition_Services__c|| oldDep.Source__c!= dep.Source__c|| 
                    oldDep.Corporate_Client_Source__c!= dep.Corporate_Client_Source__c|| 
                    oldDep.Primary_Court_Reporting_Firm__c != dep.Primary_Court_Reporting_Firm__c
                    || oldDep.Case_Name__c != dep.Case_Name__c
                    || oldDep.Hiring_Firm__c != dep.Hiring_Firm__c ||
                    oldDep.Primary_CR_Firm__c!= dep.Primary_CR_Firm__c||
                    oldDep.Deposition_Time__c!= dep.Deposition_Time__c||
                    oldDep.Estimated_Duration__c!= dep.Estimated_Duration__c
                    ){
                    lstDepositionsNeedUpdate.add(dep);    
                } 
            }
            if(lstDepositionsNeedUpdate.size()>0)
                update lstDepositionsNeedUpdate ;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Changes successfully saved.'));
        }Catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,e.getMessage()));
        }
    }
    
}