src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Deposition</fullName>
                    <default>true</default>
                    <label>Deposition</label>
                </value>
                <value>
                    <fullName>Examination Under Oath</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Statement Under Oath</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Video Playback</fullName>
                </value>
                <value>
                    <fullName>Client Meeting</fullName>
                </value>
                <value>
                    <fullName>Captioned Meeting</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Intra-co</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite Level (Business Days)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Same day turnaround</fullName>
                </value>
                <value>
                    <fullName>Next day turnaround</fullName>
                </value>
                <value>
                    <fullName>2 day turnaround</fullName>
                </value>
                <value>
                    <fullName>3 day turnaround</fullName>
                </value>
                <value>
                    <fullName>4 day turnaround</fullName>
                </value>
                <value>
                    <fullName>5 day turnaround</fullName>
                </value>
                <value>
                    <fullName>6 day turnaround</fullName>
                </value>
                <value>
                    <fullName>7 day turnaround</fullName>
                </value>
                <value>
                    <fullName>8 day turnaround</fullName>
                </value>
                <value>
                    <fullName>9 day turnaround</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Firm__c</fullName>
        <label>Hiring Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transcript_Due_From_Reporter_Computed__c</fullName>
        <inlineHelpText>Business days</inlineHelpText>
        <label>Transcript Due From Reporter (Computed)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Video_Tech_Instructions__c</fullName>
        <label>Video/Tech Instructions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Scheduling_Email_Address__c</fullName>
        <label>Scheduling Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Video_Email_Address__c</fullName>
        <label>Video Email Address</label>
        <type>Email</type>
    </fields>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConfirmController.cls
/*************************************************************************
 *Controller which confirms the participation of a court reporter
 **************************************************************************/
public class ConfirmController {

    public Boolean isError {
        get;
        set;
    }
    public Boolean isJobOpen {
        get;
        set;
    }
    public Deposition__c deposition {
        get;
        set;
    }
    public Boolean isAccepted {
        get;
        set;
    }
    public String type {
        get;
        set;
    }
    public Attendee__c attendee = new Attendee__c();

    private Contact contact;

    //===============================================//
    //Constructor
    //==============================================//
    public ConfirmController() {
        this.isError = false;
        this.isJobOpen = false;
        this.isAccepted = false;
        type = ApexPages.currentPage().getParameters().get('Type');
          this.contact = loadContact();
        this.deposition = loadDeposition();
        String selectedFirm = deposition.Primary_Court_Reporting_Firm__r.Name;
        system.debug('$$$'+selectedFirm );
        
        Cookie Cookie= new Cookie('firmCookie', null,null,0,false);
        ApexPages.currentPage().setCookies(new Cookie[]{Cookie});
        Cookie= new Cookie('firmCookie', selectedFirm,null,-1,false);
        ApexPages.currentPage().setCookies(new Cookie[]{Cookie});
        
        
    }

    public PageReference updateDeposition() {
        try {
            //Check if there is already a court Reporter for the job
            createAttendee(this.deposition, this.contact);
            //comfirmDepositionReporter();
            this.isAccepted = true;
        } catch (Exception ex) {
            System.debug('Exception ' + ex);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getmessage()));
            this.isError = true;
        }
        return null;
    }

    public PageReference confirmDeposition() {
        try {
            system.debug('$$$'+deposition.Deposition_Roles__r.size());
            if (deposition.Deposition_Roles__r.size() > 0 || deposition.Deposition_Status__c == 'Cancelled') {
                system.debug('$$hello');
                this.isError = false;
              
                sendEmail();
                if (isError == false && isJobOpen == false) {
                    //Contact contact = new Contact(Id=);
                    //contact.Already_Claimed_Job_Number__c = deposition.Name;
                    //contact.Notify_Already_Claimed_Job__c = true;
                    //update contact;

                    List < Messaging.SingleEmailMessage > mailList = new List < Messaging.SingleEmailMessage > ();
                    List < EmailTemplate > lstEmailTemplates = [select id, DeveloperName From EmailTemplate
                        WHERE DeveloperName = 'CR_Already_Claimed_Job_VF'
                    ];
                    
                    String fromEmail = deposition.Primary_Court_Reporting_Firm__r.Scheduling_email_address__c;
                    if(type== 'Videographer/Technician')
                        fromEmail = deposition.Primary_Court_Reporting_Firm__r.Video_Email_Address__c;
                    List < OrgWideEmailAddress > lstOrgWideEmailAddress = [SELECT id, Address
                        FROM OrgWideEmailAddress
                        where Address =:fromEmail
                    ];

                    if (lstEmailTemplates.size() > 0) {
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        mail.setTemplateId(lstEmailTemplates[0].id);
                        mail.setTargetObjectId(ApexPages.currentPage().getParameters().get('ctc'));
                        mail.setWhatId(deposition.id);
                        if(lstOrgWideEmailAddress.size()>0){
                            mail.setCCAddresses(new String[] {
                             lstOrgWideEmailAddress[0].Address
                            });
                            mail.setOrgWideEmailAddressId(lstOrgWideEmailAddress[0].id);
                        }
                        mailList.add(mail);
                    }
                    if (mailList.size() > 0) {
                        Messaging.sendEmail(mailList);
                    }
                }
                return null;
            }
           

            this.isJobOpen = true;
            this.isError = false;
        } catch (Exception ex) {
            this.isError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getmessage()));
            System.debug('Exception' + ex);
        }
        return null;
    }

    private void sendEmail() {

        
        /*
        Task task = new Task(WhatId = this.deposition.Id,Subject = 'Job Already Accepted');
        task.WhoId = contact.Id;
        task.Description = 'The contact tried to accept the job,but it was already booked';
    
        if(!String.isBlank(template.Username__c)) {
          List<User> lstUser = [SELECT Id FROM User WHERE Username = :template.Username__c];
          if(lstUser.size() > 0) {
            task.OwnerId = lstUser[0].Id;
          }  
        }
        insert task;*/
        if (checkIfAttendeeAlreadyExists(this.deposition, contact)) {
            this.isJobOpen = true;
            this.isAccepted = true;
            
        }
        

    }

    //========================================================================//
    //Load contact
    //========================================================================//
    private Contact loadContact() {
        String contactID = ApexPages.currentPage().getParameters().get('ctc');
        return [SELECT Id, Name, Email FROM Contact WHERE Id = : contactID Limit 1];
    }
    public PageReference comfirmDepositionReporter() {
        try {
            this.deposition = loadDeposition();
            /*if (type == 'Videographer/Technician')
                deposition.Confirm_Video_Tech__c = 'Confirmed';
            else
                deposition.Confirm_Reporter__c = 'Confirmed';
            update deposition;*/
        } catch (Exception ex) {
            this.isError = true;
            System.debug('Exception' + ex);
        }
        return null;
    }

    //===============================================================================//
    //Create Attendee record for the Depostion and Contact
    //===============================================================================//
    private void createAttendee(Deposition__c deposition, Contact contact) {
        /*
        //Check if the contact not already exists 
        List<Attendee__c> lstAttendee = [SELECT Id FROM Attendee__c WHERE Deposition__c = :deposition.ID 
                                         AND Contact__c = :contact.ID AND Role__c = 'Court Reporter'];
    
        //If the Contact already exists for the deposition as attendee, do not do anything
        if(lstAttendee.size() != 0) {
          return;
        }    */

        if (checkIfAttendeeAlreadyExists(deposition, contact)) {
            return;
        }

        Attendee__c attendee = new Attendee__c(Deposition__c = deposition.Id, Contact__c = contact.Id);
        attendee.Role__c = type;
        insert attendee;
        String fromEmail = deposition.Primary_Court_Reporting_Firm__r.Scheduling_email_address__c;
        String emailTemplateName = 'Reporter_Has_Accepted_Job_Online_VF';
        if(type== 'Videographer/Technician'){
            emailTemplateName = 'Videographer_Has_Accepted_Job_Online_VF';
            fromEmail = deposition.Primary_Court_Reporting_Firm__r.Video_Email_Address__c;
        }
        List < Messaging.SingleEmailMessage > mailList = new List < Messaging.SingleEmailMessage > ();
        List < EmailTemplate > lstEmailTemplates = [select id, DeveloperName From EmailTemplate
            WHERE DeveloperName = 'Reporter_Has_Accepted_Job_Online'
        ];
        
        
        //if(type!= 'Videographer/Technician'){
             List < OrgWideEmailAddress > lstOrgWideEmailAddress = [SELECT id, Address
                FROM OrgWideEmailAddress
                where Address =:fromEmail
            ];
    
            if (lstEmailTemplates.size() > 0) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTemplateId(lstEmailTemplates[0].id);
                mail.setTargetObjectId(ApexPages.currentPage().getParameters().get('ctc'));
                mail.setWhatId(attendee.id);
                if(lstOrgWideEmailAddress.size()>0){
                    List<String>lstCCEmails = new List<String>();
                    lstCCEmails.add(lstOrgWideEmailAddress[0].Address);
                    if(type== 'Videographer/Technician' && deposition.Primary_Court_Reporting_Firm__r.Scheduling_email_address__c != NULL)
                        lstCCEmails.add(deposition.Primary_Court_Reporting_Firm__r.Scheduling_email_address__c);
                    mail.setCCAddresses(lstCCEmails);
                    mail.setOrgWideEmailAddressId(lstOrgWideEmailAddress[0].id);
                }
                mailList.add(mail);
            }
            if (mailList.size() > 0) {
                try{
                    Messaging.sendEmail(mailList);
                } catch (Exception ex) {
                    this.isError = true;
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getmessage()));
                    System.debug('Exception' + ex);
                }
            }
        //}
    }

    private Boolean checkIfAttendeeAlreadyExists(Deposition__c deposition, Contact contact) {
        //Check if the contact not already exists 
        List < Attendee__c > lstAttendee = [SELECT Id FROM Attendee__c WHERE Deposition__c = : deposition.ID
            AND Contact__c = : contact.ID AND Role__c = : type
        ];

        //If the Contact already exists for the deposition as attendee, do not do anything
        if (lstAttendee.size() > 0) {
            return true;
        }
        return false;
    }

    //======================================================================//
    //Load deposition
    //======================================================================//
    private Deposition__c loadDeposition() {
        String depositionId = ApexPages.currentPage().getParameters().get('Dep');
        return [SELECT Id, Name, Primary_Court_Reporting_Firm__r.Name,Primary_Court_Reporting_Firm__r.Phone__c,Confirm_Reporter__c, Deposition_Date__c, Deposition_Time__c, Event_Location__c, Case_Name__c,
            Deponent_Name__c, Hiring_Attorney__c, Hiring_Firm__c, Deposition_Services__c, Event_Type__c, Video_Tech_Instructions__c,
            Expedite__c, Transcript_Due_From_Reporter_Computed__c, Deposition_Status__c, Event_Type_Lowercase__c, Transcript_Due_From_Reporter__c, Time_Zone__c,
            Primary_Court_Reporting_Firm__r.Scheduling_email_address__c,Primary_Court_Reporting_Firm__r.Video_Email_Address__c, (Select Name, Role__c From Deposition_Roles__r WHERE Role__c = : type)
            FROM Deposition__c WHERE Id = : depositionID Limit 1
        ];
    }

    

    //**********************TEST CLASS*******************************************************//
    @isTest
    private static void Test_ConfirmController() {
        Deposition__c deposition = new Deposition__c();
        insert deposition;

        Contact contact = new Contact(LastName = 'ab');
        insert contact;

        Test.setCurrentPage(Page.Confirm);
        ApexPages.currentPage().getParameters().put('Dep', deposition.ID);
        ApexPages.currentPage().getParameters().put('ctc', contact.ID);
        ApexPages.currentPage().getParameters().put('type', 'Court Reporter');
        ConfirmController ctrl = new ConfirmController();
        ctrl.confirmDeposition();
        ctrl.updateDeposition();
        ctrl.comfirmDepositionReporter();
        ctrl = new ConfirmController();
        ctrl.confirmDeposition();
        ctrl.updateDeposition();
        ctrl.comfirmDepositionReporter();
    }

}