src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>COD_Warning__c</fullName>
        <formula>if( Contact__r.Account.COD_Warning__c = TRUE, IMAGE(&quot;http://upload.wikimedia.org/wikipedia/commons/1/19/Portrait_of_Cod.jpg&quot;,&quot;COD Warning&quot;, 260, 350),&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>COD Warning</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Upload_Files__c</fullName>
        <label>Upload Batches</label>
        <referenceTo>Upload_Files__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Duration__c</fullName>
        <description>How long does the client expect this event to last?</description>
        <label>Estimated Duration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Deposition</fullName>
                    <default>true</default>
                    <label>Deposition</label>
                </value>
                <value>
                    <fullName>Examination Under Oath</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Statement Under Oath</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Video Playback</fullName>
                </value>
                <value>
                    <fullName>Client Meeting</fullName>
                </value>
                <value>
                    <fullName>Captioned Meeting</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Intra-co</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/File_Access__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipName>S3_File_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ Attendee__r.Contact__c ,   Attendee__r.Contact__r.FirstName  +&apos; &apos;+ Attendee__r.Contact__r.LastName,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <label>File Access</label>
    <nameField>
        <displayFormat>SFA-{00000000}</displayFormat>
        <label>S3 File Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Upload_Files__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Upload_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Upload_Files1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Upload Batches</label>
    <nameField>
        <displayFormat>UB-{0000000}</displayFormat>
        <label>Upload Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunitiesDepositionDetailCntrl.cls
/**************************************************
                Name        : CommunitiesDepositionDetailCntrl 
                Author      : Rajendra Rathore
                Purpose     : That class is used by CommunitiesDepositionDetail VF page for do following things:
                                A.) List All Transcripts files for Deposition
                                B.) List All Exhibits files for Deposition
                                C.) List All Videosfiles for Deposition
                                E.) Allow user to upload new files as well as allow them to specify File Type for newly upload files.
                Created Date: 25 JUNE 2016
                
                Modification History:
*****************************************************/
global class CommunitiesDepositionDetailCntrl {
    public Deposition__c webdeposition{get;set;}
    public String depDate{get;set;}
    public List<AWS_S3_Object__c>lstTranscripts{get;set;}
    public List<AWS_S3_Object__c>lstExhibits{get;set;}
    public List<AWS_S3_Object__c>lstVideos{get;set;}
    public User usr {get;set;}
    public List<AWS_S3_Object__c>lstFiles{get;set;}
    public Upload_Files__c uploadBatch{get;set;}
    public Integer latestUploadNo{get;set;}
    public String accessCodeToken{get;set;}
    public Integer selectedFileIndex{get;set;}
    public String selectedFileType{get;set;}
    public Boolean readonly{get;set;}
    
    public CommunitiesDepositionDetailCntrl(ApexPages.StandardController controller) {
        usr = [select id,ContactId,Contact.Account.Industry,Contact.Account.COD_Warning__c From User WHERE id=:Userinfo.getUserId()];
        lstFiles = new List<AWS_S3_Object__c>();
        webdeposition = (Deposition__c)controller.getRecord();
        List<Deposition__c>lstDeps = [select id,Name,Event_Type__c,Deponent_Name__c,Deposition_Status__c
                                 ,Deposition_Date__c,Deposition_Time__c,Time_Zone__c,Event_Location__c,
                                 Deposition_Services__c,Estimated_Duration__c,Case_Name__c
                                  From Deposition__c WHERE ID=:webdeposition.id];
        if(lstDeps.size()>0){
            webdeposition  = lstDeps[0];
            depDate = '';
            if(webdeposition.Deposition_Date__c!= NULL){
                String month= String.valueOf(webdeposition.Deposition_Date__c.Month());
                String day = String.valueOf(webdeposition.Deposition_Date__c.Day());
                if(Integer.valueOf(month)<10)
                    month = '0'+month;
                if(Integer.valueOf(day)<10)
                    day  = '0'+day;    
                depDate = month+'/'+day+'/'+webdeposition.Deposition_Date__c.Year();
                
                DateTime restricttion = System.now().addDays(2);
                readonly = false;
                if(webdeposition.Deposition_Date__c ==null || webdeposition.Deposition_Date__c<= restricttion){
                    readonly = true;
                }
                if(!readonly){
                    List<Attendee__c> att = [SELECT Id,Role__c FROM Attendee__c 
                                             WHERE Deposition__c =:webdeposition.Id and Contact__c=:usr.ContactId];
                    if(!att.isEmpty()){
                        readonly = (att[0].Role__c =='Court Reporter' || att[0].Role__c =='Videographer/Technician');
                    }
                }
            }
            if(readonly == null){
                readonly = !(usr.Contact.Account.Industry =='Court Reporting' || usr.Contact.Account.Industry =='Videography');
            }
        }
        loadFiles();
        
    }
    
    public void init(){
       if(Test.isRunningTest()==false)
           accessCodeToken = GoogleDriveAuthenticationCntrl.getAccessToken();
        /*List<Upload_Files__c>lstUploadFiles = [select Id,Latest_Upload_Number__c FROM Upload_Files__c WHERE Deposition__c=:webdeposition.id AND CreatedById=:Userinfo.getUserId()
                                              ORDER BY CREATEDDATE DESC];
        if(lstUploadFiles.size()>0)
            uploadBatch = lstUploadFiles[0];
        else{*/
            uploadBatch= new Upload_Files__c(Deposition__c=webdeposition.id,Contact__c=usr.ContactId,IP_Address__c=ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP'));
            insert uploadBatch;
        /*}*/
        if(uploadBatch.Latest_Upload_Number__c >0)
            latestUploadNo = Integer.valueOf(uploadBatch.Latest_Upload_Number__c+1);
        else
            latestUploadNo =1;
    }
    public void fetchUserFiles(){
      
      for(AWS_S3_Object__c s3Obj : [select id,File_Name__c,File_Type__c From AWS_S3_Object__c
                                    WHERE Deposition__c=:webdeposition.id 
                                    AND CreatedById=:UserInfo.getUserId() AND Upload_Files__c=:uploadBatch.id
                                    AND Upload_No__c=:latestUploadNo AND ID NOT IN: lstFiles]){
          lstFiles.add(s3Obj);
          
      }
      
    }
    
    @RemoteAction
    global static String createAwsS3Object(String fileName,String fileId, String uploadBatchId,String depostionId,String contentType,
                                              Integer fileSize,Integer uploadNumber ) {
            return UploadFilesController.createAwsS3Object(fileName,'',fileId,uploadBatchId,depostionId,contentType,fileSize,uploadNumber  );
            
    }
    
    public void updateFileType(){
      try{
          AWS_S3_Object__c fileObj = lstFiles[selectedFileIndex];
          fileObj.File_Type__c = selectedFileType;
          update fileObj;
       }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,ex.getMessage()));
      }
    }
    public void saveFiles(){
         try{
             if(lstFiles.size()>0 ){
                 update lstFiles;
                 loadFiles();
                 ApexPages.addMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'File Information Successfully Saved.')); 
             }
         }catch(Exception e){
             ApexPages.addMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage())); 
         }
    }
    public void loadFiles(){
        lstTranscripts = new List<AWS_S3_Object__c>();
        lstExhibits = new List<AWS_S3_Object__c>();
        lstVideos = new List<AWS_S3_Object__c>();
        Set<id>setFilesIds = new Set<Id>();
        for(File_Access__c fileAccess : [select File__c FROM File_Access__c WHERE Attendee__r.Contact__c =: usr.ContactId]){
            setFilesIds.add(fileAccess.File__c);
        }
        List<Attendee__c>lstAttendees = [select id FROM Attendee__c where Contact__c=:usr.ContactId AND Deposition__c=:webdeposition.id
                                             AND Role__c IN('Court Reporter','Interpreter','Videographer/Technician') ];
        if(lstAttendees.size()>0){
            for(AWS_S3_Object__c file : [select id,File_Id__c,File_Name__c,File_Type__c  From AWS_S3_Object__c WHERE Deposition__c=:webdeposition.id
                                    AND File_Type__c IN('Transcript','Exhibit','Video','','Deposition Notice')
                                    AND ( CreatedById=:UserInfo.getUserId() OR ID IN : setFilesIds OR File_Type__c='Deposition Notice')
                                     ]){
                if(file.File_Type__c =='Transcript' ||file.File_Type__c =='Deposition Notice' ||  ((file.File_Type__c == NULL || file.File_Type__c=='') && webdeposition.Deposition_Date__c!= NULL && webdeposition.Deposition_Date__c<System.Today() ) )
                   lstTranscripts.add(file);
                else if(file.File_Type__c =='Exhibit')
                    lstExhibits.add(file);
                else
                    lstVideos.add(file);
            }
        }else{
            for(AWS_S3_Object__c file : [select id,File_Id__c,File_Name__c,File_Type__c  From AWS_S3_Object__c WHERE Deposition__c=:webdeposition.id
                                    AND File_Type__c IN('Transcript','Exhibit','Video','')
                                    AND ( CreatedById=:UserInfo.getUserId() OR ID IN : setFilesIds)
                                     ]){
                if(file.File_Type__c =='Transcript' || ((file.File_Type__c == NULL || file.File_Type__c=='') && webdeposition.Deposition_Date__c!= NULL && webdeposition.Deposition_Date__c<System.Today() ) )
                   lstTranscripts.add(file);
                else if(file.File_Type__c =='Exhibit')
                    lstExhibits.add(file);
                else
                    lstVideos.add(file);
            }
        }
          
        
    }
    public void saveDeposition() {
       try{
           webdeposition.Deposition_Date__c = date.parse(depDate);
           update webdeposition;
           saveFiles();
           ApexPages.addMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Deposition information successfully saved.'));
       }catch(Exception ex) {
           ApexPages.addMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage()));
       }
   }
}