src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Attorney__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Attorney</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Confirm_Client__c</fullName>
        <label>Confirm - Client</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Deposition</fullName>
                    <default>true</default>
                    <label>Deposition</label>
                </value>
                <value>
                    <fullName>Examination Under Oath</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Statement Under Oath</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Video Playback</fullName>
                </value>
                <value>
                    <fullName>Client Meeting</fullName>
                </value>
                <value>
                    <fullName>Captioned Meeting</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Intra-co</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Email_Sent__c</fullName>
        <label>Last Email Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendConfirmationEmailCtlr.cls
public class SendConfirmationEmailCtlr {
    
    public list<DepositionModel>lstDepositionsModel{ get; set; }
    public Deposition__c dummydeposition{get;set;}
    public list<SelectOption>firmOptions{get;set;}
    public string selectedFirm{get;set;}
    public SendConfirmationEmailCtlr(){
         dummydeposition = new Deposition__c(Deposition_Date__c=System.today()+1);
         /*DateTime myDateTime = (DateTime) dummydeposition.Deposition_Date__c;
         String dayOfWeek = myDateTime.format('E');
         system.debug('$$$'+dayOfWeek );
         if(dayOfWeek =='Sun')
             dummydeposition.Deposition_Date__c = dummydeposition.Deposition_Date__c.addDays(1);
         else if(dayOfWeek =='Sat')
             dummydeposition.Deposition_Date__c = dummydeposition.Deposition_Date__c.addDays(2);    
         */
         lstDepositionsModel=new list<DepositionModel>();
         firmOptions = new List<SelectOption>();
         for(Firm__c firm : [select id,Name From Firm__c ]){
            firmOptions.add(new SelectOption(firm.Name,Firm.Name));
         }
         selectedFirm = Apexpages.currentPage().getParameters().get('firm');
         if(selectedFirm== NULL || selectedFirm.trim().length()==0)
             selectedFirm = 'NextGen Reporting';
    }
     
    public void actionmethod(){
        lstDepositionsModel=new list<DepositionModel>();
        
        system.debug('$$$'+dummydeposition.Deposition_Date__c);
        if(dummydeposition.Deposition_Date__c!=null){
             for(Deposition__c dep:[select name,Event_Type__c,Deposition_Status__c,Deposition_Time__c,Deposition_Date__c,Time_Zone__c,Event_Location__c
                 ,(select id,Name,Contact__c,Contact__r.Name,Contact__r.Email,Role__c,Deposition__r.Confirm_Reporter__c,
                 Deposition__r.Confirm_Client__c,Deposition__r.Confirm_Video_Tech__c,IsDeleted,Primary_Attorney__c 
                  From Deposition_Roles__r WHERE Role__c IN ('Scheduler','Court Reporter','Videographer/Technician') AND Contact__r.Email!= NULL)
                 from Deposition__c where Deposition_Date__c=:dummydeposition.Deposition_Date__c and Deposition_Status__c !='Confirmed'
                 and Deposition_Status__c !='Cancelled' AND Primary_Court_Reporting_Firm__r.Name=:selectedFirm]){
                 lstDepositionsModel.add(new DepositionModel(dep));
             }

        }
  }
  
  public PageReference cancel(){
      return new PageReference('/'+Deposition__c.sobjecttype.getDescribe().getKeyPrefix()+'/o');
  }

  public void sendEmail()
  {
       try{
           List<Messaging.SingleEmailMessage>lstEmails = new List<Messaging.SingleEmailMessage>();
            List<EmailTemplate>lstEmailTemplate = new List<EmailTemplate>();
            map<String,Id>mapEmailTemplates = new Map<String,Id>();
            String templateName = 'CR_Confirmation_Tomorrow_VF,Videographer_Confirmation_Tomorrow_VF,Confirmation_for_legal_staff_tomorrow_VF';
            for(EmailTemplate emailTempl : [select id,DeveloperName From EmailTemplate WHERE DeveloperName  IN : templateName.split(',')]){
                mapEmailTemplates.put(emailTempl.DeveloperName,emailTempl.id);
            }
            
            
            Savepoint sp = Database.setSavepoint();
            List<Deposition__c>lstNeedDepUpdate = new List<Deposition__c>();
            
            
            //List<OrgWideEmailAddress >lstOrgWideEmailAddress =  [select Id,Address from OrgWideEmailAddress WHERE
            //                                                    Address = :firmSchedulingEmailAddress];
            
            if(lstEmailTemplate.size()>0 || mapEmailTemplates.size()>0){
                for(DepositionModel depModel : lstDepositionsModel){
                    Boolean needDepUpdate = false;
                    for(Attendee__c attendee : depModel.dep.Deposition_Roles__r){
                        if((Test.isRunningTest() || attendee.isDeleted) && attendee.Contact__r.Email != NULL){
                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                            
                            mail.setWhatId(depModel.dep.id);  
                            mail.setSaveAsActivity(true);   
                            mail.setTargetObjectId(attendee.Contact__c); 
                            //if (lstOrgWideEmailAddress.size()>0) {
                            //    mail.setOrgWideEmailAddressId(lstOrgWideEmailAddress[0].Id);
                            //}       
                            if(attendee.Role__c == 'Scheduler' || attendee.Primary_Attorney__c ){
                                depModel.dep.Confirm_Client__c = 'Sent';
                                needDepUpdate = true;
                            }
                            if(attendee.Role__c == 'Court Reporter'){
                                depModel.dep.Confirm_Reporter__c= 'Sent'; 
                                needDepUpdate = true;
                            }
                            if(attendee.Role__c == 'Videographer/Technician'){
                                depModel.dep.Confirm_Video_Tech__c= 'Sent';   
                                needDepUpdate = true;
                            }  
                            
                           
                            if(attendee.Role__c == 'Scheduler' ||attendee.Primary_Attorney__c  ){
                                if(mapEmailTemplates.containsKey('Confirmation_for_legal_staff_tomorrow_VF'))
                                    mail.setTemplateId(mapEmailTemplates.get('Confirmation_for_legal_staff_tomorrow_VF'));
                            }else if(attendee.Role__c == 'Videographer/Technician' && mapEmailTemplates.containsKey('Videographer_Confirmation_Tomorrow_VF')){
                                mail.setTemplateId(mapEmailTemplates.get('Videographer_Confirmation_Tomorrow_VF'));
                            }else if(attendee.Role__c == 'Court Reporter' && mapEmailTemplates.containsKey('CR_Confirmation_Tomorrow_VF')){
                                mail.setTemplateId(mapEmailTemplates.get('CR_Confirmation_Tomorrow_VF'));
                            }
                              
                           lstEmails.add(mail);                
                        }
                        
                    }
                    
                    if(needDepUpdate){
                         depModel.dep.Last_Email_Sent__c=Date.Today();
                         lstNeedDepUpdate.add(depModel.dep);
                    
                    }
                }
                try{
                    if(lstEmails.size()>0){
                        Messaging.sendEmail(lstEmails);
                        if(lstNeedDepUpdate.size()>0)
                            update lstNeedDepUpdate;
                        
                    }
                    //actionmethod();
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Confirmation Email Sent Successfully'));
                    
                }catch(Exception e){
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
                    Database.rollback(sp);
                }
            }
       
       }catch(Exception e){
       
       }
       
   }
   public class DepositionModel{
         public Deposition__c dep{ get; set;}
         public List<Attendee__c>lstAttendees{ get; set;}
         public DepositionModel(Deposition__c dep){
             this.dep=dep;
             this.lstAttendees = dep.Deposition_Roles__r;
         }
    }
 
    

}