src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestNotifyDepositionChangesExtn.cls
@isTest
private class TestNotifyDepositionChangesExtn{
  
  @isTest
  private static void Test_NotifyDepositionChangesExtn (){
      TestUtils tUtils = new TestUtils();
      Deposition__c deposition = tUtils.createDeposition();
      Account account = tUtils.insertAccount();
      Contact contact = tUtils.insertContact(account.ID);
      
      NotifyDepositionChangesExtn  extn= new NotifyDepositionChangesExtn (new ApexPages.StandardController(deposition ));
      extn.sendEmailForClientConfirm();
      
      Attendee__c attendee = tUtils.insertAttendee(contact.Id, deposition.ID);
      attendee.Role__c='Scheduler';
      update attendee;
      
      ApexPages.currentPage().getParameters().put('Confirmed','true') ;
      extn= new NotifyDepositionChangesExtn (new ApexPages.StandardController(deposition ));
      extn.sendEmailForClientConfirm();
      extn.sendEmailForCancelled();
      
      
      attendee.Role__c='Court Reporter';
      update attendee;
      
      Test.startTest();
          extn= new NotifyDepositionChangesExtn (new ApexPages.StandardController(deposition ));
          extn.sendEmailForClientConfirm();
          extn.sendEmailForCancelled();
          
          attendee.Role__c='Videographer/Technician';
          update attendee;
          
          extn= new NotifyDepositionChangesExtn (new ApexPages.StandardController(deposition ));
          extn.sendEmailForClientConfirm();
          extn.sendEmailForCancelled();
          
          attendee.Role__c='Attorney';
          update attendee;
          
          extn= new NotifyDepositionChangesExtn (new ApexPages.StandardController(deposition ));
          extn.sendEmailForClientConfirm();
          extn.sendEmailForCancelled();
      
      Test.stopTest();
  }
}