src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled_Date__c</fullName>
        <label>Cancelled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpcomingDepositionsCntrl.cls
/**************************************************
                Name        : UpcomingDepositionsCntrl
                Author      : Rajendra Rathore
                Purpose     : That class is used by UpcomingDepositions VF component for showing upcomming depositions for community User
                Created Date: 16 April 2016
                
                Modification History:
*****************************************************/
public  class UpcomingDepositionsCntrl{
    public Transient  List<Deposition__c>lstDepositions {get;set;}
    public string selectedCaseNameChar{get;set;}
    string whereClause ='';
    User currentUser = New User();
    public Firm__c firm{get;set;}
    
    public UpcomingDepositionsCntrl(){
        List<String> alphabet = new List<String>
        {   'a','b','c','d','e','f','g','h','i','j','k','l','m',
            'n','o','p','q','r','s','t','u','v','w','x','y','z'
        };
        
        List<String> comparisons = new List<String>();
        for ( String letter : alphabet )
        {
            comparisons.add( '( NOT Hiring_Attorney__c  LIKE \'' + letter + '%\')' );
        }
        
        whereClause = String.join( comparisons, ' AND ' );
        selectedCaseNameChar = 'All';
        currentUser = [select id,ContactId From User Where Id=:Userinfo.getUserId()];
        //fetchDepositions();
        FirmInfoCntrl cntrl = new FirmInfoCntrl();
        firm = cntrl.getFirm();
    }
    
    public void fetchDepositions(){
    
    }
    public List<Deposition__c>getDepositions(){
        Date todayDate = System.today();
        
        String attendeeQuery = 'select Id,Deposition__c From Attendee__c WHERE (Deposition__r.Deposition_Date__c >=:todayDate OR Deposition__r.Deposition_Date__c =null)';
        
        String query =  'select id,Name,Deposition_Date__c,Case_Name__c,Hiring_Attorney__c';
        query+=',Deposition_Services__c,Deponent_Name__c,Cancelled_Date__c,Deposition_Status__c ';
        
        query+='  From Deposition__c WHERE (Deposition_Date__c >=:todayDate OR Deposition_Date__c =null)';
        query+= ' AND Deposition_Status__c !=\'Cancelled\'';
        if(selectedCaseNameChar != 'All' && selectedCaseNameChar != 'Other'){
            query+=' AND Deponent_Name__c like \''+ selectedCaseNameChar +'%\'';
            attendeeQuery += ' AND Deposition__r.Deponent_Name__c like \''+ selectedCaseNameChar +'%\'';
        }else if(selectedCaseNameChar == 'Other'){
            query+=' AND ' +whereClause  ;
        }
        if(currentUser.ContactId != NULL)
            attendeeQuery +=' AND Contact__c =\'' +currentUser.ContactId+'\'';
        else
            attendeeQuery +=' AND Deposition__r.OwnerId=\'' +currentUser.Id+'\'';
        system.debug('$$$'+selectedCaseNameChar );
        String caseId = Apexpages.currentPage().getParameters().get('caseId');
        if(caseId != '' &&caseId != NULL  && caseId.trim().length()>0)
            attendeeQuery +=' AND Deposition__r.Deposition_Group__c =\'' +caseId+'\'';
        Set<Id>setDepositionIds = new Set<Id>();
        for(Attendee__c attendee : Database.Query(attendeeQuery )){
            setDepositionIds.add(attendee.Deposition__c ) ;
        }
        List<Deposition__c>lstDepositions = new List<Deposition__c>();
        if(setDepositionIds.size()>0){
            query+=' AND ID IN:setDepositionIds' ;
            query+=' ORDER By Name,CreatedDate DESC LIMIT 800';
            lstDepositions= Database.Query(query);
        }else
            lstDepositions = new list<Deposition__c>(); 
        return lstDepositions ;
    }
}