src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCongaCustomLexitasIntegration.cls
@isTest
private class TestCongaCustomLexitasIntegration {

    @isTest
    private static void Test_CongaCustomLexitasIntegration() {

        TestUtils tUtils = new TestUtils();

        Account acc = tUtils.insertAccount();
        Contact con = tUtils.insertContact(acc.id);
        Deposition__c deposition = tUtils.insertDeposition(acc.id);
        Attendee__c attende = tUtils.insertAttendee(con.id, deposition.id);

        APXTConga4__Conga_Merge_Query__c conquery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'deposition', APXTConga4__Query__c = 'select id, Deposition__r.Name, Deposition__r.Deposition_Date__c, Deposition__r.Deponent_Name__c, Deposition__r.Case_Name__c,Contact__r.name from Attendee__c where id = {pv0}');
        insert conquery;

        APXTConga4__Conga_Template__c congaTem = new APXTConga4__Conga_Template__c(APXTConga4__Name__c = 'conga temp', APXTConga4__Template_Type__c = 'Document');
        insert congaTem;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        CongaCustomLexitasIntegration.congaSendMailBackgroundMode(deposition.id, con.id, congaTem.id, '', 'Test Subject', 'Test file', '', con.id, conquery.id, attende.id);
        Test.stopTest();
    }
}