src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestUpcomingDepositionsCntrl.cls
/**************************************************
                Name        : TestUpcomingDepositionsCntrl
                Author      : Rajendra Rathore
                Purpose     : Test class for UpcomingDepositionsCntrl Apex class
                Created Date: 12 JUNE  2016
                
                Modification History:
*****************************************************/
@isTest
public  class TestUpcomingDepositionsCntrl{
  @isTest
  private static void Test_UpcomingDepositionsCntrl(){
      
      Deposition__c dep = TestUtility.createDeposition(null);
      dep.Deposition_Date__c= Date.valueOf(System.now().addDays(5));
      insert dep;
      User usr  = TestUtility.createCommunityUser();
      system.runAs(usr  ){
          Attendee__c attendee = TestUtility.createAttendee(usr.ContactId,dep.id);
          insert attendee;
          
          UpcomingDepositionsCntrl  cntrl = new UpcomingDepositionsCntrl ();
          cntrl.selectedCaseNameChar = 'Other';
          cntrl.fetchDepositions();
          cntrl.selectedCaseNameChar = 'A';
          cntrl.fetchDepositions();
          cntrl.getDepositions();
      }
     
      
  }
}