src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name_Text__c</fullName>
        <label>Case Name Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/File_Access__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipName>S3_File_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ Attendee__r.Contact__c ,   Attendee__r.Contact__r.FirstName  +&apos; &apos;+ Attendee__r.Contact__r.LastName,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <label>File</label>
        <referenceTo>AWS_S3_Object__c</referenceTo>
        <relationshipLabel>File Access</relationshipLabel>
        <relationshipName>S3_File_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File Access</label>
    <nameField>
        <displayFormat>SFA-{00000000}</displayFormat>
        <label>S3 File Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommunitiesAddAttendeeToDepositionCntrl.cls
public class CommunitiesAddAttendeeToDepositionCntrl {
    public List<Deposition__c>lstDepositions{get;set;}
    public User usr{get;set;}
    public string depSearchText{get;set;}
    public CommunitiesAddAttendeeToDepositionCntrl(){
        usr = [select id,ContactId,Contact.AccountId,Contact.Email From User WHERE ID =:Userinfo.getUserId()];
        depSearchText = String.valueOf(ApexPages.currentPage().getParameters().get('searchText'));
    }
    public void searchDepositions(){
        lstDepositions = new List<Deposition__c>();
        
        /*List<List<SObject>> searchList = [FIND :depSearchText IN All Fields RETURNING Deposition__c];
        Deposition__c [] Depositions= ((List<Deposition__c>)searchList[0]);*/
        if(usr.Contact.AccountId != NULL){
        
            Set<Id>setCurrentUserDepositionIds = new Set<Id>();
            Set<Id>setDepositionIds = new Set<Id>();
            String searchText = '%'+depSearchText+'%';
            for(Attendee__c attendee : [select Deposition__c,Contact__c From Attendee__c 
                                      WHERE 
                                      (  Deposition__r.Case_Name_Text__c like:searchText  OR  Deposition__r.Deponent_Name__c like:searchText )
                                      AND Deposition__r.Deposition_Status__c !='Cancelled'
                                      AND Contact__r.AccountId=:usr.Contact.AccountId
                                      
                                      ]){
                setDepositionIds.add(attendee.Deposition__c);
                if(attendee.Contact__c == usr.ContactId)
                    setCurrentUserDepositionIds.add(attendee.Deposition__c);
            }
            if(setDepositionIds.size()>0)
                lstDepositions = [select Id,Case_Name__c,Deponent_Name__c,Deposition_Date__c,Hiring_Attorney__c
                                 ,IsDeleted
                                 From Deposition__c WHERE
                                  ID =:setDepositionIds AND
                                 ID NOT IN:setCurrentUserDepositionIds LIMIT 1000];
        }

    }
    
    public void addToMyAccount(){
        List<Attendee__c>lstAttendees=new List<Attendee__c>();
        set<Id>setSelectedDepIds = new Set<Id>();
        for(Deposition__c dep: lstDepositions ){
            if(dep.IsDeleted || Test.isRunningTest()){
                lstAttendees.add(new Attendee__c(Deposition__c=dep.id,Role__c='Attorney',Contact__c=usr.ContactId,Email__c=usr.Contact.Email));
                setSelectedDepIds.add(dep.id);
            }
        }
        if(lstAttendees.size()>0){
            Savepoint sp = Database.setSavepoint();
            try{
                insert lstAttendees;
                List<File_Access__c>lstNeedFileAccess = new List<File_Access__c>();
                Set<Id>setFileIds = new Set<Id>();
                Map<Id,Set<Id>>mapDepWithFileIds = new Map<Id,Set<Id>>();
                for(File_Access__c fileAccess: [select File__c,attendee__r.Deposition__c FROM File_Access__c WHERE Attendee__r.Deposition__c IN :
                                                setSelectedDepIds AND Attendee__r.Contact__r.AccountId=:usr.Contact.AccountId
                                                AND attendee__r.Contact__c !=:usr.ContactId]){
                    setFileIds = mapDepWithFileIds.get(fileAccess.attendee__r.Deposition__c);
                    if(setFileIds == NULL)
                        setFileIds = new Set<Id>();
                    setFileIds.add(fileAccess.File__c);
                    mapDepWithFileIds.put(fileAccess.attendee__r.Deposition__c,setFileIds);
                }
                if(setFileIds.size()>0){
                    for(Attendee__c attend : lstAttendees){
                        if(mapDepWithFileIds.containsKey(attend.Deposition__c)){
                            for(Id fileId : mapDepWithFileIds.get(attend.Deposition__c)){
                                lstNeedFileAccess.add(new File_Access__c (Attendee__c=attend.id,File__c=fileId ));
                            }
                        }
                    }
                    if(lstNeedFileAccess.size()>0)
                        insert lstNeedFileAccess;
                }
                searchDepositions();
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'These depositions have been added to your account.'));
           }catch(Exception e){
               ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Error: '+e.getMessage()));
               Database.rollback(sp);
           } 
        }else
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Error: Please select atleast one deposition!'));
    }
}