src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Attorney__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Attorney</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Firm</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Confirm_Client__c</fullName>
        <label>Confirm - Client</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type_Lowercase__c</fullName>
        <formula>CASE( Event_Type__c , &quot;Deposition&quot;, &quot;deposition&quot;, &quot;Arbitration&quot;, &quot;arbitration&quot;, &quot;Demo&quot;, &quot;demo&quot;, &quot;Other&quot; , &quot;event&quot; , &quot;Examination Under Oath&quot; , &quot;examination under oath&quot;, &quot;Statement Under Oath&quot; , &quot;statement under oath&quot;, &quot;Mediation&quot; , &quot;mediation&quot;, &quot;Trial&quot; , &quot;trial&quot;, &quot;Hearing&quot; , &quot;hearing&quot;, &quot;Video Playback&quot; , &quot;video playback&quot;, &quot;Auction&quot; , &quot;auction&quot;, &quot;event&quot;)</formula>
        <label>Event Type Lowercase</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GuestName__c</fullName>
        <label>Scheduler Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Firm__c</fullName>
        <label>Hiring Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Business_Day__c</fullName>
        <formula>CASE(
MOD( (TODAY())- DATE(1900, 1, 7), 7),
5, Deposition_Date__c-2 , /*if Fri */
6,Deposition_Date__c-1, /*if Sat*/
Deposition_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Business Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zoom_ID_URL__c</fullName>
        <formula>IF(ISBLANK(Zoom_ID_PIN_Code__c),&apos;&apos;,&quot;https://lexitas.zoom.us/j/&quot; &amp; Zoom_ID_PIN_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zoom ID URL</label>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <fields>
        <fullName>Community_Admin_Email__c</fullName>
        <label>Community Admin Email</label>
        <type>Email</type>
    </fields>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PortalExtn.cls
/**************************************************
                Name        : PortalExtn 
                Author      : Rajendra Rathore
                Purpose     : That class are used Portal VF page in Community for Scheduling for Deposition as well as show them 
                              following things:
                                  A.) Upcomming Depositions
                                  B.) Past Depositions
                Created Date: 18 May 2016
                
                Modification History:
*****************************************************/
public class PortalExtn {
   public Boolean isSuccess{get;set;}
   private Deposition__c webdeposition;
   public Attendee__c todayDeposition{get;set;}
   public Firm__c firm{get;set;}
   public list<CollaborationGroupMember>lstChatterGroups{get;set;}
   public List<SelectOption>lstCasesOptions{get;set;}
   public string selectedCaseId{get;set;}
   public List<Deposition__c>lstConfirmTomorrowDepositions{get;set;}
   public string selectedDepId{get;set;}
   public string depSearchText{get;set;}
   User usr;
   List<Contact>lstContacts ;
   
   
   //Constructor
   public PortalExtn (ApexPages.StandardController stdController) {
       webdeposition = (Deposition__c)stdController.getRecord();
       TimeZone tz = UserInfo.getTimeZone();
       if(tz.getDisplayName().startsWith('Eastern') || tz.getDisplayName().startsWith('Central')
        || tz.getDisplayName().startsWith('Mountain') || tz.getDisplayName().startsWith('Pacific') )
           webdeposition.Time_zone__c =  tz.getDisplayName().split(' ')[0];
       webdeposition.Deposition_Status__c = 'Scheduled';
       lstCasesOptions = new List<SelectOption>();
       lstConfirmTomorrowDepositions = new List<Deposition__c>();
       String firmName = '';
       Cookie firmCookie = ApexPages.currentPage().getCookies().get('firmCookie');
        
       firmName = 'NextGen Reporting';
       if(firmCookie != null)
           firmName = firmCookie.getValue(); 
       firm= DepositionHelper.fetchFirm(firmName );
       
       webdeposition.Primary_Court_Reporting_Firm__c = firm.id;
       isSuccess = false;  
       usr = [select id,ContactId,Contact.Name,Contact.Email,Contact.Phone,Contact.Account.Name,Contact.Account.Phone,Contact.Account.Owner.Email From User Where Id=:Userinfo.getUserId()];  
       todayDeposition = new Attendee__c();
       if(usr.ContactId != NULL){
           lstContacts = [select Id,Account.Industry From Contact WHERE Id=:usr.ContactId];
           List<Attendee__c>lstAttendess = [select id,Deposition__r.Zoom_ID_URL__c,Deposition__r.Event_Type_Lowercase__c,
                                       Deposition__r.Deposition_Time__c,Deposition__r.Time_zone__C ,
                                       Deposition__r.Deponent_Name__c,Deposition__r.Case_Name__c
                                       FROM Attendee__c WHERE Deposition__r.Deposition_Date__c=:System.today() AND 
                                       Deposition__r.Deposition_Services__c includes ('LegalView (Remote Video)')
                                       AND (Contact__c=:usr.ContactId OR Deposition__r.OwnerId=:Userinfo.getUserId())
                                       AND Deposition_Status__c !='Cancelled' ORDER BY CreatedDate DESC LIMIT 1];
          if(lstAttendess.size()>0)
              todayDeposition =lstAttendess[0];
          Set<Id>setCasesIds = new Set<Id>();
          String caseId = Apexpages.currentPage().getParameters().get('caseId');
          if(caseId == '' || caseId == NULL || caseId.trim().length()==0){
              for(Attendee__c attendee : [select id,Deposition__r.Deposition_Group__c From Attendee__c
                                         WHERE Deposition__r.Deposition_Group__c != NULL AND
                                         (Contact__c=:usr.ContactId OR Deposition__r.OwnerId=:Userinfo.getUserId())]){
                  setCasesIds.add(attendee.Deposition__r.Deposition_Group__c);
              }
              if(setCasesIds.size()>0){
                  lstCasesOptions.add(new SelectOption('','--None--'));
                  for(Case__c cse : [select Id,Name From Case__c WHERE ID IN:setCasesIds ORDER BY Name ]){
                      lstCasesOptions.add(new SelectOption(cse.id,cse.name));
                  }
              }
          }
          loadTomorrowDeepositions();
         
             
      }
     
      loadChatterGroup();
   }
   public void confirmDeposition(){
       try{
           Deposition__c dep = new Deposition__c(Id=selectedDepId);
           
           for(Attendee__c attendee : [select id,Role__c,Primary_Attorney__c From Attendee__c WHERE 
                                       Deposition__c=:dep.id AND 
                                       (Role__c='Videographer/Technician' OR Role__c='Court Reporter' OR Role__c='Scheduler' OR Primary_Attorney__c=true)  
                                       AND Contact__c = : usr.ContactId]){
               if(attendee.Role__c=='Scheduler' || attendee.Primary_Attorney__c)                        
                   dep.Confirm_Client__c = 'Confirmed';
               if(attendee.Role__c=='Court Reporter')                        
                   dep.Confirm_Reporter__c = 'Confirmed';
               if(attendee.Role__c=='Videographer/Technician')                        
                   dep.Confirm_Video_Tech__c = 'Confirmed';    
                   
           }
           update dep;
           loadTomorrowDeepositions();
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Deposition successfully confirmed.'));
       }catch(Exception e){
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,e.getMessage()));
       }
       
   }
   
   //If someone logs in the day before a deposition (either using Deposition.Next_Business_Day__c or Deposition Date - 1) 
   //please add a line to the top of the main page just like what you created when users have a LegalView deposition today.
   private void loadTomorrowDeepositions(){
      Date todayDate = system.today();
      Date tomorrowDate = System.today().addDays(1);
      String contactId= usr.ContactId;
      String userId = usr.Id;
      String qry = 'select id,Deposition__c FROM Attendee__c WHERE  Deposition__r.Deposition_Status__c != \'Cancelled\' AND ' 
                       +'(Contact__c=:contactId OR Deposition__r.OwnerId=:userId)'+
                       ' AND (Deposition__r.Next_Business_Day__c= :todayDate  OR'+
                       ' Deposition__r.Deposition_Date__c=:tomorrowDate )' +
                       'AND ( (Deposition__r.Confirm_Client__c !=\'Confirmed\' AND (Role__c=\'Scheduler\' OR Primary_Attorney__c=true))'+
                       'OR (Deposition__r.Confirm_Reporter__c !=\'Confirmed\' AND  Role__c=\'Court Reporter\' ) '+
                       'OR (Deposition__r.Confirm_Video_Tech__c !=\'Confirmed\' AND Role__c=\'Videographer/Technician\') )';
                       
                        
                       
      system.debug('###'+qry );
      
      set<Id>setDepositionIds = new Set<Id>();
      for(Attendee__c attendee : Database.Query(qry)){
          setDepositionIds.add(attendee.Deposition__c);
      }
      if(setDepositionIds.size()>0)
          lstConfirmTomorrowDepositions  = [select ID,Name,Event_Type_Lowercase__c,Deposition_Date__c,Deposition_Time__c,Time_Zone__c
                                       FROM Deposition__c WHERE ID IN :setDepositionIds];
      else
          lstConfirmTomorrowDepositions  = new List<Deposition__c >();
     
   }     
   public PageReference saveDeposition() {
       isSuccess= false;
       try {
           if(webdeposition.Deposition_Date__c == NULL){
               ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'To schedule a deposition, please enter a date. Or, to search for a deposition, please use the box at the top of the screen. Any questions? <A style="color:white;" HREF="mailto:'+ Firm.Community_Admin_Email__c+'">Send us an email</A>.'));
               return null;
           }
               
           webdeposition.Hiring_Firm__c = usr.Contact.Account.Name;
           webdeposition.GuestName__c= usr.Contact.Name;
           webdeposition.GuestEmail__c= usr.Contact.Email;
           webdeposition.GuestPhone__c= usr.Contact.Phone != NULL ? usr.Contact.Phone : usr.Contact.Account.Phone;
           upsert(webdeposition);
           addGuestAsScheduler();
           List<OrgWideEmailAddress >lstOrgWideEmails = [select Id,Address from OrgWideEmailAddress WHERE
                                Address =:Firm.Scheduling_email_address__c];
           List<EmailTemplate>lstEmailTemplate = [select Id From EmailTemplate WHERE DeveloperName='Deposition_Booking_Email_Notification'];
           if(lstEmailTemplate.size()>0){
                try{
                    List < Messaging.SingleEmailMessage > allMails = new List < Messaging.SingleEmailMessage > ();
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    if (lstOrgWideEmails.size()>0) {
                        mail.setOrgWideEmailAddressId(lstOrgWideEmails[0].Id);
                    }
                    List<String> ccAddresses = new List<String>();
                    if(Firm.Scheduling_email_address__c != NULL){
                        ccAddresses.add(Firm.Scheduling_email_address__c);
                    }
                   /* if(usr.Contact.Account.Owner.Email!= '' && usr.Contact.Account.Owner.Email!= NULL){
                        ccAddresses.add(usr.Contact.Account.Owner.Email);
                    } */
                    Deposition__c depowithComm = [select id, Commission__r.Primary_Rep__r.Email, Commission__r.Secondary_Rep__r.Email  from Deposition__c where id=:webdeposition.id];
                    If(depowithComm != null && String.isNotBlank(depowithComm.Commission__r.Primary_Rep__r.Email))
                    	ccAddresses.add(depowithComm.Commission__r.Primary_Rep__r.Email);
                    If(depowithComm != null &&  String.isNotBlank(depowithComm.Commission__r.Secondary_Rep__r.Email))
                    	ccAddresses.add(depowithComm.Commission__r.Secondary_Rep__r.Email);
                    mail.setTargetObjectId(usr.ContactId);
                    mail.setWhatId(webdeposition.id);
                    mail.setTemplateId(lstEmailTemplate[0].id);
                    if(ccAddresses.size()>0)
                        mail.setCCAddresses(ccAddresses);
                    allmails.add(mail);
                    Messaging.sendEmail(allMails);
               }catch(Exception e){
                   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
                   return null;
               }
           }
           String firmId = webdeposition.Primary_Court_Reporting_Firm__c ;
           
           webdeposition = new Deposition__c();
           webdeposition.Primary_Court_Reporting_Firm__c = firmId ;
           isSuccess = true;
       }
       catch(System.DMLException e) {
           ApexPages.addMessages(e);
           return null;
       }
       
      
       
       
       return null;
       
   }
   
   private void addGuestAsScheduler() {
      Attendee__c attendee = new Attendee__c(Deposition__c = webDeposition.Id);
      attendee.Role__c = 'Scheduler';
      if(usr.ContactId != null) {
         attendee.Contact__c = usr.ContactId;
         attendee.Email__c = usr.Contact.Email;
         insert attendee;
      }

   }
   
   private void loadChatterGroup(){
       lstChatterGroups = [SELECT CollaborationGroupId,CollaborationGroup.Name From CollaborationGroupMember
                            WHERE CollaborationGroup.CollaborationType='Private' AND MemberId=:UserInfo.getUserId()];
   }
   
   public PageReference searchDepositionsRecord(){
       return new PageReference('/apex/CommunitiesAddAttendeeToDeposition?searchText='+depSearchText);
   }
  
}