src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Location Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Client_Notes__c</fullName>
        <label>Client Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Confirm_Client__c</fullName>
        <label>Confirm - Client</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type_Lowercase__c</fullName>
        <formula>CASE( Event_Type__c , &quot;Deposition&quot;, &quot;deposition&quot;, &quot;Arbitration&quot;, &quot;arbitration&quot;, &quot;Demo&quot;, &quot;demo&quot;, &quot;Other&quot; , &quot;event&quot; , &quot;Examination Under Oath&quot; , &quot;examination under oath&quot;, &quot;Statement Under Oath&quot; , &quot;statement under oath&quot;, &quot;Mediation&quot; , &quot;mediation&quot;, &quot;Trial&quot; , &quot;trial&quot;, &quot;Hearing&quot; , &quot;hearing&quot;, &quot;Video Playback&quot; , &quot;video playback&quot;, &quot;Auction&quot; , &quot;auction&quot;, &quot;event&quot;)</formula>
        <label>Event Type Lowercase</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firm_Name__c</fullName>
        <formula>Primary_Court_Reporting_Firm__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Firm Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Firm__c</fullName>
        <label>Hiring Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Contact__c</fullName>
        <label>Location Contact</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConfirmDepositionController.cls
public without sharing class ConfirmDepositionController {
    public Boolean isSucess{get;set;}
    private Boolean hasMissingParameterMsgAdded = false;
    public Deposition__c deposition{get;set;}
    public ConfirmDepositionController (){
        isSucess = false;
        
        String depId = ApexPages.currentpage().getParameters().get('code');
        if(depId != NULL && depId != '')
            this.deposition = loadDeposition(depId );
        else
            this.deposition = new Deposition__c();
        String selectedFirm = deposition.Primary_Court_Reporting_Firm__r.Name;
        system.debug('$$$'+selectedFirm );
        
        Cookie Cookie= new Cookie('firmCookie', null,null,0,false);
        ApexPages.currentPage().setCookies(new Cookie[]{Cookie});
        Cookie= new Cookie('firmCookie', selectedFirm,null,-1,false);
        ApexPages.currentPage().setCookies(new Cookie[]{Cookie});
    }
    //======================================================================//
    //Load deposition
    //======================================================================//
    private Deposition__c loadDeposition(String depId ) {
        List<Deposition__c>lstDeps =  [SELECT Id,Firm_Name__c, Event_Type_Lowercase__c,Deposition_Date__c ,Deposition_Time__c ,Time_Zone__c,
                                       Event_Location__c, Deposition_Services__c,Client_Notes__c,Hiring_Attorney__c,Hiring_Firm__c,
                                       Primary_Court_Reporting_Firm__r.Name,Primary_Court_Reporting_Firm__r.Phone__c
            FROM Deposition__c WHERE Id = : depId Limit 1
        ];
        if(lstDeps.size()>0)
            return lstDeps [0];
            
        return new Deposition__c();
    }
    public PageReference updateDeposition(){
        String depostionId = '';
        String code ='';
        String type ='';
        Boolean isErr = false;
        if(!String.isBlank(ApexPages.currentPage().getParameters().get('code'))) {
            depostionId = ApexPages.currentPage().getParameters().get('code').trim();
        }else{
            if(!hasMissingParameterMsgAdded)
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal, Label.Msg_on_Missing_Parameter));
            hasMissingParameterMsgAdded = true;
            isErr = true;
        }
        
        /*if(!String.isBlank(ApexPages.currentPage().getParameters().get('code'))) {
            code = ApexPages.currentPage().getParameters().get('code').trim();
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,'Code parameter missing in url!!!'));
            isErr = true;
        }*/
        
        if(!String.isBlank(ApexPages.currentPage().getParameters().get('type'))) {
            type= ApexPages.currentPage().getParameters().get('type').trim();
            if(type != 'R'  && type !='C' && type != 'V' && hasMissingParameterMsgAdded == false){
               // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,'Invalid Type parameter value!!!'));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,Label.Msg_on_Missing_Parameter));
                hasMissingParameterMsgAdded = true;
                isErr = true;
            }
                
        }else{
            if(!hasMissingParameterMsgAdded)
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,Label.Msg_on_Missing_Parameter));
            hasMissingParameterMsgAdded = true;
            isErr = true;
        } 
        
        if(isErr)
            return null;
            
        
        if(deposition == null){
            deposition  = new Deposition__c();
            return null;
        }else{
            try{
                if(type == 'R' )
                    deposition.Confirm_Reporter__c = 'Confirmed';
                else if(type == 'C' )
                    deposition.Confirm_Client__c = 'Confirmed';
                else if(type == 'V' )
                    deposition.Confirm_Video_Tech__c= 'Confirmed';
                update deposition;
                isSucess = true;
                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'We have successfully confirmed Deposition.'));
            }Catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,e.getMessage()));
            }
        }
        return null;
    }
   
   
    
    public Deposition__c validateDespositionAndAttendees(String depositionID,String code){
      List<Deposition__c> lstDeposition = [SELECT Id,Event_Type_Lowercase__c,Deposition_Date__c,Deposition_Time__c,Time_Zone__c
                                           ,Hiring_Attorney__c,Hiring_Firm__c,Deposition_Services__c,
                                           Client_Notes__c,Event_Location__c,Deponent_Name__c,Case_Name__c,Location_contact__c 
                                           FROM Deposition__c WHERE Name =:depositionID AND Id=:code];
      if(lstDeposition.size() == 0 && hasMissingParameterMsgAdded == false) {
        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,'Deposition Number OR Code is invalid.Please check and retry'));
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,Label.Msg_on_Missing_Parameter));
          hasMissingParameterMsgAdded = true;
          return null;
      }
      
      /*List<Attendee__c> lstAttendee = [SELECT Id,Email__c FROM Attendee__c WHERE Deposition__c = :lstDeposition[0].Id
                                       AND Email__c = :email];
      if(lstAttendee.size() == 0) {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,'You are not authorized to confirm the deposition'));
        return null;
      } */
      return lstDeposition[0];                                
    }
    
  
}