src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Size_KB__c</fullName>
        <formula>IF(ROUND(File_Size__c/1024,0)&lt;1024,TEXT(ROUND(File_Size__c/1024,0) )&amp;&apos;k&apos;,TEXT(ROUND((File_Size__c/1024)/1024,0) )&amp;&apos; MB&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>File Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposition Notice</fullName>
                </value>
                <value>
                    <fullName>Exhibit</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Signature Page</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Turn-in Sheet</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/File_Access__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipName>S3_File_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ Attendee__r.Contact__c ,   Attendee__r.Contact__r.FirstName  +&apos; &apos;+ Attendee__r.Contact__r.LastName,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <label>File</label>
        <referenceTo>AWS_S3_Object__c</referenceTo>
        <relationshipLabel>File Access</relationshipLabel>
        <relationshipName>S3_File_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File Access</label>
    <nameField>
        <displayFormat>SFA-{00000000}</displayFormat>
        <label>S3 File Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GrantedFilesCntrl.cls
public class GrantedFilesCntrl {
    public string contactId{get;set;}
    public String depositionId{get;set;}
    public List<File_Access__c>getAccessFiles(){
        return [select Id,File__r.File_Type__c,File__r.File_Size_KB__c,File__r.File_Name__c,File__c,File__r.Deposition__r.Primary_Court_Reporting_Firm__r.Name
              From File_Access__c WHERE Attendee__r.Deposition__c=:depositionId
                AND Attendee__r.Contact__c=:contactId];
    }
}