src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <formula>BLANKVALUE(Deposition_Location__r.Location_Address__c,  Deposition__r.Event_Location__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Corporate_Client_Source__c</fullName>
        <label>Corporate Client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AIG</fullName>
                </value>
                <value>
                    <fullName>Allstate</fullName>
                </value>
                <value>
                    <fullName>Amica</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T (Troy)</fullName>
                </value>
                <value>
                    <fullName>BASF</fullName>
                </value>
                <value>
                    <fullName>Cardinal Health</fullName>
                </value>
                <value>
                    <fullName>CSAA Insurance</fullName>
                </value>
                <value>
                    <fullName>DuPont</fullName>
                </value>
                <value>
                    <fullName>Electric Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Erie Insurance</fullName>
                </value>
                <value>
                    <fullName>Farmers Insurance</fullName>
                </value>
                <value>
                    <fullName>Fireman’s Fund</fullName>
                </value>
                <value>
                    <fullName>Gateway Risk Services</fullName>
                </value>
                <value>
                    <fullName>GEICO</fullName>
                </value>
                <value>
                    <fullName>Global Indemnity</fullName>
                </value>
                <value>
                    <fullName>Horace Mann</fullName>
                </value>
                <value>
                    <fullName>HPE</fullName>
                </value>
                <value>
                    <fullName>Liberty Mutual</fullName>
                </value>
                <value>
                    <fullName>Markel</fullName>
                </value>
                <value>
                    <fullName>Mass Mutual</fullName>
                </value>
                <value>
                    <fullName>Medical Protective</fullName>
                </value>
                <value>
                    <fullName>Mercury Insurance</fullName>
                </value>
                <value>
                    <fullName>National Indemnity Company of the South</fullName>
                </value>
                <value>
                    <fullName>National Liability &amp; Fire Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>No Corporate Client</fullName>
                </value>
                <value>
                    <fullName>North American Risk Services</fullName>
                </value>
                <value>
                    <fullName>Old Republic Contractors</fullName>
                </value>
                <value>
                    <fullName>Pioneer</fullName>
                </value>
                <value>
                    <fullName>Preferred Mutual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Sheet__c.object
<CustomObject>
    <label>Rate Sheet</label>
    <nameField>
        <label>Rate Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Sheet_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Rate Sheet Items</relationshipLabel>
        <relationshipName>Rate_Sheet_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Rate Sheet Items</relationshipLabel>
        <relationshipName>Rate_Sheet_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate Sheet Item</label>
    <nameField>
        <displayFormat>RSI-{00000}</displayFormat>
        <label>Rate Sheet Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Sheet Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State_Rules__c.object
<CustomObject>
    <label>State Rule</label>
    <nameField>
        <label>State Rules</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCreateInvoice_Ctrl.cls
/**
                                    Name             : TestCreateInvoice_Ctrl
                                    Date             : 03 Dec 2015
                                    Descripition     : Test Class for CreateInvoice_Ctrl class.
*/                                   
@isTest
private class TestCreateInvoice_Ctrl{

    @isTest
    private static void Test_CreateInvoice() {
        Rate_Sheet__c rateSheet = TestUtility.createRateSheet('Allstate','Reporter');
        insert rateSheet;
        
        Case__c depositionGroup = TestUtility.createDepositionGroup('Test group');
        depositionGroup.Rate_Sheet__c =rateSheet.id; 
        insert depositionGroup;
        
        Account account = TestUtility.createAccount('Test Account','Court Reporting');
        account.Rate_Sheet__c = rateSheet.id;
        insert account;
        
        Contact contact = TestUtility.createContact(account.ID,'Test Contact', 'test@test.com');
        contact.Rate_Sheet__c = rateSheet.id;
        insert contact;
        
        Deposition__c deposition = TestUtility.createDeposition(account.id);
        deposition.Event_Location__c= 'His Prison Cell Folsom, CA 94123';
        deposition.Corporate_Client_Source__c = 'Allstate';
        deposition.Deposition_Group__c = depositionGroup.Id;
        insert deposition;

        
        Attendee__c  attendee = TestUtility.createAttendee(contact.Id, deposition.Id);
        insert attendee ;
        
        State_Rules__c  stateRules= TestUtility.createStateRules('California','Test CA Rule');
        insert stateRules;
        
        Item__c item = TestUtility.createItem('Test Item');
        insert item;
        
        Rate_Sheet_Item__c rateSheetItem = TestUtility.createRateSheetItem(rateSheet.id,item.id,200,'Default Copy');
        insert rateSheetItem;
        
        ApexPages.currentPage().getParameters().put('id', attendee.id);
        CreateInvoice_Ctrl cntrl = new CreateInvoice_Ctrl();
        cntrl.getRateSheets();
        cntrl.deSelectPicklistRateSheet();
        cntrl.deSelectLookupRateSheet();
        cntrl.PrepareInvoice();
        cntrl.selectedRateSheet = rateSheet.id;
        cntrl.PrepareInvoice();
        cntrl.Cancel();
        cntrl.selectedRateSheet = 'Other';
        cntrl.tempContact.Rate_Sheet__c = rateSheet.id;
        cntrl.deSelectPicklistRateSheet();
        cntrl.deSelectLookupRateSheet();
        
        Test.StartTest();
            cntrl = new CreateInvoice_Ctrl();
            account.Industry = 'Law Firm';
            update account;
            cntrl.getRateSheets();
            
            cntrl = new CreateInvoice_Ctrl();
            account.Industry = 'Videography';
            update account;
            cntrl.getRateSheets();
            cntrl.saveDeposition();
            cntrl.dep = new Deposition__c();
            cntrl.saveDeposition();
       Test.StopTest();
    }


}