src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <formula>IF(ISBlank(TEXT(Contact__r.VIP_Level__c)),Text(Contact__r.Account.VIP_Level__c),Text(Contact__r.VIP_Level__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIP Level</label>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountHelper.cls
public Class AccountHelper{
    public static void updateAccountAttendee(List<Account>lstAccounts,Map<Id,Account>oldmap){
        set<Id>setAccountIds = new Set<Id>();
        for(Account acc: lstAccounts){
            if(acc.VIP_Level__c != oldmap.get(acc.id).VIP_Level__c)
                setAccountIds.add(acc.id);
        }
        
        if(setAccountIds.size()>0){
            List<Attendee__c >lstAttendees = [select id From Attendee__c  WHERE Contact__r.AccountId IN: setAccountIds];
            update lstAttendees ;
        }
        
    }
}