src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <formula>Invoice_Amount__c - Paid_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>IF(Paid_Amount__c&gt;= Invoice_Amount__c,&apos;Paid&apos;,IF(Paid_Amount__c==0,&apos;Unpaid&apos;,IF(Paid_Amount__c&gt;0,&apos;Partial&apos;,&apos;&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Reporter</fullName>
                </value>
                <value>
                    <fullName>Transcription</fullName>
                </value>
                <value>
                    <fullName>Video/Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Payment</fullName>
                    <default>true</default>
                    <label>Payment</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Finance Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResourcePaymentCtlr_Test.cls
@isTest
private class ResourcePaymentCtlr_Test {

	@isTest private static void testPayment() {
        
        TestFactory tFact = new TestFactory();
        List<Invoice__c> invoices = tFact.invoices;
        List<Invoice_Item__c> invoiceItems = tFact.invoiceItems;
        System.debug([SELECT Id, Name, Deposition__c, Account__c, Contact__c, Contact__r.Name,Contact__r.Payment_Method__c, Contact__r.ADP_ID__c , Deposition__r.Name, Deposition__r.Deposition_Date__c, Invoice_Date__c, Due_Amount__c  , Deposition__r.Primary_Court_Reporting_Firm__r.Name, Attendee__c,Attendee__r.Role__c FROM Invoice__c  WHERE Type__c!='Client' AND Payment_Status__c !='Paid' AND Status__c='Valid' AND Deposition__c != NULL AND Deposition__r.Primary_Court_Reporting_Firm__c!=null  ORDER BY Invoice_Date__c ASC NULLS LAST LIMIT 10]);
        System.debug([SELECT Type__c,Payment_Status__c,Status__c  FROM Invoice__c  ORDER BY Invoice_Date__c ASC NULLS LAST LIMIT 10]);
        
        Test.startTest();
            ResourcePaymentCtlr control = new ResourcePaymentCtlr();
            System.debug(control.hasNext);
            control.next();
            System.debug(control.hasPrevious);
            control.previous();
            System.debug(control.pageNumber);
            control.last();
            System.debug(control.getTotalPages());
            control.first();
            control.sortExpression='Deposition__r.Name';
            control.doSort();
            Date dToday = System.today();
            control.startDate = dToday.month()+'/'+(dToday.day()-2)+'/'+dToday.year();
            control.endDate = dToday.month()+'/'+(dToday.day()+3)+'/'+dToday.year();
            control.onSearch();
            System.debug('===='+control.invoices.size());
        
        	control.invoices[0].isSelect = false;
            control.onPay();
        	control.invoices[0].isSelect = true;
            control.onPay();
        
        	System.debug(control.header);
        	control.onExport();
        Test.stopTest();
        System.assertEquals(1, [SELECT Count() FROM Payment__c]);
	}

}