src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate Client</fullName>
                </value>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Process Server</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Videographer/Technician</fullName>
                </value>
                <value>
                    <fullName>Paralegal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <formula>IF(ISBlank(TEXT(Contact__r.VIP_Level__c)),Text(Contact__r.Account.VIP_Level__c),Text(Contact__r.VIP_Level__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIP Level</label>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <label>VIP Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP 1</fullName>
                </value>
                <value>
                    <fullName>VIP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>After_Deposition_Date_With_CR_Email__c</fullName>
        <formula>IF(OR(ISBlank( Deposition_Date__c ),ISBlank( CR_Email_Address__c ) ),&apos;&apos;,TEXT(Deposition_Date__c +1)&amp;&apos;==Email==&apos;&amp;CR_Email_Address__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>After Deposition Date With CR Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assistant_Or_Boss_Email__c</fullName>
        <label>Assistant Or Boss Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CR_Email_Address__c</fullName>
        <label>CR Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case_Name_Text__c</fullName>
        <label>Case Name Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deposition_Date_With_CR_Email__c</fullName>
        <formula>IF(OR(ISBlank( Deposition_Date__c ),ISBlank(  CR_Email_Address__c ) ),&apos;&apos;,TEXT(Deposition_Date__c )&amp;&apos;==Email==&apos;&amp;CR_Email_Address__c)</formula>
        <label>Deposition Date With CR Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Different_Reporters_on_Adjacent_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Different Reporters on Adjacent Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Google_Drive_Folder_Id__c</fullName>
        <label>Google Drive Folder Id</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prior_Deposition_Date_With_CR_Email__c</fullName>
        <formula>IF(OR(ISBlank( Deposition_Date__c ),ISBlank( CR_Email_Address__c ) ),&apos;&apos;,TEXT(Deposition_Date__c -1)&amp;&apos;==Email==&apos;&amp;CR_Email_Address__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prior Deposition Date With CR Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Rule</label>
        <referenceTo>State_Rules__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <label>VIP Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP 1</fullName>
                </value>
                <value>
                    <fullName>VIP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Deposition_Group_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deposition Group</relationshipLabel>
        <relationshipName>Deposition_Group_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Deposition_Group_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deposition Group Contact</label>
    <nameField>
        <displayFormat>DGC-{00000000}</displayFormat>
        <label>Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposition Group Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <fields>
        <fullName>Community_Admin_Email__c</fullName>
        <label>Community Admin Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_Footer_HTML__c</fullName>
        <label>Email Footer HTML</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Header_HTML__c</fullName>
        <label>Email Header HTML</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Google_Drive_Folder_Name__c</fullName>
        <label>Google Drive Folder Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scheduling_Email_Address__c</fullName>
        <label>Scheduling Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Web_Page_Footer_HTML__c</fullName>
        <label>Web Page Footer HTML</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Web_Page_Header_HTML__c</fullName>
        <label>Web Page Header HTML</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DepositionHelper.cls
/**
*                                    Name             : DepositionHelper
*                                    Date             : 06/02/2015
*                                    Description      : Helper Class for Deposition__c object Triggers
*/
public class DepositionHelper{
    public static Boolean isDepositiononAdjacentDaysWithDifferentCrEmailCalled = false;
    
    
    public static void blockDelete(List<Deposition__c>lstDeps){
        String profileId=userinfo.getProfileId();   
        List<Profile>lstProfiles = [Select Id,Name from Profile where Id=:profileId];
        
            
        if(lstProfiles.size()>0 &&  lstProfiles[0].Name =='New Platform'){
            for (Deposition__c preventDelete: lstDeps)
    
            {
                  preventDelete.addError('You don\'t have permission for delete Deposition. Please contact System Administrator.');
            }
    
    
        }
    }
    
    /** Create a folder in Google Drive and popuplate Folder Id in Deposition record
     */
    @future(Callout=true) 
    public static void populateGoogleDriveFolderId(String depositionsJson){
        List<Deposition__c> lstDeposition = (List<Deposition__c>)JSON.deserialize(depositionsJson, List<Deposition__c>.class);
        set<String>setStateNames = new Set<String>();
        List<Deposition__c>lstDepositionNeedUpdate = new List<Deposition__c>();
        String accessToken = '';
        if(Test.isRunningTest())
            accessToken = 'Testing';    
        else 
            accessToken =GoogleDriveAuthenticationCntrl.getAccessToken();

        for(Deposition__c dep : lstDeposition){
            try{
                HttpRequest req = new HttpRequest();
                req.setMethod('POST');
                req.setEndpoint('https://www.googleapis.com/drive/v2/files');
                req.setHeader('Authorization', 'Bearer '+accessToken);
                req.setHeader('content-type', 'application/json');
                
                String messageBody = '{'+
                  '"title": "' +dep.Name+'",'+
                  '"parents": [],'+
                  '"mimeType": "application/vnd.google-apps.folder"'+
                '}';
                req.setBody(messageBody);
                req.setTimeout(60*1000);
                
                Http h = new Http();
                String resp;
                HttpResponse res = new HttpResponse();
                if(Test.isRunningTest()){
                    String json=        '{'+
                    ' "id": "",'+
                    '}';
                    res.SetBody(json);
                }else
                    res = h.send(req);
                resp = res.getBody();
                lstDepositionNeedUpdate.add(new Deposition__c(Id=dep.id,Google_Drive_Folder_Id__c=GogoleDriveFolderParser.parse(resp).id));
            }Catch(Exception e ){
                System.debug('Error in Google Drive Create Folder'+e.getMessage());
            }
        }
        
        if(lstDepositionNeedUpdate.size()>0){
            update lstDepositionNeedUpdate;                                              
        }
    }
    
    
    /** Whenever Deposition Created or Updated then populate State Rule lookup value account state field
     */
    public static void populateStateRule(List<Deposition__c> lstDeposition,map<Id,Deposition__c>oldMap,Boolean isUpdate){
        set<String>setStateNames = new Set<String>();
        List<Deposition__c>lstDepositionNeedUpdate = new List<Deposition__c>();
        for(Deposition__c dep : lstDeposition){
            if(dep.State__c != NULL && (isUpdate == false || dep.State__c != oldmap.get(dep.id).State__c )){
                setStateNames.add(dep.State__c); 
                lstDepositionNeedUpdate.add(dep);
            }
            
        }
        
        if(setStateNames.size()>0){
            Map<String,Id>mapStateNameWithStateRuleId = new Map<String,Id>();
            for(State_Rules__c rule : [select id,Name From State_Rules__c WHERE Name IN:setStateNames]){
                mapStateNameWithStateRuleId.put(rule.Name.toLowerCase(),rule.id);
            }
            for(Deposition__c dep : lstDepositionNeedUpdate){
                if(mapStateNameWithStateRuleId.containsKey(dep.State__c.toLowercase()))
                    dep.State_Rule__c = mapStateNameWithStateRuleId.get(dep.State__c.toLowercase());
                
            }                                            
        }
    }
    
    /** Whenever Deposition Created or Updated By Community User then copy their related Contact.Reports To>Email Field 
        IN Assistant_Or_Boss_Email__c field
     */
    public static void updateDepostionAdminORBossEmail(List<Deposition__c> lstDeposition,map<Id,Deposition__c>oldMap,Boolean isUpdate){
        set<Id>setOwnerIds = new Set<Id>();
        for(Deposition__c dep : lstDeposition){
            if(isUpdate == false || (dep.OwnerId!= oldmap.get(dep.id).OwnerId)){
                setOwnerIds.add(dep.OwnerId); 
            }
            
        }
        
        if(setOwnerIds.size()>0){
            Map<Id,User>mapOwner = new Map<Id,User>([select id,Assistant_Or_Boss_Email__c 
                                                          From User WHERE Id IN: setOwnerIds]);
            for(Deposition__c dep : lstDeposition){
                dep.Assistant_Or_Boss_Email__c = mapOwner.get(dep.Ownerid).Assistant_Or_Boss_Email__c ;
                
            }                                            
        }
    }
    public static void updateDepostionFirm(List<Deposition__c> lstDeposition, map<Id,Deposition__c>oldMap,Boolean isUpdate){
        List<Deposition__c >lstDepositonsNeedUpdate= new List<Deposition__c >();
        for(Deposition__c dep : lstDeposition){
           
            If(dep.Primary_Court_Reporting_Firm__c == NULL &&
               (isUpdate == false || dep.Primary_Court_Reporting_Firm__c != oldMap.get(dep.id).Primary_Court_Reporting_Firm__c  )){
                lstDepositonsNeedUpdate.add(dep);
            }
            
        }
        
        if(lstDepositonsNeedUpdate.size()>0){
            List<user>lstUser= [select id,Default_CR_Firm__c From User WHERE Id=:userinfo.getUserId() AND Default_CR_Firm__c  !=NULL];  
            String userFirmName= 'NextGen Reporting';
            if(lstUser.size()>0){
                userFirmName = lstUser[0].Default_CR_Firm__c;
            }       
            
            List<Firm__c>lstFirms = [select id From Firm__c WHERE Name=:userFirmName];
            if(lstFirms.size()>0){
                for(Deposition__c  dep : lstDepositonsNeedUpdate){
                    dep.Primary_Court_Reporting_Firm__c  = lstFirms[0].id;
                }
            }                               
        }
    }
    /** Whenever Deposition.Deposition_Group__c field changed Or new  Deposition in inserted then populate
        Deposition.VIP_Level__c = Case__C.VIP_Level__c 
     */
    public static void updateDepostionVIPLevel(List<Deposition__c> lstDeposition, map<Id,Deposition__c>oldMap,Boolean isUpdate){
        set<Id>setCaseIds = new Set<Id>();
        for(Deposition__c dep : lstDeposition){
            if(dep.Deposition_Group__c  != NULL ){
                If(isUpdate == false || (dep.Deposition_Group__c != oldmap.get(dep.id).Deposition_Group__c )){
                    setCaseIds.add(dep.Deposition_Group__c);
                }
            }
        }
        
        if(setCaseIds.size()>0){
            Map<Id,Case__c>mapCases = new Map<Id,Case__c>([select id,VIP_Level__c 
                                                          From Case__c WHERE Id in:setCaseIds ]);
            for(Deposition__c dep : lstDeposition){
                if(dep.Deposition_Group__c  != NULL && mapCases.containsKey(dep.Deposition_Group__c)){
                    dep.VIP_Level__c  = mapCases.get(dep.Deposition_Group__c).VIP_Level__c;
                }
            }                                            
        }
    }
    /** Whenever Deposition.Deposition_Group__c field changed Or new  Deposition in inserted then populate
        Deposition.VIP_Level__c = Case__C.VIP_Level__c 
     */
    public static void checkDepositiononAdjacentDaysWithDifferentCrEmail(map<Id,Deposition__c> mapDepositions, map<Id,Deposition__c>oldMap,Boolean isUpdate){
        if(DepositionHelper.isDepositiononAdjacentDaysWithDifferentCrEmailCalled == false){
            
            map<Id,Deposition__c >mapDepositionUpdated = new map<Id,Deposition__c >();
            for(Deposition__c dep : mapDepositions.values()){
                if(dep.Deposition_Date_With_CR_Email__c != NULL && dep.Deposition_Group__c != NULL ){
                    If(isUpdate == false || (oldmap.get(dep.id).Deposition_Group__c==NULL || dep.Deposition_Date__c!= oldmap.get(dep.id).Deposition_Date__c || dep.CR_Email_Address__c!= oldmap.get(dep.id).CR_Email_Address__c)){
                        mapDepositionUpdated.put(dep.id,dep);
                    }
                }
            }
            if(mapDepositionUpdated.size()>0){
                List<AggregateResult>lstAggregateResult = [select max(Deposition_Date__c) maxDate,min(Deposition_Date__c)minDate 
                                                          From Deposition__c WHERE Deposition_Date_With_CR_Email__c != ''
                                                           AND ID IN : mapDepositionUpdated.keyset()];
                                                          
                if(lstAggregateResult.size()>0){
                    Date maxDate ;
                    Date minDate;
                    for(AggregateResult result :lstAggregateResult){
                        maxDate = (Date)result.get('maxDate');
                        minDate= (Date)result.get('minDate');
                    }
                    if(maxDate  != NULL && minDate != NULL){
                        minDate = minDate.addDays(-1);
                        maxDate = maxDate.addDays(1);
                        map<String,List<Deposition__c>>mapDateWithDepoistions = new Map<String,List<Deposition__c>>();
                        for(Deposition__c dep : [select id,Deposition_Date_With_CR_Email__c,CR_Email_Address__c   From Deposition__c 
                                                WHERE Deposition_Date__c>=:minDate 
                                                AND Deposition_Date__c<=:maxDate AND Deposition_Group__c !=NULL
                                                AND ID NOT IN : mapDepositionUpdated.keyset() AND Deposition_Date_With_CR_Email__c  !=NULL]){
                            List<Deposition__c>lstDeps = mapDateWithDepoistions.get(dep.Deposition_Date_With_CR_Email__c.split('==Email==')[0]);
                            if(lstDeps == null )
                                lstDeps = new List<Deposition__c >();
                            lstDeps.add(dep );
                            mapDateWithDepoistions.put(dep.Deposition_Date_With_CR_Email__c.split('==Email==')[0],lstDeps);
                            
                        }
                        if(mapDateWithDepoistions.size()>0){
                            List<Deposition__c>lstDepositionNeedUpdate = new List<Deposition__c>(); 
                            Boolean isDepositionAdded= false;
                            for(Deposition__c dep : mapDepositionUpdated.values()){
                                 isDepositionAdded = false;
                                if(mapDateWithDepoistions.containsKey(dep.After_Deposition_Date_With_CR_Email__c.split('==Email==')[0])){
                                    for(Deposition__c  depRecord : mapDateWithDepoistions.get(dep.After_Deposition_Date_With_CR_Email__c.split('==Email==')[0])){
                                        if(dep.CR_Email_Address__c != depRecord.CR_Email_Address__c ){
                                            Deposition__c deposition = new Deposition__c(Id=dep.id,Different_Reporters_on_Adjacent_Days__c = true);
                                            lstDepositionNeedUpdate.add(deposition );  
                                            isDepositionAdded = true;
                                            break;  
                                        }
                                        
                                    }
                                }
                                if(isDepositionAdded == false && mapDateWithDepoistions.containsKey(dep.Prior_Deposition_Date_With_CR_Email__c.split('==Email==')[0])){
                                    for(Deposition__c  depRecord : mapDateWithDepoistions.get(dep.Prior_Deposition_Date_With_CR_Email__c.split('==Email==')[0])){
                                        if(dep.CR_Email_Address__c != depRecord.CR_Email_Address__c ){
                                            Deposition__c deposition = new Deposition__c(Id=dep.id,Different_Reporters_on_Adjacent_Days__c = true);
                                            lstDepositionNeedUpdate.add(deposition );  
                                            isDepositionAdded = true;
                                            break;  
                                        }
                                        
                                    }
                                }
                                 
                            }
                            if(lstDepositionNeedUpdate.size()>0){
                                DepositionHelper.isDepositiononAdjacentDaysWithDifferentCrEmailCalled = true;
                                update lstDepositionNeedUpdate;
                            }
                           
                        }
                    }
                }
            }
        }
    }
    
    public static Firm__c fetchFirm(String firmName){
        if(firmName == NULL || firmName=='' || firmName=='null')
            firmName  = 'NextGen Reporting';
        system.debug('$$'+firmName);
        List<Firm__c>lstFirms = [select id,Name,Web_Page_Footer_HTML__c,Web_Page_Header_HTML__c,Email_Footer_HTML__c,Email_Header_HTML__c,URL__c,
                                Scheduling_email_address__c,Community_Admin_Email__c,Google_Drive_Folder_Name__c From Firm__c WHERE Name like: firmName+'%'];
        if(lstFirms.size()>0)
            return lstFirms[0];
        else 
            return new Firm__c();
    }
    
    
     /** Case_Name_Text__C inherits the first 100 characters of the case name field(Long text area)
     */
    public static void updateCaseNameText(List<Deposition__c> lstDeposition){
        set<Id>setCaseIds = new Set<Id>();
        for(Deposition__c dep : lstDeposition){
            dep.Case_Name_Text__c = '';
            if(dep.Case_Name__c != NULL){
                if(dep.Case_Name__c.trim().length()>100)
                    dep.Case_Name_Text__c = dep.Case_Name__c.trim().left(100);
                else
                    dep.Case_Name_Text__c = dep.Case_Name__c.trim();
            }
        }  
    }
    public static void createDefaultAttendeeFromDepositionGroup(List<Deposition__c> lstDeposition, map<Id,Deposition__c>oldMap,Boolean isUpdate){
        set<Id>setDepGroupIds = new Set<Id>();
        for(Deposition__c dep : lstDeposition){
            if(dep.Deposition_Group__c != NULL && (isUpdate==false || oldmap.get(dep.id).Deposition_Group__c  != dep.Deposition_Group__c ))    
                setDepGroupIds.add(dep.Deposition_Group__c);
        }  
        if(setDepGroupIds.size()>0){
            List<Attendee__c>lstAttendees = new List<Attendee__c>();
            Map<Id,Case__c>mapDepositionGroups = new Map<Id,Case__c>([select id,(select id,Contact__c,Role__c FROM Deposition_Group_Contacts__r) FROM Case__c WHERE ID IN : setDepGroupIds]);
            for(Deposition__c dep : lstDeposition){
                if(dep.Deposition_Group__c != NULL && (isUpdate==false || oldmap.get(dep.id).Deposition_Group__c  != dep.Deposition_Group__c ) && mapDepositionGroups.get(dep.Deposition_Group__c).Deposition_Group_Contacts__r.size()>0){
                    Case__c cse= mapDepositionGroups.get(dep.Deposition_Group__c);
                    for(Deposition_Group_Contact__c depGroupContact: cse.Deposition_Group_Contacts__r){
                        lstAttendees.add(new Attendee__c(Deposition__c=dep.id,Contact__c=depGroupContact.Contact__c,Role__c=depGroupContact.Role__c));
                    }
                }
                    
            } 
            if(lstAttendees.size()>0)
                insert lstAttendees;
        }
    }
    
    /** Log Fields Updated changes in activity History for following fields:
            -          Billing Notes - Billing_Notes__c
            -          Post Event Notes - Post_event_Notes__c
            -          Case Name/Caption - Case_Name__c
            -          Pre-Event Notes - Notes__c
            -          Reporter Instructions - Reporter_Instructions__c
            -          Special Instructions - Special_Instructions__c
    **/
    public static void logFieldChanges(map<Id,Deposition__c> mapDepositions, map<Id,Deposition__c>oldMap){
        List<Task>lstTasks = new List<Task>();
        
        for(Deposition__c dep: mapDepositions.values()){
            String taskDescription = '';
            String taskSubject = 'Update to ';
            if(dep.Billing_Notes__c!= oldmap.get(dep.id).Billing_Notes__c){
                taskDescription +='The Billing Notes has been changed from \n'+ oldmap.get(dep.id).Billing_Notes__c+' to \n'+ dep.Billing_Notes__c+'.\n';
                taskSubject += 'Billing Notes, ';
            }
            if(dep.Post_event_Notes__c!= oldmap.get(dep.id).Post_event_Notes__c){
                taskDescription +='The Post Event Notes has been changed from \n'+ oldmap.get(dep.id).Post_event_Notes__c+' to \n'+ dep.Post_event_Notes__c+'.\n';
                taskSubject += 'Post Event Notes, ';
            }
            if(dep.Case_Name__c!= oldmap.get(dep.id).Case_Name__c){
                taskDescription +='The Case Name/Caption has been changed from \n'+ oldmap.get(dep.id).Case_Name__c+' to \n'+ dep.Case_Name__c+'.\n';
                taskSubject += 'Case Name/Caption, ';
            }
            if(dep.Notes__c!= oldmap.get(dep.id).Notes__c){
                taskDescription +='The Pre-Event Notes has been changed from \n'+ oldmap.get(dep.id).Notes__c+' to \n'+ dep.Notes__c+'.\n';
                taskSubject += 'Pre-Event Notes, ';
            }
            
            if(dep.Reporter_Instructions__c!= oldmap.get(dep.id).Reporter_Instructions__c){
                taskDescription +='The Reporter Instructions has been changed from \n'+ oldmap.get(dep.id).Reporter_Instructions__c+' to \n'+ dep.Reporter_Instructions__c+'.\n';
                taskSubject += 'Reporter Instructions, ';
            }
            if(dep.Special_Instructions_text__c!= oldmap.get(dep.id).Special_Instructions_text__c){
                taskDescription +='The Special Instructions has been changed from \n'+ oldmap.get(dep.id).Special_Instructions_text__c+' to \n'+ dep.Special_Instructions_text__c+'.\n';
                taskSubject += 'Special Instructions, ';
            }
            if(dep.Deposition_Services__c!= oldmap.get(dep.id).Deposition_Services__c){
                taskDescription +='The Deposition Services has been changed from \n'+ oldmap.get(dep.id).Deposition_Services__c+' to \n'+ dep.Deposition_Services__c+'.\n';
                taskSubject += 'Deposition Services, ';
            }
            
            if(taskDescription != ''){
                taskSubject = taskSubject.removeend(', ');
                Task tsk = new Task(Status='Completed',WhatId=dep.Id,ActivityDate=System.today(),Subject=taskSubject );
                tsk.Description = taskDescription;
                lstTasks.add(tsk);
            }
            
        }
        if(lstTasks.size()>0)
            insert lstTasks;       
       
    }
}