src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>COD_Warning__c</fullName>
        <formula>if( Contact__r.Account.COD_Warning__c = TRUE, IMAGE(&quot;http://upload.wikimedia.org/wikipedia/commons/1/19/Portrait_of_Cod.jpg&quot;,&quot;COD Warning&quot;, 260, 350),&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>COD Warning</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ends_Time__c</fullName>
        <label>Ends Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Errata_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Errata Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Errata_Notes__c</fullName>
        <label>Errata Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type_Lowercase__c</fullName>
        <formula>CASE( Event_Type__c , &quot;Deposition&quot;, &quot;deposition&quot;, &quot;Arbitration&quot;, &quot;arbitration&quot;, &quot;Demo&quot;, &quot;demo&quot;, &quot;Other&quot; , &quot;event&quot; , &quot;Examination Under Oath&quot; , &quot;examination under oath&quot;, &quot;Statement Under Oath&quot; , &quot;statement under oath&quot;, &quot;Mediation&quot; , &quot;mediation&quot;, &quot;Trial&quot; , &quot;trial&quot;, &quot;Hearing&quot; , &quot;hearing&quot;, &quot;Video Playback&quot; , &quot;video playback&quot;, &quot;Auction&quot; , &quot;auction&quot;, &quot;event&quot;)</formula>
        <label>Event Type Lowercase</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exhibit_Page_Count__c</fullName>
        <label>Exhibit Page Count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite Level (Business Days)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Same day turnaround</fullName>
                </value>
                <value>
                    <fullName>Next day turnaround</fullName>
                </value>
                <value>
                    <fullName>2 day turnaround</fullName>
                </value>
                <value>
                    <fullName>3 day turnaround</fullName>
                </value>
                <value>
                    <fullName>4 day turnaround</fullName>
                </value>
                <value>
                    <fullName>5 day turnaround</fullName>
                </value>
                <value>
                    <fullName>6 day turnaround</fullName>
                </value>
                <value>
                    <fullName>7 day turnaround</fullName>
                </value>
                <value>
                    <fullName>8 day turnaround</fullName>
                </value>
                <value>
                    <fullName>9 day turnaround</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Firm_Name__c</fullName>
        <formula>Primary_Court_Reporting_Firm__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Firm Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Deposition_Services__c</fullName>
        <label>Portal Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Starts_Time__c</fullName>
        <label>Starts Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>State_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Rule</label>
        <referenceTo>State_Rules__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stop_Time__c</fullName>
        <label>Stop Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transcript_page_count__c</fullName>
        <label>Transcript page count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <fields>
        <fullName>Community_Footer__c</fullName>
        <label>Community Footer</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Community_Header__c</fullName>
        <label>Community Header</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Scheduling_Email_Address__c</fullName>
        <label>Scheduling Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Web_Page_Footer_HTML__c</fullName>
        <label>Web Page Footer HTML</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Web_Page_Header_HTML__c</fullName>
        <label>Web Page Header HTML</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State_Rules__c.object
<CustomObject>
    <fields>
        <fullName>Read_and_Sign_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Read and Sign Required</label>
        <type>Checkbox</type>
    </fields>
    <label>State Rule</label>
    <nameField>
        <label>State Rules</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DepositionInvoiceCtrl.cls
public class DepositionInvoiceCtrl {
    
    public Boolean isValidEntry{get;set;}
    public Deposition__c depositionRec{get;set;}
    public Firm__c firm{get;set;}
    private User usr;
    private String deposId;
    private String invId;
    
    public class InvoiceData{
        public Invoice__c inv{get;set;}
        public List<Invoice_Item__c> invItems{get;set;}
        public InvoiceData(Invoice__c inv){
            this.inv = inv;
            invItems = new List<Invoice_Item__c>();
        }
    }
    public DepositionInvoiceCtrl(ApexPages.StandardController controller) {
        init();
    }
    
    private void init(){
        usr = [SELECT Id, ContactId, Contact.Account.COD_Warning__c, Contact.Email From User WHERE ID =:Userinfo.getUserId()];
        if(usr.ContactId==null){
            isValidEntry= false;
        }
        deposId = ApexPages.currentPage().getParameters().get('id');
        invId = ApexPages.currentPage().getParameters().get('invid');
        if(String.isEmpty(deposId) || String.isEmpty(invId)){
            return;
        }
        firm = DepositionHelper.fetchFirm( 'Lexitas' );
        depositionRec=getDeposition(deposId);
        if(depositionRec!=null && depositionRec.Primary_Court_Reporting_Firm__c!=null){
            firm = [SELECT Id, Name, Community_Header__c,Community_Footer__c, Web_Page_Footer_HTML__c , Web_Page_Header_HTML__c,
                    Scheduling_Email_Address__c, Phone__c
                    FROM Firm__c 
                    WHERE Id=: depositionRec.Primary_Court_Reporting_Firm__c  LIMIT 1];
            
            Cookie Cookie= new Cookie('firmCookie', null,null,0,false);
            ApexPages.currentPage().setCookies(new Cookie[]{Cookie});
            Cookie= new Cookie('firmCookie', firm.Name,null,-1,false);
            ApexPages.currentPage().setCookies(new Cookie[]{Cookie});
        }
        isValidEntry = true;
    }
    
    private Deposition__c getDeposition(Id did){
        List<Deposition__c> depositions=new List<Deposition__c>();
        depositions=[Select id, Name,Firm_Name__c, Expedite__c ,Deponent_Name__c,Deposition_Services__c, Deposition_Date__c ,
                    Event_Type_Lowercase__c,Primary_Court_Reporting_Firm__c,
                    Transcript_page_count__c, Exhibit_page_count__c, Errata_Notes__c, Errata_Needed__c,Portal_Deposition_Services__c,
                    State_Rule__c, State_Rule__r.Read_and_Sign_Required__c, Start_Time__c, Stop_Time__c, Starts_Time__c,Ends_Time__c
                    from Deposition__c where id=:did];
        if(depositions!=null && depositions.size()>0){
            return depositions[0];
        }else{
            return null;
        }
    }
    public List<Invoice__c> getInvoices(){
        if(usr.ContactId==null){
            return new List<Invoice__c> ();
        }
        String query = 'SELECT Id, Name, Deposition__c, Account__c, Payment_Status__c'
                    +', Contact__c, Contact__r.Name,Contact__r.Payment_Method__c, Contact__r.ADP_ID__c '
                    +', Deposition__r.Name, Deposition__r.Deposition_Date__c, Invoice_Date__c, Due_Amount__c  '
                    +', Deposition__r.Primary_Court_Reporting_Firm__r.Name'
                    +', Attendee__c,Attendee__r.Role__c'
                    +', (SELECT Id, Item__c, Item__r.Name, Invoice_Text__c, Quantity__c, Price__c, Units_of_Measure__c FROM Invoice_Items__r)'
                    +' FROM Invoice__c '
                    +' WHERE Deposition__c=: deposId AND Contact__c =\''+usr.ContactId +'\''
                    +' AND Id=:invId'
                    +' ORDER BY Invoice_Date__c desc';
        return Database.query(query);
    }
    public InvoiceData getInvoiceData(){
        if(usr.ContactId==null){
            isValidEntry = false;
            return null;
        }
        
        String query = 'SELECT Id, Name, Deposition__c, Account__c, Payment_Status__c'
                    +', Contact__c, Contact__r.Name,Contact__r.Payment_Method__c, Contact__r.ADP_ID__c '
                    +', Deposition__r.Name, Deposition__r.Deposition_Date__c, Invoice_Date__c, Due_Amount__c  '
                    +', Deposition__r.Primary_Court_Reporting_Firm__r.Name'
                    +', Attendee__c,Attendee__r.Role__c'
                    +', (SELECT Id, Item__c, Item__r.Name, Total_Price__c, Modification__c, Invoice_Text__c, Quantity__c, Price__c, Units_of_Measure__c FROM Invoice_Items__r)'
                    +' FROM Invoice__c '
                    +' WHERE Deposition__c=: deposId AND Contact__c =\''+usr.ContactId +'\''
                    +' AND Id=:invId'
                    +' ORDER BY Invoice_Date__c desc';
        List<Invoice__c> invs = Database.query(query);
        if(!invs.isEmpty()){
            InvoiceData inv = new InvoiceData(invs[0]);
            if(!invs[0].Invoice_Items__r.isEmpty()){
                inv.invItems = invs[0].Invoice_Items__r;
            }
            return inv;
        }
        isValidEntry = false;
        return null;
    }
}