src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OnSiteConfirmationControllerTest.cls
@isTest
private class OnSiteConfirmationControllerTest {
    
    private static testMethod void testOnSite() {
        
        TestFactory tFact = new TestFactory();

        List<Attendee__c> attendees = tFact.attendees;

        Test.startTest();
        ApexPages.currentPage().getParameters().put('depositionId',attendees[0].Deposition__c);
        ApexPages.currentPage().getParameters().put('contactId',attendees[0].Contact__c);
        OnSiteConfirmationController control = new OnSiteConfirmationController();
        control.manitainAttendee();
        Test.stopTest();
    }

}