src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Confirm_Interpreter__c</fullName>
        <label>Confirm - Interpreter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestConfirmEmailCtrl_Test.cls
@isTest
private class TestConfirmEmailCtrl_Test {

	@isTest private static void testConfrim() {
	    TestFactory tFact = new TestFactory();
        List<Deposition__c> depositions = tFact.depositions;
        List<Attendee__c> attendees = tFact.attendees;
        List<Contact> contacts = tFact.contacts;
        for(Contact con : contacts){
            con.Email = '';
        }
        update contacts;
        System.runAs(tFact.communtiyUser){
            TestConfirmEmailCtrl control = new TestConfirmEmailCtrl();
            control.onDepChange();
            
            control.inv.Deposition__c = depositions[0].Id;
            control.onDepChange();
            
            control.selectedAttendees = control.attendees[1].getValue();
            control.onSendConfirmationNotification();
        }
        Deposition__c dep = [SELECT Id, Confirm_Interpreter__c, Confirm_Reporter__c, Confirm_Video_Tech__c 
                            FROM Deposition__c WHERE Id=:depositions[0].Id LIMIT 1];
        // System.assert(dep.Confirm_Interpreter__c != depositions[0].Confirm_Interpreter__c 
        //     || dep.Confirm_Reporter__c != depositions[0].Confirm_Reporter__c
        //     || dep.Confirm_Video_Tech__c!=depositions[0].Confirm_Video_Tech__c);
	}
	@isTest private static void testRecap() {
	    TestFactory tFact = new TestFactory();
        List<Deposition__c> depositions = tFact.depositions;
        List<Attendee__c> attendees = tFact.attendees;
        List<Contact> contacts = tFact.contacts;
        for(Contact con : contacts){
            con.Email = '';
            con.Exempt_From_Automated_Confirmations__c = true;
        }
        update contacts;
        Test.startTest();
        System.runAs(tFact.communtiyUser){
            TestConfirmEmailCtrl control = new TestConfirmEmailCtrl();
            control.onDepChange();
            
            control.inv.Deposition__c = depositions[0].Id;
            control.onDepChange();
            
            control.selectedAttendees = control.attendees[1].getValue();
            control.onSendRecapNotification();
        }
        Test.stopTest();
        Deposition__c dep = [SELECT Id, Confirm_Interpreter__c, Confirm_Reporter__c, Confirm_Video_Tech__c 
                            FROM Deposition__c WHERE Id=:depositions[0].Id LIMIT 1];
        System.assert(dep.Confirm_Interpreter__c != depositions[0].Confirm_Interpreter__c 
            || dep.Confirm_Reporter__c != depositions[0].Confirm_Reporter__c
            || dep.Confirm_Video_Tech__c!=depositions[0].Confirm_Video_Tech__c);
	}

}