src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Realtime</fullName>
                </value>
                <value>
                    <fullName>Remote Deposition</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <formula>TEXT(Deposition__r.Deposition_Status__c)</formula>
        <label>Deposition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Deposition_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled_Date__c</fullName>
        <label>Cancelled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <formula>BLANKVALUE(Deposition__r.Deposition_Group__r.Name,  Deposition__r.Case_Name_Text__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <formula>Deposition__r.Hiring_Attorney__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hiring Attorney</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PastDepositionsCntrl.cls
/**************************************************
                Name        : PastDepositionsCntrl 
                Author      : Rajendra Rathore
                Purpose     : That class is used by PastDepositions VF component for showing past depositions for community User.
                Created Date: 16 April 2016
                
                Modification History:
*****************************************************/
public class PastDepositionsCntrl {
    public Transient  List<Deposition__c>lstDepositions {get;set;}
    public string selectedCaseNameChar{get;set;}
    string whereClause ='';
    public User currentUser{get;set;}
    public Firm__c firm{get;set;}
    public PastDepositionsCntrl(){
        List<String> alphabet = new List<String>
        {   'a','b','c','d','e','f','g','h','i','j','k','l','m',
            'n','o','p','q','r','s','t','u','v','w','x','y','z'
        };
        
        List<String> comparisons = new List<String>();
        for ( String letter : alphabet )
        {
            comparisons.add( '( NOT Deposition__r.Hiring_Attorney__c  LIKE \'' + letter + '%\')' );
        }
        
        whereClause = String.join( comparisons, ' AND ' );
        selectedCaseNameChar = 'All';
        currentUser = [select id,ContactId,Contact.AccountId,Contact.Account.Industry From User Where Id=:Userinfo.getUserId()];
        //fetchDepositions();
        FirmInfoCntrl cntrl = new FirmInfoCntrl();
        firm = cntrl.getFirm();
    }
    public void fetchDepositions(){
        //fetchDepositions();
    }
    /*public List<Deposition__c>getDepositions(){
        Date todayDate = System.today();
        
        String attendeeQuery = 'SELECT Id, Deposition__c From Attendee__c WHERE Deposition__r.Deposition_Date__c <:todayDate';
        String query =  'SELECT Id, Name, Deposition_Date__c, Case_Name__c, Hiring_Attorney__c';
        query+=', Deposition_Services__c, Deponent_Name__c, Cancelled_Date__c, Deposition_Status__c ';
        query+='  From Deposition__c WHERE Deposition_Date__c <:todayDate';
        if(selectedCaseNameChar != 'All' && selectedCaseNameChar != 'Other'){
            query+=' AND Deponent_Name__c like \''+ selectedCaseNameChar +'%\'';
            attendeeQuery += ' AND Deposition__r.Deponent_Name__c like \''+ selectedCaseNameChar +'%\'';
        }else if(selectedCaseNameChar == 'Other'){
            query+=' AND ' +whereClause  ;
        }
        if(currentUser.ContactId != NULL)
            attendeeQuery +=' AND Contact__c =\'' +currentUser.ContactId+'\'';
        else
            attendeeQuery +=' AND Deposition__r.OwnerId=\'' +currentUser.Id+'\'';
            
        String caseId = Apexpages.currentPage().getParameters().get('caseId');
        if(caseId != '' &&caseId != NULL  && caseId.trim().length()>0)
            attendeeQuery +=' AND Deposition__r.Deposition_Group__c =\'' +caseId+'\'';
        Set<Id>setDepositionIds = new Set<Id>();
        System.debug('>query'+query);
        System.debug('>query'+attendeeQuery);
        for(Attendee__c attendee : Database.Query(attendeeQuery )){
            setDepositionIds.add(attendee.Deposition__c ) ;
        }
        List<Deposition__c>lstDepositions = new List<Deposition__c>();
        if(setDepositionIds.size()>0){
            query+=' AND ID IN:setDepositionIds' ;
            query+=' ORDER By Deposition_Date__c DESC LIMIT 800';
            lstDepositions = Database.Query(query);
        }else
            lstDepositions = new list<Deposition__c>(); 
        getPastDepositions();
        return lstDepositions ;
    }*/
    
    public List<DepositionData> getPastDepositions(){
        Date todayDate = System.today();
        List<DepositionData> pasDep = new List<DepositionData>();
        String attendeeQuery ='';// 'SELECT Id, Deposition__c From Attendee__c WHERE Deposition__r.Deposition_Date__c <:todayDate';
        
        String query =  'SELECT Deposition__r.Id, Deposition__r.Name, Deposition__r.Deposition_Date__c, Deposition__r.Case_Name__c, Deposition__r.Hiring_Attorney__c';
        query+=', Deposition__r.Deposition_Services__c, Deposition__r.Deponent_Name__c, Deposition__r.Cancelled_Date__c, Deposition__r.Deposition_Status__c ';
        query+='  From Attendee__c WHERE Deposition__r.Deposition_Date__c <:todayDate';
        String invFilter ='';
        if(selectedCaseNameChar != 'All' && selectedCaseNameChar != 'Other'){
            query+=' AND Deposition__r.Deponent_Name__c like \''+ String.escapeSingleQuotes(selectedCaseNameChar) +'%\'';
            // attendeeQuery += ' AND Deposition__r.Deponent_Name__c like \''+ selectedCaseNameChar +'%\'';
        }else if(selectedCaseNameChar == 'Other'){
            query+=' AND ' +whereClause  ;
        }
        if(currentUser.ContactId != NULL){
            attendeeQuery +=' AND Contact__c =\'' +currentUser.ContactId+'\'';
            invFilter +=' AND Contact__c =\'' +currentUser.ContactId+'\'';
        }else{
            attendeeQuery +=' AND Deposition__r.OwnerId=\'' +currentUser.Id+'\'';
            invFilter +=' AND OwnerId=\'' +currentUser.Id+'\'';
        }
        String caseId = Apexpages.currentPage().getParameters().get('caseId');
        if(caseId != '' &&caseId != NULL  && caseId.trim().length()>0)
            attendeeQuery +=' AND Deposition__r.Deposition_Group__c =\'' +caseId+'\'';
        Set<Id>setDepositionIds = new Set<Id>();
        attendeeQuery = query + attendeeQuery;
        System.debug(attendeeQuery);
        Map<Id, DepositionData> sMap = new Map<Id, DepositionData>();
        for(List<Attendee__c> attendees : Database.Query(attendeeQuery )){
            for(Attendee__c attendee : attendees){
                if(!sMap.containsKey(attendee.Deposition__r.Id)){
                    DepositionData d = new DepositionData(attendee.Deposition__r);
                    sMap.put(attendee.Deposition__r.Id, d);
                }
            }
        }
        if(!sMap.isEmpty()){
            Set<Id> ids = sMap.keySet();
            String invQuery = 'SELECT Id,Name, Deposition__c FROM Invoice__c '
                            +' WHERE Deposition__c in :ids AND Status__c=\'Valid\''
                            + invFilter
                            +' ORDER BY CreatedDate';
            for(List<Invoice__c> invoices : Database.query(invQuery)){
                for(Invoice__c invoice : invoices){
                    if(sMap.containsKey(invoice.Deposition__c)){
                        DepositionData d = sMap.get(invoice.Deposition__c);
                        d.invoices.add(invoice);
                    }
                }
            }
        }
        return sMap.values();
    }
    public class DepositionData{
        public Deposition__c dep{get;set;}
        public List<Invoice__c> invoices{get;set;}
        public DepositionData(Deposition__c dep){
            this.dep = dep;
            invoices = new List<Invoice__c>();
        }
    }
}