src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Size_KB__c</fullName>
        <formula>IF(ROUND(File_Size__c/1024,0)&lt;1024,TEXT(ROUND(File_Size__c/1024,0) )&amp;&apos;k&apos;,TEXT(ROUND((File_Size__c/1024)/1024,0) )&amp;&apos; MB&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>File Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposition Notice</fullName>
                </value>
                <value>
                    <fullName>Exhibit</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Signature Page</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Turn-in Sheet</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Url__c</fullName>
        <formula>&apos;https://s3.amazonaws.com/&apos; &amp; Bucket_Name__c &amp;&apos;/&apos; &amp; Folder_Path__c &amp; File_Name_With_Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>File Url</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Address__c</fullName>
        <formula>Upload_Files__r.IP_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IP Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <formula>Note__c != NULL &amp;&amp; Note__c !=&apos;&apos;</formula>
        <label>Notes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Upload_Files__c</fullName>
        <label>Upload Batches</label>
        <referenceTo>Upload_Files__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Pre-event Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Upload_Files__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Upload_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Time_Of_Upload__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date/Time Of Upload</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Upload_Files1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IP_Address__c</fullName>
        <label>IP Address</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Upload Batches</label>
    <nameField>
        <displayFormat>UB-{0000000}</displayFormat>
        <label>Upload Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UploadFilesEmailsComponentCntrl.cls
public class UploadFilesEmailsComponentCntrl{
      public String uploadFilesId{get;set;}
      
      public Upload_Files__c getUploadFiles(){
        Upload_Files__c uploadFiles= new Upload_Files__c();
        if(uploadFilesId != null && uploadFilesId.trim().length()>0){
            List<Upload_Files__c>lstUploadFiles = [select id,Name,Email__c,Deposition__r.Name,Contact__r.Email,Date_Time_Of_Upload__c,Notes__c,IP_Address__c
            From Upload_Files__c WHERE Id=:uploadFilesId];
            if(lstUploadFiles.size()>0)
                uploadFiles = lstUploadFiles[0];
        }
        return uploadFiles;
      }
      
      public List<AWS_S3_Object__c>getAWSS3Objects(){
          return [select id,Name,File_Name__c,File_Size_KB__c,File_Url__c,File_Type__c From AWS_S3_Object__c WHERE Upload_Files__c =:uploadFilesId ];
      }
      
      public String getLogoDocumentid(){
          List<Document>lstDocuments = [select id From Document WHERE Name='Next Gen Logo'];
          if(lstDocuments.size()>0)
              return lstDocuments[0].id;
          else
              return '';
      }
      
      
}