src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>File_Id__c</fullName>
        <externalId>true</externalId>
        <label>File Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upload_Files__c</fullName>
        <label>Upload Batches</label>
        <referenceTo>Upload_Files__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Upload_Files__c.object
<CustomObject>
    <label>Upload Batches</label>
    <nameField>
        <displayFormat>UB-{0000000}</displayFormat>
        <label>Upload Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFilesTrigger.cls
/**************************************************
                Name        : TestFilesTrigger
                Author      : Rajendra Rathore
                Purpose     : Test class for FilesTrigger 
                Created Date: 21 FEB 2017
                
                Modification History:
*****************************************************/
@isTest
public  class TestFilesTrigger{
  @isTest
  private static void Test_S3FileModel(){
        Upload_Files__c upFiles = new Upload_Files__c();
        insert upFiles;
        
        AWS_S3_Object__c file= new AWS_S3_Object__c(Upload_Files__c= upFiles.id,File_Name__c='test.png',File_Id__c='TestId');
        insert file;
        file.File_Name__c='test1.png';
        update file;
        
        delete file;
  }
}