src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposition Notice</fullName>
                </value>
                <value>
                    <fullName>Exhibit</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Signature Page</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Turn-in Sheet</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCommunitiesDepositionDetailCntrl.cls
/**************************************************
                Name        : TestCommunitiesDepositionDetailCntrl
                Author      : Rajendra Rathore
                Purpose     : Test class for CommunitiesDepositionDetailCntrl Apex class
                Created Date: 11 JULY 2016
                
                Modification History:
*****************************************************/
@isTest
public  class TestCommunitiesDepositionDetailCntrl{
  @isTest
  private static void Test_CommunitiesDepositionDetailCntrl(){
      Deposition__c dep = TestUtility.createDeposition(null);
      insert dep;
      CommunitiesDepositionDetailCntrl cntrl = new CommunitiesDepositionDetailCntrl(new ApexPages.StandardController(dep));
      cntrl.init();
      cntrl.saveFiles();
     
      
      
      system.debug('$$'+CommunitiesDepositionDetailCntrl.createAwsS3Object('Test.jpg', 'test123', cntrl.uploadBatch.id,dep.id, 'test',
                                          100,1));
      CommunitiesDepositionDetailCntrl.createAwsS3Object('Test2.jpg', 'test1234', cntrl.uploadBatch.id,dep.id, 'test',
                                          100,1);
      CommunitiesDepositionDetailCntrl.createAwsS3Object('Test3.jpg', 'test1236', cntrl.uploadBatch.id,dep.id, 'test',
                                          100,1);                                    
      List<AWS_S3_Object__c>lstFiles = [select id From AWS_S3_Object__c  ];
      Integer i=0;
      for(AWS_S3_Object__c file : lstFiles){
          if(i==0)
              file.file_Type__c = 'Transcript';
          else if(i==1)
              file.file_Type__c = 'Exhibit';
          else 
              file.file_Type__c = 'Video';
          i++;
      }
      if(lstFiles.size()>0)
          update lstFiles;
      cntrl.fetchUserFiles();
      cntrl.loadFiles();
      cntrl.saveDeposition();
      cntrl.fetchUserFiles();
      
  }
}