src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deposition Notice</fullName>
                </value>
                <value>
                    <fullName>Exhibit</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Signature Page</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Turn-in Sheet</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_Files__c</fullName>
        <label>Upload Batches</label>
        <referenceTo>Upload_Files__c</referenceTo>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>File-{0000}</displayFormat>
        <label>File No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice_Item__c.object
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Upload_Files__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Upload_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipName>Upload_Files1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Upload Batches</label>
    <nameField>
        <displayFormat>UB-{0000000}</displayFormat>
        <label>Upload Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DepositionFilesCtrlTest.cls
@isTest
private class DepositionFilesCtrlTest {
    
    private static testMethod void testAccess() { 
        
        TestFactory tFact = new TestFactory();
        List<Invoice_Item__c> items = tFact.invoiceItems;
        List<Deposition__c> depositions = tFact.depositions;
        List<Contact> contacts = tFact.contacts;
        
        Upload_Files__c upFile = new Upload_Files__c (Contact__c=contacts[0].Id, Deposition__c  = depositions[0].Id);
        insert upFile;
        List<AWS_S3_Object__c> s3 = new List<AWS_S3_Object__c>();
        s3.add(new AWS_S3_Object__c(File_Type__c='Deposition Notice', Deposition__c= depositions[0].Id, 
                                    File_Name__c='test',Upload_Files__c=upFile.id ));
        insert s3;
        DepositionFilesCtrl control = new DepositionFilesCtrl();
        control.depositionId = depositions[0].Id;
        s3 = control.awsFiles;
        
        control.getFileAccess();
    }

}