src/objects/Blocked_Unicourt_Case__c.object
<CustomObject>
    <fields>
        <fullName>Unicourt_Case_Id__c</fullName>
        <label>Unicourt Case Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Blocked Unicourt Case</label>
    <nameField>
        <displayFormat>BUC-{0000}</displayFormat>
        <label>Blocked Unicourt Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blocked Unicourt Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Unicourt_Case_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unicourt Case ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MassDeleteSelectedCasesController.cls
public class MassDeleteSelectedCasesController {
	PageReference originalPage;
    List<case_leads__c> cases;
    public MassDeleteSelectedCasesController(ApexPages.StandardSetController setController){
        cases = setController.getSelected();
        system.debug('Casess:: '+cases);
        originalPage = setController.cancel();
        
    }
    
    public PageReference redirectBack(){
        
        system.debug('cases::: '+cases);
        List<Id> caseIds = new List<Id>();
        for(case_leads__c c : cases){
            caseIds.add(c.Id);
        }
        // add Unicourt case ids to metadata before deleting case.
        List<Blocked_Unicourt_Case__c> blockedCases = new List<Blocked_Unicourt_Case__c>();
        for(case_leads__c c : [select id,Unicourt_Case_ID__c from case_leads__c where id in :caseIds]){
            if(String.isNotBlank(c.Unicourt_Case_ID__c)){
                Blocked_Unicourt_Case__c buc = new Blocked_Unicourt_Case__c(Unicourt_Case_Id__c=c.Unicourt_Case_ID__c);
                blockedCases.add(buc);
            }
        }
        if(blockedCases.size() > 0)
            insert blockedCases;
        if(cases.size() > 0)
            delete cases;
        
        originalPage.setRedirect(true);
        return originalPage;
        /*
        Schema.DescribeSObjectResult result = Case_Leads__c.SObjectType.getDescribe();
        
        PageReference pg = new PageReference('/'+result.getKeyPrefix());
        pg.setRedirect(true);
        return pg; */
    }
}