src/objects/Blocked_Unicourt_Case__c.object
<CustomObject>
    <fields>
        <fullName>Unicourt_Case_Id__c</fullName>
        <label>Unicourt Case Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Blocked Unicourt Case</label>
    <nameField>
        <displayFormat>BUC-{0000}</displayFormat>
        <label>Blocked Unicourt Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blocked Unicourt Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Primary_Rep_Email__c</fullName>
        <label>Commission-Primary Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Commission_Secondary_Rep_Email__c</fullName>
        <label>Commission-Secondary Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Commission_Tertiary_Rep_Email__c</fullName>
        <label>Commission-Tertiary Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unicourt_Case_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unicourt Case ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>primary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>secondary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tertiary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseLeadTriggerHelper.cls
public class CaseLeadTriggerHelper {

    public static void onBeforeInsert(List<case_leads__c> newCaseLeads){
        
       
        Map<String, case_leads__c> UnicourtIdCaseLeadMap = new Map<String, case_leads__c>();
        
        for(case_leads__c cl : newCaseLeads){
            if(String.isNotBlank(cl.Unicourt_Case_ID__c)){
                UnicourtIdCaseLeadMap.put(cl.Unicourt_Case_ID__c, cl);
            }
        }
        // check if new unicourt case Ids are blocked
        system.debug('here validateUnicourtIds is called----');
        validateUnicourtIds(UnicourtIdCaseLeadMap);
        updateCommissionRepEmails(newCaseLeads,null);
    }
    
    public static void onBeforeUpdate(List<case_leads__c> newCaseLeads, Map<Id, case_leads__c> oldCaseLeadsMap){
        updateCommissionRepEmails(newCaseLeads,oldCaseLeadsMap);
    }
    
    /*
     * Method : validateUnicourtIds
     * @param1 : Map<String, case_leads__c>
     * purpose : Validate and add Error if Unicourt Case ID of the Case Lead is blocked.
     */
    private static void validateUnicourtIds(Map<String, case_leads__c> UnicourtIdCaseLeadMap){
        for(Blocked_Unicourt_Case__c blockedCase : [select id, Unicourt_Case_Id__c from Blocked_Unicourt_Case__c where Unicourt_Case_Id__c in :UnicourtIdCaseLeadMap.keyset()]){
			   if(UnicourtIdCaseLeadMap.keyset().contains(blockedCase.Unicourt_Case_Id__c))
                   UnicourtIdCaseLeadMap.get(blockedCase.Unicourt_Case_Id__c).addError('This Unicourt case is blocked.');
        }
    }
    
    private static void updateCommissionRepEmails(List<case_leads__c> newCaseLeads, Map<Id, case_leads__c> oldCaseLeadsMap){
        system.debug('updateCommissionRepEmails start--');
        List<id> commissionIds = new List<Id>();
        for(case_leads__c cl : newCaseLeads){
                system.debug('cl.Commission__c:::'+cl.Commission__c);
                if(cl.Commission__c != null){
                    commissionIds.add(cl.Commission__c);
                }else{
                    system.debug('commission null--');
                    cl.Commission_Primary_Rep_Email__c = null;
                    cl.Commission_Secondary_Rep_Email__c = null;
                    cl.Commission_Tertiary_Rep_Email__c = null;
                }
            
        }
        system.debug('commissionIds--'+commissionIds);
        Map<Id, Commission__c> commissionMap = new Map<Id, Commission__c>([select id, Primary_Rep__r.email, Secondary_Rep__r.email, Tertiary_Rep__r.email 
                                                                           from commission__c where id in :commissionIds]);
        for(case_leads__c cl : newCaseLeads){
            if(cl.Commission__c != null && commissionMap.keyset().contains(cl.Commission__c)){
                commission__c comm = commissionMap.get(cl.Commission__c);
                cl.Commission_Primary_Rep_Email__c = comm.Primary_Rep__r.email;
                cl.Commission_Secondary_Rep_Email__c = comm.Secondary_Rep__r.email;
                cl.Commission_Tertiary_Rep_Email__c = comm.Tertiary_Rep__r.email;
            }
        }
    }
    
    
    
    
}