src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <fields>
        <fullName>Billing_Notes__c</fullName>
        <label>Billing Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reporter_Instructions__c</fullName>
        <label>Reporter Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <label>VIP Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP 1</fullName>
                </value>
                <value>
                    <fullName>VIP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Notes__c</fullName>
        <label>Billing Notes</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CR_Email_Address__c</fullName>
        <label>CR Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Group</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Pre-event Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Post_event_Notes__c</fullName>
        <label>Post-event Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reporter_Instructions__c</fullName>
        <description>Instructions for the court reporter about a specific deposition.</description>
        <label>Reporter Instructions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Special_Instructions_text__c</fullName>
        <description>Detailed description of the special instructions used on this deposition.</description>
        <label>Special Instructions</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <label>VIP Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP 1</fullName>
                </value>
                <value>
                    <fullName>VIP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestDepositionTrigger.cls
/**
                    Name            :  TestDepositionTrigger
                    Date            :  26/07/2015
                    Descriptiion    : Test Class for  Deposition after insert, after update,before insert, beefore triggers
*/
@isTest
private class TestDepositionTrigger{
  
  @isTest
  private static void Test_DepositionBeforeTrigger(){
    insert TestUtils.createSignature();
    TestUtils tUtils = new TestUtils();
    Deposition__c deposition = tUtils.createDeposition();
    
    Account account = tUtils.insertAccount();
    Contact contact = tUtils.insertContact(account.ID);
    account.VIP_Level__c = 'VIP 1';
    update account;
    contact.VIP_Level__c = 'VIP 2';
    update contact;
    
    Case__c cse = new Case__c(Name='Test Case');
    insert cse;
    deposition.Deposition_Group__c  = cse.id;
    update deposition;
    
  }
  @isTest
  private static void Test_eDefaultAttendeeFromDepositionGroup(){
    TestUtils tUtils = new TestUtils();
    Account account = tUtils.insertAccount();
    Contact contact = tUtils.insertContact(account.ID);
    
    Case__c cse = new Case__c(Name='Test Case');
    insert cse;
    contact.Deposition_Group__c  = cse.id;
    update contact;
    Deposition__c deposition = TestUtility.createDeposition(null);
    deposition.Deposition_Group__c  = cse.id;
    insert deposition;
    
  }  
    
  @isTest
  private static void Test_DepositionAfterTrigger(){
    Case__c cse = new Case__c(Name='Test Case');
    insert cse;
    
    
    insert TestUtils.createSignature();
    TestUtils tUtils = new TestUtils();
    Account account = tUtils.insertAccount();
    Deposition__c deposition = TestUtils.insertDepositionWithDepostionGroup(account.id,cse.id,1);
    Deposition.CR_Email_Address__c= 'test@gmail.com';
    deposition.Deposition_Group__c  = cse.id;
    update deposition;
    
    DepositionHelper.isDepositiononAdjacentDaysWithDifferentCrEmailCalled  = false;
    Deposition__c  deposition2 = TestUtils.insertDepositionWithDepostionGroup(account.id,cse.id,3);
    deposition2.Deposition_Date__c = system.today().addDays(1);
    deposition2.Deposition_Group__c  = cse.id;
    DepositionHelper.isDepositiononAdjacentDaysWithDifferentCrEmailCalled  = false;
    update deposition2;
    
    delete deposition2;
    
  }
  @isTest
  private static void Test_logFieldChanges(){
    TestUtils tUtils = new TestUtils();
    Deposition__c deposition = tUtils.createDeposition();
    
    deposition.Billing_Notes__c       ='Test Billing Notes';
    deposition.Post_event_Notes__c    ='Test Post Event Notes';
    deposition.Case_Name__c           ='Test Case Name';
    deposition.Notes__c               ='Test  Notes';
    deposition.Reporter_Instructions__c='Test Reporter Instructions';
    deposition.Special_Instructions_text__c='Test Special Instructions';
    update deposition;
  }
}