src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status_Category__c</fullName>
        <label>Case Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Disposed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Judgment Entered</fullName>
                </value>
                <value>
                    <fullName>Other Pending</fullName>
                </value>
                <value>
                    <fullName>Other Disposed</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type_Category__c</fullName>
        <label>Case Type Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type_Subcategory__c</fullName>
        <label>Case Type Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small Claim</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Personal Injury</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other Small Claim</fullName>
                </value>
                <value>
                    <fullName>Chapter 7</fullName>
                </value>
                <value>
                    <fullName>Chapter 13</fullName>
                </value>
                <value>
                    <fullName>Other Product Liability</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Courthouse__c</fullName>
        <label>Courthouse</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Downey Courthouse</fullName>
                </value>
                <value>
                    <fullName>Chatsworth Courthouse</fullName>
                </value>
                <value>
                    <fullName>California Central Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Florida Middle Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Alhambra Courthouse</fullName>
                </value>
                <value>
                    <fullName>California Southern Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Michael Antonovich Antelope Valley Courthouse</fullName>
                </value>
                <value>
                    <fullName>Texas Eastern District</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Docket_Entry_Token__c</fullName>
        <label>Docket Entry Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filing_Date__c</fullName>
        <label>Filing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Los Angeles County Superior Courts</fullName>
                </value>
                <value>
                    <fullName>U.S. Bankruptcy Courts</fullName>
                </value>
                <value>
                    <fullName>U.S. District Courts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastSFDCUpdatedfromUnicourt__c</fullName>
        <description>This field shows when Case details in SFDC are updated from Unicourt</description>
        <label>Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Updated__c</fullName>
        <label>Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>PACER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unicourt_Case_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unicourt Case ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Update_Request_Status__c</fullName>
        <label>Update Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued for Update</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Had No Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Webhook_Log__c.object
<CustomObject>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Webhook Log</label>
    <nameField>
        <displayFormat>WH-{000000}</displayFormat>
        <label>Webhook Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webhook Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/updateCaseWebhookController.cls
public class updateCaseWebhookController {
    
    public void init(){
        //Map<String, CaseParser> mapCaseLeads = new Map<String,CaseParser >();
        try{
            String json = ApexPages.currentpage().getParameters().get('data');
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            UpdateAPIResParse parseObj	= UpdateAPIResParse.parse(json);
            if(parseObj.result.Status == 'has_update'){
                String caseUniCourtId = parseObj.result.case_id;
                HttpRequest req = new HttpRequest();
                req.setMethod('GET');
                req.setEndpoint('https://api.unicourt.com/rest/v1/case/'+caseUniCourtId +'/?token=2a8c48f7019a286dae3ddd7f43a96622a9ccc669');
                req.setTimeout(60*1000);
                
                Http h = new Http();
                String resp;
                HttpResponse res = h.send(req);
                resp = res.getBody();
                
                if(resp.indexOf('"case"') !=-1)
                    resp = resp.substring(0,resp.indexOf('"case"')) + '"caseObj"' + resp.substring(resp.indexOf(':{"case_meta"'),resp.length()) ;
                
                CaseParser casePraserRes =  CaseParser.parse(resp );
                Case_Leads__c caseLead;
                if(casePraserRes.error==false){
                    caseLead  = new Case_Leads__c ();
                    caseLead.Case_Name__c = casePraserRes.data.caseobj.case_meta.case_name;
                    caseLead.Case_Number__c = casePraserRes.data.caseobj.case_meta.case_number;
                    caseLead.Case_Status__c = casePraserRes.data.caseobj.case_meta.case_status;
                    caseLead.Case_Status_Category__c = casePraserRes.data.caseobj.case_meta.case_status_category;
                    caseLead.Case_Type__c = casePraserRes.data.caseobj.case_meta.case_type;
                    caseLead.Case_Type_Category__c = casePraserRes.data.caseobj.case_meta.case_type_category;
                    caseLead.Case_Type_Subcategory__c = casePraserRes.data.caseobj.case_meta.case_type_subcategory;
                    caseLead.County__c = casePraserRes.data.caseobj.case_meta.county;
                    caseLead.Courthouse__c = casePraserRes.data.caseobj.case_meta.courthouse;
                    caseLead.Filing_Date__c = Date.valueOf(casePraserRes.data.caseobj.case_meta.filing_date);
                    caseLead.Jurisdiction__c = casePraserRes.data.caseobj.case_meta.jurisdiction;
                    caseLead.Last_Updated__c = Date.valueOf(casePraserRes.data.caseobj.case_meta.last_updated_date);
                    caseLead.State__c = casePraserRes.data.caseobj.case_meta.state;
                    caseLead.Unicourt_Case_ID__c = casePraserRes.data.caseobj.case_meta.case_id;
                    caseLead.Docket_Entry_Token__c = casePraserRes.data.docket_entries_token;
                    caseLead.LastSFDCUpdatedfromUnicourt__c = system.today();
                    caseLead.Update_Request_Status__c = 'Updated';
                    
                    // mapCaseLeads.put(caseLead.Unicourt_Case_ID__c, caseLead);
                }
                
                if(caseLead !=null)
                    upsert caseLead Unicourt_Case_ID__c;
                if(!Test.isRunningTest() && caseLead != null && String.isNotBlank(caseLead.Unicourt_Case_ID__c)){
                    Map<String, String> caseIDTokenMap = new Map<String,String>();
                    caseIDTokenMap.put(caseLead.Unicourt_Case_ID__c, casePraserRes.data.docket_entries_token);
                    //CaseLeadCommonRoutine.createDocketEntries(caseIDTokenMap); // update the Docket Entries from Unicourt
                    LeadGenCaseBatch cntrl = new LeadGenCaseBatch(caseIDTokenMap.keyset());
                	Database.executeBatch(cntrl,100);
                }
            }
            
            if(parseObj.result.Status == 'has_no_update'){
                String caseUniCourtId = parseObj.result.case_id;
                Case_Leads__c clead  = new Case_Leads__c (Update_Request_Status__c = 'Had No Update', Unicourt_Case_ID__c = caseUniCourtId);
                upsert clead Unicourt_Case_ID__c;
            }
            
        }catch(Exception e){
            Webhook_Log__c log = new Webhook_Log__c ();
            log.Details__c = e.getMessage();
            insert log;
            
        }
        
    }
}