src/objects/Case_Follower__c.object
<CustomObject>
    <fields>
        <fullName>Case_Lead__c</fullName>
        <label>Case Lead</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Case Followers</relationshipLabel>
        <relationshipName>Case_Followers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Followed_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Follower</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Case Follower Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Followers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Conference__c</fullName>
        <label>Case Management Conference</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unicourt_Case_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unicourt Case ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseLeadsStartPageControllerTest.cls
@isTest
private class CaseLeadsStartPageControllerTest {

    @isTest
    private static void CaseLeadStartPageTest(){
        Case_Leads__c case1 = new Case_Leads__c( unicourt_case_id__c= 'HFKCQLBTIBKEMKEVPFAW7CTMNVRCC0998', Case_Name__c = 'testCase',Case_Management_Conference__c = System.Today()+1 );
        insert case1;
        Case_Follower__c cf = new Case_Follower__c(Case_Lead__c=case1.Id , User__c = Userinfo.getUserId());
        insert cf;
        String token = 'HFKCQLBTIBKEMKEVPFAW7CTMNVRCC'; // dummy case docket token
        Map<String, String> docketmap = new Map<String,String>();
        docketmap.put(case1.unicourt_case_id__c, token);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DocketActivityCalloutMock());
        CaseLeadCommonRoutine.createDocketEntries(docketmap);
        List<Case_Follower__c> cfList = [select id, Case_Lead__c from Case_Follower__c where User__c = :Userinfo.getUserId()];
        System.assert(cfList.size() > 0);
        CaseLeadsStartPageController CLS = new CaseLeadsStartPageController();
        cls.caseUpdateSince = Date.newInstance(2018, 07, 01);// Date before docket entry date i.e. 2018-07-06 (from mock response)
        cls.getCaseUpdates();
           
        System.assert(CLS.myCaseList.size() > 0);
        Test.stopTest();
    }
}