src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Commission profile is not active</errorMessage>
            <filterItems>
                <field>Commission__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Follower__c.object
<CustomObject>
    <fields>
        <fullName>Case_Lead__c</fullName>
        <label>Case Lead</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Case Followers</relationshipLabel>
        <relationshipName>Case_Followers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Followed_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Follower</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Case Follower Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Followers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>primary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>secondary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tertiary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Docket_Activity__c.object
<CustomObject>
    <description>Interesting updates to case leads</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Docket Activities</relationshipLabel>
        <relationshipName>Docket_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Docket_Entry_Date__c</fullName>
        <label>Docket Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Docket_Update__c</fullName>
        <label>Docket Update</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Docket Activity</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Docket Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Docket Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseLeadsStartPageController.cls
public class CaseLeadsStartPageController {
    public Map<Id, Docket_Activity__c> CaseIddocketActivitiesMap{get;set;}
    public Map<Id, Integer> CaseVs30DayHistory{get;set;}
    public List<case_leads__c> myCaseList{get;set;}
    public Date caseUpdateSince{get;set;}
    Id currentUserId;
    List<String> followedCaseList;
    public CaseLeadsStartPageController(){
        
        caseUpdateSince = System.today().addDays(-30);
        
        followedCaseList = new List<String>();
        currentUserId = UserInfo.getUserId();
        for(Case_Follower__c cf : [select id, Case_Lead__c from Case_Follower__c where User__c = :currentUserId] ){
            followedCaseList.add(cf.Case_Lead__c);
        }
        myCaseList = [select id, LastModifiedDate, Case_Name__c,commission__c 
                      from Case_Leads__c 
                      where id in :followedCaseList or Commission__r.Primary_Rep__c = :currentUserId OR Commission__r.Secondary_Rep__c = :currentUserId OR Commission__r.Tertiary_Rep__c = :currentUserId 
                      order by lastmodifieddate desc];
        getCaseUpdates();
        
    }
    
    public void getCaseUpdates(){
        CaseIddocketActivitiesMap = new Map<Id, Docket_Activity__c>();
        CaseVs30DayHistory = new Map<Id, Integer>();
        Integer caseCount = 0;
        system.debug('caseUpdateSince:::'+caseUpdateSince);
        for(Docket_Activity__c docket :  [select id, Docket_Entry_Date__c, Case__c,Docket_Update__c, LastModifiedDate
                                          from Docket_Activity__c 
                                          where Docket_Entry_Date__c >= :caseUpdateSince And (case__c in :followedCaseList or Case__r.Commission__r.Primary_Rep__c = :currentUserId OR Case__r.Commission__r.Secondary_Rep__c = :currentUserId OR Case__r.Commission__r.Tertiary_Rep__c = :currentUserId)  
                                          order by Docket_Entry_Date__c desc, Order__c desc]){
                                              if(!CaseIddocketActivitiesMap.containsKey(docket.Case__c) && caseCount < 25){
                                                  CaseIddocketActivitiesMap.put(docket.Case__c, docket);
                                                  caseCount++;
                                              }
                                              if(CaseIddocketActivitiesMap.containsKey(docket.Case__c)){
                                                  if(CaseVs30DayHistory.containsKey(docket.Case__c)){
                                                      Integer count = CaseVs30DayHistory.get(docket.Case__c)+1;
                                                      CaseVs30DayHistory.put(docket.Case__c, count);
                                                  }else{
                                                      CaseVs30DayHistory.put(docket.Case__c, 1);
                                                  }
                                              }
                                          }
    }
    
}