src/objects/Case_Follower__c.object
<CustomObject>
    <fields>
        <fullName>Case_Lead__c</fullName>
        <label>Case Lead</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Case Followers</relationshipLabel>
        <relationshipName>Case_Followers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Followed_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Follower</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Case Follower Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Followers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Conference__c</fullName>
        <label>Case Management Conference</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManageCaseFollowersTest.cls
@isTest
private class ManageCaseFollowersTest {
    
	@isTest
    private static void testAddFollowers(){
        Case_Leads__c case1 = new Case_Leads__c(Case_Name__c = 'testCase',Case_Management_Conference__c = System.Today()+1 );
        insert case1;
        Test.setMock(HttpCalloutMock.class, new TrackCasesCalloutMock());
        ManageCaseFollowers.addFollower(case1.id, UserInfo.getUserId());
    }
    
    @isTest(seeAllData=true)
    private static void testUpdateUnicourtCase(){
        Case_Leads__c case1 = [select id from Case_leads__c limit 1];
        
        Test.setMock(HttpCalloutMock.class, new TrackCasesCalloutMock());
        ManageCaseFollowers.updateUnicourtCase(case1.id);
    }
    @isTest
    private static void testRemoveCaseTracking(){
        Case_Leads__c case1 = new Case_Leads__c(Case_Name__c = 'testCase',Case_Management_Conference__c = System.Today()+1 );
        insert case1;
         Case_Follower__c cf = new Case_Follower__c(Case_Lead__c=case1.Id, User__c = Userinfo.getUserId());
        insert cf;
        Test.setMock(HttpCalloutMock.class, new TrackCasesCalloutMock());
        ManageCaseFollowers.removeCaseTracking(new List<string>{case1.id});
    }
}