src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Status__c</fullName>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Judgment Entered</fullName>
                </value>
                <value>
                    <fullName>Other Pending</fullName>
                </value>
                <value>
                    <fullName>Other Disposed</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other Small Claim</fullName>
                </value>
                <value>
                    <fullName>Chapter 7</fullName>
                </value>
                <value>
                    <fullName>Chapter 13</fullName>
                </value>
                <value>
                    <fullName>Other Product Liability</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discovery_Deadline__c</fullName>
        <label>Discovery Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filing_Date__c</fullName>
        <label>Filing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Followup_Date__c</fullName>
        <label>Followup Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>High_Profile_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>High Profile Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Representation__c.object
<CustomObject>
    <description>Which law firms represent which corporations?</description>
    <fields>
        <fullName>Case_Status__c</fullName>
        <formula>text(Case__r.Case_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Law_Firm_Text__c</fullName>
        <label>Law Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Representation (Law Firm)</relationshipLabel>
        <relationshipName>Representation_Law_Firms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unicourt_Client_Name__c</fullName>
        <label>Client Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Representation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Representation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Representation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HighProfileCasesController.cls
/*
 * Name         : HighProfileCasesController
 * Author       : Jitendra, 25 Jan 2019
 * Test Class   : HighProfileCasesControllerTest
 */
public class HighProfileCasesController {
     public List<Case_leads__c> HPCaseList{get;set;}
     List<Case_leads__c>  HPCaseMasterList;
    public String selectedCommission{get;set;}
    public Boolean isReadOnly{get;set;}
    public List<SelectOption> commissionList;
    transient public Map<Id, String> caseFirmsMap= new Map<Id, String>();
    transient public Map<Id, String> casePartiesMap= new Map<Id, String>();
    public Map<String,String> commIDNameMap;

    List<String> filterStatusList = new List<String>{'Other Disposed','Terminated'};
    public HighProfileCasesController(){
        HPCaseList = new List<Case_leads__c>();
        isReadOnly = true;
        system.debug('isReadonly --- '+isReadOnly);
        HPCaseMasterList = new List<Case_leads__c>();
      //  caseFirmsMap = new Map<Id, String>();
     //   casePartiesMap = new Map<Id, String>();
        commIDNameMap = new Map<String,String>();
        for(Case_leads__c cl : [select id,name, Case_Type__c,Discovery_Deadline__c, Filing_Date__c, Commission__c,Commission__r.Name, Followup_Date__c, Notes__c, (select id, Law_Firm__r.name, Law_Firm_Text__c, Client__r.name, Unicourt_Client_Name__c  from Representation__r)   from Case_Leads__c where High_Profile_Case__c = true and Case_Status__c not in :filterStatusList LIMIT 1000]){
            List<String> partiesName = new List<String>();
            List<String> firmsName = new List<String>();
            if(String.isNotBlank(cl.Commission__c))
                commIDNameMap.put(cl.Commission__c,cl.Commission__r.Name);
            for(Representation__c rep : cl.Representation__r){
                if(String.isNotBlank(rep.Law_Firm__r.name) && !firmsName.contains(rep.Law_Firm__r.name))
                    firmsName.add(rep.Law_Firm__r.name);
                if(String.isNotBlank(rep.Law_Firm_Text__c) && !firmsName.contains(rep.Law_Firm_Text__c))
                    firmsName.add(rep.Law_Firm_Text__c);
                if(String.isNotBlank(rep.Client__r.name) && !partiesName.contains(rep.Client__r.name) )
                    partiesName.add(rep.Client__r.name);
                if(String.isNotBlank(rep.Unicourt_Client_Name__c) && !partiesName.contains(rep.Unicourt_Client_Name__c))
                    partiesName.add(rep.Unicourt_Client_Name__c);
            }
            
            Case_leads__c cloneCaseLead = new Case_leads__c (id=cl.id, Name=cl.Name,Case_Type__c = cl.Case_Type__c);
            cloneCaseLead.Filing_Date__c = cl.Filing_Date__c;
            cloneCaseLead.Commission__c= cl.Commission__c;
            cloneCaseLead.Followup_Date__c= cl.Followup_Date__c;
            cloneCaseLead.Notes__c= cl.Notes__c;
            cloneCaseLead.Discovery_Deadline__c = cl.Discovery_Deadline__c;
            HPCaseMasterList.add(cloneCaseLead );
            
           // if(!firmsName.isEmpty())
                caseFirmsMap.put(cl.Id, String.join(firmsName, ','));
           // if(!partiesName.isEmpty())
                casePartiesMap.put(cl.Id, String.join(partiesName, ','));
            
        }
        HPCaseList = HPCaseMasterList;
    }
    
    public Map<Id,String> getCaseFirmsMap(){
       
       If(caseFirmsMap != null && caseFirmsMap.size() > 0){
            return caseFirmsMap;
       }
        caseFirmsMap = new Map<Id, String>();
        casePartiesMap = new Map<Id, String>();
        for(Case_leads__c cl : [select id,name, Case_Type__c, Filing_Date__c, Commission__c,Commission__r.Name, Followup_Date__c, Notes__c, (select id, Law_Firm__r.name, Law_Firm_Text__c, Client__r.name, Unicourt_Client_Name__c  from Representation__r)   from Case_Leads__c where High_Profile_Case__c = true and Case_Status__c not in :filterStatusList LIMIT 1000]){
            List<String> partiesName = new List<String>();
            List<String> firmsName = new List<String>();
           
            for(Representation__c rep : cl.Representation__r){
                if(String.isNotBlank(rep.Law_Firm__r.name) && !firmsName.contains(rep.Law_Firm__r.name))
                    firmsName.add(rep.Law_Firm__r.name);
                if(String.isNotBlank(rep.Law_Firm_Text__c) && !firmsName.contains(rep.Law_Firm_Text__c))
                    firmsName.add(rep.Law_Firm_Text__c);
                if(String.isNotBlank(rep.Client__r.name) && !partiesName.contains(rep.Client__r.name) )
                    partiesName.add(rep.Client__r.name);
                if(String.isNotBlank(rep.Unicourt_Client_Name__c) && !partiesName.contains(rep.Unicourt_Client_Name__c))
                    partiesName.add(rep.Unicourt_Client_Name__c);
            }
            
           // if(!firmsName.isEmpty())
                caseFirmsMap.put(cl.Id, String.join(firmsName, ','));
           // if(!partiesName.isEmpty())
                casePartiesMap.put(cl.Id, String.join(partiesName, ','));
        }
        return caseFirmsMap;
       
    }

    public Map<Id,String> getCasePartiesMap(){
        If(casePartiesMap != null && casePartiesMap.size() > 0){
            return casePartiesMap;
       }
        caseFirmsMap = new Map<Id, String>();
        casePartiesMap = new Map<Id, String>();
        for(Case_leads__c cl : [select id,name, Case_Type__c, Filing_Date__c, Commission__c,Commission__r.Name, Followup_Date__c, Notes__c, (select id, Law_Firm__r.name, Law_Firm_Text__c, Client__r.name, Unicourt_Client_Name__c  from Representation__r)   from Case_Leads__c where High_Profile_Case__c = true and Case_Status__c not in :filterStatusList LIMIT 1000]){
            List<String> partiesName = new List<String>();
            List<String> firmsName = new List<String>();
           
            for(Representation__c rep : cl.Representation__r){
                if(String.isNotBlank(rep.Law_Firm__r.name) && !firmsName.contains(rep.Law_Firm__r.name))
                    firmsName.add(rep.Law_Firm__r.name);
                if(String.isNotBlank(rep.Law_Firm_Text__c) && !firmsName.contains(rep.Law_Firm_Text__c))
                    firmsName.add(rep.Law_Firm_Text__c);
                if(String.isNotBlank(rep.Client__r.name) && !partiesName.contains(rep.Client__r.name) )
                    partiesName.add(rep.Client__r.name);
                if(String.isNotBlank(rep.Unicourt_Client_Name__c) && !partiesName.contains(rep.Unicourt_Client_Name__c))
                    partiesName.add(rep.Unicourt_Client_Name__c);
            }
            
           // if(!firmsName.isEmpty())
                caseFirmsMap.put(cl.Id, String.join(firmsName, ','));
           // if(!partiesName.isEmpty())
                casePartiesMap.put(cl.Id, String.join(partiesName, ','));
        }
        return casePartiesMap;
    }

    public List<SelectOption> getCommissionList(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','All'));
        for(String commId : commIDNameMap.keySet()){
            SelectOption option = new SelectOption(commId,commIDNameMap.get(commId));
            options.add(option);
        }
        
        return options;
    }
    public void save(){
        update HPCaseList;
    }
    
    public void filterListByCommission(){
        HPCaseList = new List<Case_leads__c>();
        if(String.isBlank(selectedCommission)){
            HPCaseList = HPCaseMasterList;
        }else{
            for(Case_leads__c cl : HPCaseMasterList ){
                system.debug(selectedCommission+' - '+cl.Commission__c);
                if(selectedCommission.equals(cl.Commission__c)){
                    HPCaseList.add(cl);
                }
            }
        }
    }

    public void toggleReadyOnlyMode(){
        system.debug('before toggle --- '+isReadOnly);
        if(isReadOnly){
            isReadOnly = false;
        }else{
            isReadOnly = true;
        }
        filterListByCommission();
        system.debug('after toggle --- '+isReadOnly);
    }
    
    
}