src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Commission profile is not active</errorMessage>
            <filterItems>
                <field>Commission__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Representation__c.object
<CustomObject>
    <description>Which law firms represent which corporations?</description>
    <fields>
        <fullName>Attorney__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Attorney</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Attorney_Email__c</fullName>
        <formula>BLANKVALUE( Attorney__r.Email ,  Unicourt_Email_Address__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Attorney Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Law_Firm_Text__c</fullName>
        <label>Law Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Representation (Law Firm)</relationshipLabel>
        <relationshipName>Representation_Law_Firms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unicourt_Attorney_First_Name__c</fullName>
        <label>Attorney First Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unicourt_Attorney_Last_Name__c</fullName>
        <label>Attorney Last Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unicourt_Client_Name__c</fullName>
        <label>Client Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Representation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Representation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Representation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewCaseAsgmtTemplateCtlr.cls
/*
* Class Name  :  NewCaseAsgmtTemplateCtlr
* Author      :  Jitendra Kumar	   
* Purpose	  :  To get the Representations, related to case lead in right order.
*/

global class NewCaseAsgmtTemplateCtlr {
    
    global string caseleadId;
    global List<representation__c> repList;
    global Map<String, List<Representation__c>> commission_repList_Map{get;set;}
    
    global Set<String> commissionList{get;set;}
   
    global void setcaseleadId(String caseid){
        if(String.isBlank(caseleadId) && String.isNotBlank(caseid)){
            caseleadId = caseid;
            system.debug('caseleadid::'+caseid);
            List<Representation__c> RepsWithNoCommission = new List<Representation__c>();
            commission_repList_Map = new Map<String, List<Representation__c>>();
            for(Representation__c rep : [select id, Client__c,Client__r.name, Unicourt_Client_Name__c, Commission__r.name, Law_Firm__c,Law_Firm__r.name,Law_Firm_Text__c, Attorney__r.name, Unicourt_Attorney_First_Name__c, Unicourt_Attorney_Last_Name__c, Full_Attorney_Email__c from Representation__c where Case__c = :caseid order by Client__r.name, Unicourt_Client_Name__c, Law_Firm__r.name,Law_Firm_Text__c, Attorney__r.name,Unicourt_Attorney_First_Name__c]){
                String commission = rep.Commission__r.name != null ? rep.Commission__r.name : 'No Commission';
                if(commission.equals('No Commission')){
                    RepsWithNoCommission.add(rep);
                }
                else if(commission_repList_Map.keyset().contains(commission)){
                    commission_repList_Map.get(commission).add(rep);
                }else{
                    commission_repList_Map.put(commission, new List<Representation__c>());
                    commission_repList_Map.get(commission).add(rep);
                }
            }
            commission_repList_Map.put('No Commission',RepsWithNoCommission);
            commissionList = commission_repList_Map.keySet();
            system.debug('rep size::'+commission_repList_Map.get('No Commission').size());
            system.debug('commissionList::'+commissionList);
        }
    }
    
    global string getcaseleadId(){
        return caseleadId;
    }
}