src/objects/Case_Follower__c.object
<CustomObject>
    <fields>
        <fullName>Case_Lead__c</fullName>
        <label>Case Lead</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Case Followers</relationshipLabel>
        <relationshipName>Case_Followers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Followed_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Follower</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Case Follower Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Followers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Conference__c</fullName>
        <label>Case Management Conference</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>primary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Depositions associated with a particular case lead</description>
        <label>Case Lead</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SalesRepCasesSummaryControllerTest.cls
@isTest
private class SalesRepCasesSummaryControllerTest {
	
    
    @isTest
    private static void testShowDetail(){
        Case_leads__c case1 = new Case_Leads__c(Case_Name__c = 'testCase',Case_Management_Conference__c = System.Today()+1 );
        insert case1;
        Case_Follower__c cf = new Case_Follower__c(Case_Lead__c=case1.Id, User__c = Userinfo.getUserId());
        insert cf;
        Commission__c comm = new Commission__c(name='testCommission', Primary_Rep__c=Userinfo.getUserId() );
        insert comm;
        Deposition__c dep = new Deposition__c(Commission__c = comm.id,Deposition_Date__c=System.Today()+1);
        insert dep;
        Test.startTest();
        SalesRepCasesSummaryController controller = new SalesRepCasesSummaryController();
        controller.rId = case1.Id;
        controller.showDetail();
        Test.stopTest();
    }
}