src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Conference__c</fullName>
        <label>Case Management Conference</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unicourt_Case_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unicourt Case ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MassDeleteSelectedCasesControllerTest.cls
@isTest
private class MassDeleteSelectedCasesControllerTest {
	
    @isTest
    private Static void TestMassDelete(){
        Case_Leads__c case1 = new Case_Leads__c( unicourt_case_id__c= 'HFKCQLBTIBKEMKEVPFAW7CTMNVRCC0998', Case_Name__c = 'testCase',Case_Management_Conference__c = System.Today()+1 );
        List<Case_leads__c> caselist = new List<Case_Leads__c>();
        caselist.add(case1);
        insert caselist;
        ApexPages.StandardSetController stdCont = new ApexPages.StandardSetController(caselist);
        stdCont.setSelected(caselist);
        MassDeleteSelectedCasesController massdelete = new MassDeleteSelectedCasesController(stdCont);
        Test.startTest();
        massdelete.redirectBack();
        List<Case_leads__c> csList = [select id from case_leads__c where id = :case1.Id];
        System.assertEquals(0, csList.size());
    }
}