src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Commission profile is not active</errorMessage>
            <filterItems>
                <field>Commission__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unicourt_Case_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unicourt Case ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this commission value active?</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Representation__c.object
<CustomObject>
    <description>Which law firms represent which corporations?</description>
    <fields>
        <fullName>Attorney__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Attorney</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <formula>Case__r.Case_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Law_Firm_Text__c</fullName>
        <label>Law Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unicourt_Client_Name__c</fullName>
        <label>Client Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Representation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Representation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Representation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewCaseAsgmtTemplateCtlrTest.cls
@isTest
private class NewCaseAsgmtTemplateCtlrTest {
	@isTest
    private static void prepareRepListTest(){
        Account account = TestUtility.createAccount('Hendel & Collins, P.C.','Court Reporting');
        insert account;
        Contact contact = TestUtility.createContact(account.ID,'Philip L. Bednar', 'test@test.com');
        insert contact;
        Case_Leads__c case1 = new Case_Leads__c(Case_Name__c = 'testCase',Unicourt_Case_ID__c  ='EI6RCFI4E46S6EL6MIVFQ63AKVDAY1011');
        insert case1;
        Commission__c comm = new Commission__c(Name='TestCommission', Active__c=true);
        insert comm;
        Representation__c rep = new Representation__c(Case__c = case1.Id, Unicourt_Client_Name__c='Test Client', Law_Firm_Text__c='Test LAw Firm', attorney__c = contact.id);
        
        Representation__c rep1 = new Representation__c(Case__c = case1.Id, Unicourt_Client_Name__c='Test Client1', Law_Firm_Text__c='Test LAw Firm1', attorney__c = contact.id, Commission__c = comm.id);
        List<Representation__c> repList = new List<Representation__c>{rep, rep1};
        insert repList;
        
        NewCaseAsgmtTemplateCtlr con = new NewCaseAsgmtTemplateCtlr();
        con.setcaseleadId(case1.id);
    }
}