src/objects/Case_Follower__c.object
<CustomObject>
    <fields>
        <fullName>Case_Lead__c</fullName>
        <label>Case Lead</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Case Followers</relationshipLabel>
        <relationshipName>Case_Followers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Followed_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Follower</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Case Follower Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Followers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Conference__c</fullName>
        <label>Case Management Conference</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>primary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>secondary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tertiary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Depositions associated with a particular case lead</description>
        <label>Case Lead</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SalesRepCasesSummaryController.cls
public class SalesRepCasesSummaryController {
    Public List<Deposition__c> clientList{get;set;}
    Public List<Case_Leads__c> prospectList{get;set;}
    Public List<Case_Follower__c> followedCaseList{get;set;}
    Public String rId{get;set;}
    String currentUserId;
    
    public SalesRepCasesSummaryController(){
        currentUserId = Userinfo.getUserId();
        clientList = [select id,Name, Case_Lead__r.Case_Name__c, Deposition_Date__c, Deposition_Status__c from Deposition__c 
                      where Deposition_Date__c > TODAY and 
                      (Commission__r.Primary_Rep__c = :currentUserId or Commission__r.Secondary_Rep__c = :currentUserId or Commission__r.Tertiary_Rep__c = :currentUserId ) order by Deposition_Date__c asc];
        prospectList = [select id,Name, Case_Management_Conference__c, Case_Name__c from Case_Leads__c where Case_Management_Conference__c > TODAY and ownerId = :currentUserId order by Case_Management_Conference__c asc];
        followedCaseList = [select id, Case_Lead__c,Case_Lead__r.Case_Name__c  from Case_Follower__c where User__c = :currentUserId];
    }
    
    public PageReference showDetail() {
        String baseURL = System.Url.getSalesforceBaseUrl().toExternalForm();
        pagereference ref = new pagereference(baseURL+'/'+rId);
                                              ref.setredirect(true);
                                              return ref;
                                              }
                                              
                                              }