src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>High_Profile_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>High Profile Case</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Representation__c.object
<CustomObject>
    <description>Which law firms represent which corporations?</description>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Representation</relationshipLabel>
        <relationshipName>Representation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Law_Firm_Text__c</fullName>
        <label>Law Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unicourt_Client_Name__c</fullName>
        <label>Client Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Representation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Representation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Representation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HighProfileCasesControllerTest.cls
@isTest
private class HighProfileCasesControllerTest {

    @isTest
    private static void TestHighProfileCase(){
        Commission__c comm = TestUtility.createCommission();
        insert comm;
        Case_leads__c cl = TestUtility.createCaseLead();
        cl.High_Profile_Case__c = true;
        cl.Commission__c = comm.id;
        insert cl;
        Representation__c rep = TestUtility.createRepresentation(cl.id);
        rep.Commission__c = comm.Id;
        rep.Law_Firm_Text__c = 'TestLawFirm';
        rep.Unicourt_Client_Name__c = 'WalmartTest';
        insert rep;
        Test.startTest();
        HighProfileCasesController controller = new HighProfileCasesController();
        System.assertEquals(1, controller.HPCaseList.size());
        controller.getCommissionList();
        controller.filterListByCommission();
        controller.selectedCommission = cl.Commission__c;
        controller.casePartiesMap = null;
        controller.getCasePartiesMap();
        controller.caseFirmsMap = null;
        controller.getCaseFirmsMap();
        controller.filterListByCommission();
        System.assertEquals(1, controller.HPCaseList.size());

        Test.stopTest();
    }
}