src/objects/Case__c.object
<CustomObject>
    <description>A way of grouping depositions in a specific legal matter.</description>
    <label>Case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Docket_Activity__c.object
<CustomObject>
    <description>Interesting updates to case leads</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Docket Activities</relationshipLabel>
        <relationshipName>Docket_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Docket_Entry_Date__c</fullName>
        <label>Docket Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Docket_Update__c</fullName>
        <label>Docket Update</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Docket Activity</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Docket Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Docket Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DocketActivitiesInlineExtension.cls
public class DocketActivitiesInlineExtension {

    public List<Docket_Activity__c> docketActivities{get;set;}  
    public Id caseId{get;set;}
    public DocketActivitiesInlineExtension(ApexPages.StandardController ctrlr){
        caseId = ctrlr.getId();
        docketActivities = [select id,name,Docket_Entry_Date__c, Case__c,Docket_Update__c, LastModifiedDate
                                          from Docket_Activity__c where case__c = :caseId];
    }

}