src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Conference__c</fullName>
        <label>Case Management Conference</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unicourt_Case_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unicourt Case ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GroupSelectedCasesControllerTest.cls
@isTest
private class GroupSelectedCasesControllerTest {
 
    @isTest
    private Static void TestGroupSelected(){
        Case_Leads__c case1 = new Case_Leads__c( unicourt_case_id__c= 'HFKCQLBTIBKEMKEVPFAW7CTMNVRCC0998', Case_Name__c = 'testCase',Case_Management_Conference__c = System.Today()+1 );
        Case_Leads__c case2 = new Case_Leads__c( unicourt_case_id__c= 'HFKCQLBTIBKEMKEVPFAW7CTMNVRCC0990', Case_Name__c = 'testCase2',Case_Management_Conference__c = System.Today()+1 );
        Case_Leads__c testParentCase = new Case_Leads__c( unicourt_case_id__c= 'HFKCQLBTIBKEMKEVPFAW7CTMNVRCC0991', Case_Name__c = 'testParentCase',Case_Management_Conference__c = System.Today()+1 );
        List<Case_leads__c> caselist = new List<Case_Leads__c>();
        caselist.add(case1);
        caselist.add(case2);
        caselist.add(testParentCase);
        insert caselist;
        List<Case_Leads__c> selectedCases = new List<Case_Leads__c>{case1,case2};
        ApexPages.StandardSetController stdCont = new ApexPages.StandardSetController(selectedCases);
        stdCont.setSelected(selectedCases);
        GroupSelectedCasesController groupSelected = new GroupSelectedCasesController(stdCont);
        groupSelected.parentGroupName = 'testParentCase';
        Test.startTest();
        groupSelected.findParentCases();
        System.assert(groupSelected.parentCases.size() > 0);
        groupSelected.parentCaseId = testParentCase.Id;
        groupSelected.groupSelectedCaseLeads();
        System.assert(groupSelected.groupingSuccessful);
        groupSelected.gotoParent();
        Test.stopTest();
    }
}