src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Primary_Rep_Email__c</fullName>
        <label>Commission-Primary Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Commission_Secondary_Rep_Email__c</fullName>
        <label>Commission-Secondary Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Commission_Tertiary_Rep_Email__c</fullName>
        <label>Commission-Tertiary Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Case Leads</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Case</label>
        <referenceTo>Case_Leads__c</referenceTo>
        <relationshipLabel>Child Cases</relationshipLabel>
        <relationshipName>Case_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>primary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>secondary_rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tertiary_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommissionTriggerHepler.cls
public class CommissionTriggerHepler {
    
    public static void onAfterInsert(List<Commission__c> newCommissions){
        
    }
    
    public static void onAfterUpdate(List<Commission__c> newCommissions, Map<Id,Commission__c> oldMap ){
        updateCaseLeads(newCommissions,oldMap);
    }
    
    /*
* Purpose: when Primary, Secondary or Tertiary Rep changes, update their email id to Case Lead Fields.
* Author: Jitendra Kumar, 12-Jan-2019
*/
    private static void updateCaseLeads(List<Commission__c> newCommissions, Map<Id,Commission__c> oldMap){
        Set<ID> commissionIds = new Set<Id>();
        for(Commission__c comm : newCommissions){
            if(oldMap != null && (comm.Primary_Rep__c != oldMap.get(comm.Id).Primary_Rep__c || 
                                  comm.Secondary_Rep__c != oldMap.get(comm.Id).Secondary_Rep__c ||
                                  comm.Tertiary_Rep__c != oldMap.get(comm.Id).Tertiary_Rep__c)){
                                      commissionIds.add(comm.Id);
                                  }
        }
        List<Case_Leads__c> caseLeadList = new List<Case_Leads__c>();
        for(commission__c comm : [select id, Primary_Rep__r.email, Secondary_Rep__r.email, Tertiary_Rep__r.email, 
                                  (select id, Commission_Primary_Rep_Email__c, Commission_Secondary_Rep_Email__c, Commission_Tertiary_Rep_Email__c from Case_Leads__r) 
                                  from commission__c where id in :commissionIds]){
                                      if(comm.Case_Leads__r.size() > 0){
                                          for(Case_Leads__c cl : comm.Case_Leads__r){
                                              cl.Commission_Primary_Rep_Email__c = comm.Primary_Rep__r.email;
                                              cl.Commission_Secondary_Rep_Email__c = comm.Secondary_Rep__r.email;
                                              cl.Commission_Tertiary_Rep_Email__c = comm.Tertiary_Rep__r.email;
                                              caseLeadList.add(cl);
                                          }
                                      }           
                                  }
        update caseLeadList;
        
    }
    
}