src/objects/Case_Leads__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Conference__c</fullName>
        <label>Case Management Conference</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Lead</label>
    <nameField>
        <label>Case Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FollowActionWindowControllerTest.cls
@isTest
private class FollowActionWindowControllerTest {
	
    @isTest
    private static void testAddFollower(){
        Case_Leads__c case1 = new Case_Leads__c(Case_Name__c = 'testCase',Case_Management_Conference__c = System.Today()+1 );
        insert case1;
        ApexPages.StandardController sc = new ApexPages.StandardController(case1);
        FollowActionWindowController FAController = new FollowActionWindowController(sc);
        Test.setMock(HttpCalloutMock.class, new TrackCasesCalloutMock());
        FAController.addFollower();
        
    }
}