src/objects/Court_Search_Email_Template__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The email template , to be used, when a email is send via the court search page</description>
    <fields>
        <fullName>Exclude_Fields_For_Logging__c</fullName>
        <description>These fields should not be logged when the Deposition Logging Trigger runs</description>
        <inlineHelpText>These fields should not be logged when the Deposition Logging Trigger runs</inlineHelpText>
        <label>Exclude Fields For Logging</label>
        <type>TextArea</type>
    </fields>
    <label>Court Search Email Template</label>
</CustomObject>

src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Change_Log__c</fullName>
        <description>Captures the fields changed during updates, is not shown on the UI, used in Email templates</description>
        <inlineHelpText>Captures the fields changed during updates, is not shown on the UI, used in Email templates</inlineHelpText>
        <label>Change Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Generate_Change_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this field is checked, the trigger runs and computes the values that are changed, enable selectively for testing and debugging first.</description>
        <inlineHelpText>When this field is checked, the trigger runs and computes the values that are changed, enable selectively</inlineHelpText>
        <label>Generate Change Log</label>
        <type>Checkbox</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DepositionManager.cls
/*************************************************************
*Deposition Manager, takes care of Logging changes and future updates
**************************************************************/
public with sharing class DepositionManager {
  
  private static Map<String,List<Schema.DescribeFieldResult>> mapFields = new Map<String,List<Schema.DescribeFieldResult>>();
  private static Boolean isExecuted = false;
  
  
  public void setChangeLog(List<Deposition__c> lstDeposition) {
     if(isExecuted == true) return;
     
     isExecuted = true; 
     for(Deposition__c deposition :lstDeposition) {
       if(deposition.Generate_Change_Log__c != true) {
         continue;
       }
      deposition.Change_Log__c = generatePayLoad(deposition,getFields('Deposition__c',deposition));
    }
  }
  
   public static void sendEmail(Exception ex) {
  	try {
	    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	    String[] toAddress = new String[]{'iyer.salesforce@gmail.com'};
	    mail.setSubject('Exception occurred');
	    mail.setToAddresses(toAddress);
	    String message = ex.getMessage() + '\n<-->';
	    message += ex.getStackTraceString() + '\n<-->';
	    message += ex.getLineNumber() + '\n<-->';
	    message += ex.getTypeName();
	    
	    mail.setPlainTextBody(message);
	    
	    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
  	}
  	catch(Exception e) {
  	  System.debug(e); //Ignore what else can we do
  	}
  }
  
  
  //=========================================================================//
  //Generate String to be logged
  //=========================================================================//
  private static String generatePayLoad(SObject sObj,List<Schema.DescribeFieldResult> llstFields) {
    String payLoad = '';
    SObject oldSObject = Trigger.oldMap.get(sObj.Id);
   
    for(Schema.DescribeFieldResult fieldResult :llstFields){
      String fld =  fieldResult.getName();
      string newFieldValue  =  String.valueOf(sObj.get(fld));     
      
      if(oldSObject != null) {
        String oldFieldValue = String.valueOf(oldSObject.get(fld));
        if(oldFieldValue != newFieldValue) {
          payLoad += fieldResult.getLabel() + ' = ' + newFieldValue;    
          payload += ' ; (Old Value = ' + oldFieldValue + ')';
          payload += '\n';
        }  
      }
     
    }
    if(payload.length() > 32000) {
      return payload.subString(0,32000);
    }
    return payload.trim();
  }
  
  
  //----------------------------------------------------------------------//
  //get All Fields for the SObject,so that we can generate the String
  //----------------------------------------------------------------------//
  private static List<Schema.DescribeFieldResult> getFields(String objectType,SObject sObj) {
    if(mapFields.containsKey(objectType)) {
      return mapFields.get(objectType);
    }
    
    List<Schema.DescribeFieldResult> lstFields = new List<Schema.DescribeFieldResult>();
    
    Court_Search_Email_Template__c template = Court_Search_Email_Template__c.getInstance();
    Set<String> setExcludeFields = new Set<String>();
    
    if(!String.isBlank(template.Exclude_Fields_For_Logging__c)) {
      setExcludeFields.addAll(template.Exclude_Fields_For_Logging__c.split(';'));
    }
    
    //Describe Sobject and get the object Name and token
    Schema.DescribeSObjectResult result = sObj.getSObjectType().getDescribe(); 
    //Get all fields from the token
    Map<String, Schema.SObjectField> fldMap = result.fields.getMap();
    for(String key :fldMap.keyset()) {
      Schema.DescribeFieldResult fldResult =  fldMap.get(key).getDescribe();
      String fldName = fldResult.getName();
      
      if(setExcludeFields.contains(fldName)) {
        continue;
      }
      
      lstFields.add(fldResult);
    }
    //Sort the fields for easy debugging and logging
    //lstFields.sort();
    mapFields.put(objectType,lstFields);
    
    return mapFields.get(objectType);
  }
}