src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled_Time__c</fullName>
        <label>Cancelled Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <label>Claims Professional</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Client_Source__c</fullName>
        <label>Corporate Client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AIG</fullName>
                </value>
                <value>
                    <fullName>Allstate</fullName>
                </value>
                <value>
                    <fullName>Amica</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T (Troy)</fullName>
                </value>
                <value>
                    <fullName>BASF</fullName>
                </value>
                <value>
                    <fullName>Cardinal Health</fullName>
                </value>
                <value>
                    <fullName>CSAA Insurance</fullName>
                </value>
                <value>
                    <fullName>DuPont</fullName>
                </value>
                <value>
                    <fullName>Electric Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Erie Insurance</fullName>
                </value>
                <value>
                    <fullName>Farmers Insurance</fullName>
                </value>
                <value>
                    <fullName>Fireman’s Fund</fullName>
                </value>
                <value>
                    <fullName>Gateway Risk Services</fullName>
                </value>
                <value>
                    <fullName>GEICO</fullName>
                </value>
                <value>
                    <fullName>Global Indemnity</fullName>
                </value>
                <value>
                    <fullName>Horace Mann</fullName>
                </value>
                <value>
                    <fullName>HPE</fullName>
                </value>
                <value>
                    <fullName>Liberty Mutual</fullName>
                </value>
                <value>
                    <fullName>Markel</fullName>
                </value>
                <value>
                    <fullName>Mass Mutual</fullName>
                </value>
                <value>
                    <fullName>Medical Protective</fullName>
                </value>
                <value>
                    <fullName>Mercury Insurance</fullName>
                </value>
                <value>
                    <fullName>National Indemnity Company of the South</fullName>
                </value>
                <value>
                    <fullName>National Liability &amp; Fire Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>No Corporate Client</fullName>
                </value>
                <value>
                    <fullName>North American Risk Services</fullName>
                </value>
                <value>
                    <fullName>Old Republic Contractors</fullName>
                </value>
                <value>
                    <fullName>Pioneer</fullName>
                </value>
                <value>
                    <fullName>Preferred Mutual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date_To_The_Client_Computed__c</fullName>
        <description>Due Date to the Client in Business Days computed automatically via Trigger</description>
        <label>Due Date To The Client</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Duration__c</fullName>
        <description>How long does the client expect this event to last?</description>
        <label>Estimated Duration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Deposition</fullName>
                    <default>true</default>
                    <label>Deposition</label>
                </value>
                <value>
                    <fullName>Examination Under Oath</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Statement Under Oath</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Video Playback</fullName>
                </value>
                <value>
                    <fullName>Client Meeting</fullName>
                </value>
                <value>
                    <fullName>Captioned Meeting</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Intra-co</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite Level (Business Days)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Same day turnaround</fullName>
                </value>
                <value>
                    <fullName>Next day turnaround</fullName>
                </value>
                <value>
                    <fullName>2 day turnaround</fullName>
                </value>
                <value>
                    <fullName>3 day turnaround</fullName>
                </value>
                <value>
                    <fullName>4 day turnaround</fullName>
                </value>
                <value>
                    <fullName>5 day turnaround</fullName>
                </value>
                <value>
                    <fullName>6 day turnaround</fullName>
                </value>
                <value>
                    <fullName>7 day turnaround</fullName>
                </value>
                <value>
                    <fullName>8 day turnaround</fullName>
                </value>
                <value>
                    <fullName>9 day turnaround</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Uploaded_By_Client__c</fullName>
        <defaultValue>false</defaultValue>
        <label>File Uploaded By Client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Google_Drive_Folder_Id__c</fullName>
        <label>Google Drive Folder Id</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GuestEmail__c</fullName>
        <label>Scheduler Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>GuestName__c</fullName>
        <label>Scheduler Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GuestPhone__c</fullName>
        <label>Scheduler Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hiring_Attorney_Email__c</fullName>
        <label>Hiring Attorney Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Firm__c</fullName>
        <label>Hiring Firm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Claim_Info__c</fullName>
        <label>Insurance Claim Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_Contact__c</fullName>
        <label>Location Contact</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matter_Number__c</fullName>
        <label>Matter Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_CR_Firm__c</fullName>
        <description>The court reporting firm for which we&apos;re handling this deposition.</description>
        <label>Networking/Covering For</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporter_EOD_Check_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporter EOD Check In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate that there are special instructions below.</description>
        <label>Special Instructions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VIP_Level__c</fullName>
        <label>VIP Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP 1</fullName>
                </value>
                <value>
                    <fullName>VIP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DepositionCloneCtrl.cls
public with sharing  class DepositionCloneCtrl{
        public Map<String,Boolean> fieldChecks{set;get;}
        public Deposition__c obj{set;get;}
        private ApexPages.StandardController controller;
        public list<Deposition__c> depositions{get;set;}
        private Set<String> depositionFields = new Set<String>();
        public integer recCount{get;set;}
        public boolean isMultiple{get;set;}
        public Boolean isSaved{get;set;}
        public integer ismulti{get;set;}
        public DepositionCloneCtrl (ApexPages.StandardController controller) {
            this.controller = controller;
            recCount=1;
            isMultiple=false;
            isSaved = false;
            fieldChecks = new Map<String,Boolean> ();
            Map<String, Schema.SobjectField> fields = 
            Schema.SobjectType.Deposition__c.fields.getMap();
            set<String> notInclude = new set<String>{'Cancelled_Time__c','Google_Drive_Folder_Id__c'};
            set<String> defaultSelectedFields = new set<String>{'Case_Name__c','Deposition_Services__c','File_Uploaded_By_Client__c','Hiring_Firm__c',
                                        'Reporter_EOD_Check_In__c','GuestName__c','Deposition_Status__c','GuestEmail__c','Expedite__c','GuestPhone__c','Due_Date_To_The_Client_Computed__c',
                                         'Hiring_Attorney__c','Insurance_Claim_Info__c','Hiring_Attorney_Email__c','Claims_Professional__c','Matter_Number__c','Time_Zone__c',
                                         'Primary_CR_Firm__c','Estimated_Duration__c',
                                         'Event_Type__c','Location_Contact__c','VIP_Level__c','Source__c','Corporate_Client_Source__c','Primary_Court_Reporting_Firm__c'};
            Set<String>setFieldsNames = new Set<String>{'Case_Name__c','Deposition_Services__c','Special_Instructions__c','File_Uploaded_By_Client__c','Hiring_Firm__c',
                                        'Reporter_EOD_Check_In__c','GuestName__c','Deposition_Status__c','GuestEmail__c','Expedite__c','GuestPhone__c','Due_Date_To_The_Client_Computed__c',
                                         'Hiring_Attorney__c','Insurance_Claim_Info__c','Hiring_Attorney_Email__c','Claims_Professional__c',
                                         'Matter_Number__c','Deposition_Date__c', 'Billing_Notes__c', 'Deposition_Time__c', 'Primary_CR_Firm__c','Time_Zone__c','Estimated_Duration__c',
                                         'Deponent_Name__c', 'Event_Type__c',
                                         
                                         'Event_Location__c','Reporter_Instructions__c','Location_Contact__c','Video_Tech_Instructions__c','VIP_Level__c',
                                         'Interpreter_Instructions__c','Source__c','Corporate_Client_Source__c','Primary_Court_Reporting_Firm__c'
                                         ,'Start_Time__c'};
            
            String fieldCSV ='';
           /*for (String s : fields.keySet()) {
            // Only include accessible fields 
            system.debug('*** s '+s +' field '+fields.get(s));
            system.debug('$$$$$ '+fields.get(s).getDescribe().isCreateable());
            
                if (fields.get(s).getDescribe().isAccessible() && fields.get(s).getDescribe().isUpdateable()&&
                    fields.get(s).getDescribe().isCustom() && !notInclude.contains(String.valueof(fields.get(s)))) {
                        depositionFields.add(fields.get(s).getDescribe().getName());
                        fieldCSV+=(fields.get(s).getDescribe().getName())+',';
                        fieldChecks.put(fields.get(s).getDescribe().getName(),defaultSelectedFields.contains(fields.get(s).getDescribe().getName()));
                }
            }
            */
            for (String fieldName : setFieldsNames ) {
                 fieldCSV+=fieldName+',';
                 depositionFields.add(fieldName);     
                 fieldChecks.put(fieldName,defaultSelectedFields.contains(fieldName));
            }
            Deposition__c rec = (Deposition__c)controller.getRecord();
            obj = database.query('SELECT ' + fieldCSV.removeEnd(',') + ' FROM Deposition__c WHERE ID=\'' +rec.id +'\' LIMIT 1');
            obj.Deposition_Status__c = 'Scheduled';
            obj.Reporter_EOD_Check_In__c= false;
            obj.Due_Date_To_The_Client_Computed__c = null;    
            
            
        }
        
        public  List<String> availableFields {
            get {
                controller.reset(); 
                controller.addFields(new List<String>(depositionFields));
                    return new List<String>(depositionFields);
            }
        }   
        public Pagereference onsave(){
            if(recCount<1){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please enter value'));
                return null;
            }
            list<sObject> sobjList=new list<sObject>();
            try{
                for(integer i=0;i<recCount;i++){
                    sObject sObj = Schema.getGlobalDescribe().get('Deposition__c').newSObject() ;
                    system.debug('**** obj '+obj);
                    for(string key: fieldChecks.keyset()){
                        if(fieldChecks.get(key)){
                            system.debug('****** '+key +' ' + fieldChecks.get(key));
                            system.debug('8888888888 '+ obj.get(key));
                            //sObj.Deposition_Date__c='';
                            
                            
                            sObj.put(key, obj.get(key)) ;
                        }
                    }
                   sobjList.add(sObj);
                   system.debug('***** sObj '+sObj);
               }
               system.debug('**** sobjList '+sobjList);
               
               
               if(sobjList.size()>0){
                   insert sobjList;
               }
               if(sobjList.size()==1){
                   
                   system.debug('*** depositions '+depositions);
                   
                   
                  
                   return new pageReference('/'+sobjList[0].id+'/e?retURL=%2F'+sobjList[0].id);
               }else{
                   isMultiple=true;
                   depositions=new list<Deposition__c>();
                   depositions=[select id, name,Deposition_Date__c, Deponent_Name__c, Event_Location__c
                               from Deposition__c where Id IN: sobjList];
                   return null;
               }
               
               
           }catch(Exception e){
               system.debug('****** Exception '+e);
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,e.getMessage()));
               return null;
           }
           
           
            //sobject s=new sobject();
            
        }
        
        public void saveDepositions(){
            try{
                update depositions;
                isSaved = true;
            }catch(Exception e){
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,e.getMessage()));
              
           }
        }
    
}