src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DepositionInvoiceCtrlTest.cls
@isTest
private class DepositionInvoiceCtrlTest {

	private static testMethod void testInvoices() {
        TestFactory tFact = new TestFactory();
        List<Invoice__c> invoices = tFact.invoices;
        
        System.runAs(tFact.communtiyUser){
            User usr = [SELECT Id, ContactId FROM User Where Id = :UserInfo.getUserId() LIMIT 1];
            Invoice__c inv =[Select Id, Deposition__c FROM Invoice__c WHERE Contact__c =:usr.ContactId LIMIT 1];
            ApexPages.currentPage().getParameters().put('id',inv.Deposition__c);
            ApexPages.currentPage().getParameters().put('invid',inv.Id);
            DepositionInvoiceCtrl control = new DepositionInvoiceCtrl(new ApexPages.StandardController(new Deposition__c(Id = inv.Deposition__c)));
            control.getInvoices();
            control.getInvoiceData();
        }
	}

}