src/objects/Deposition__c.object
<CustomObject>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Upload_File__c.object
<CustomObject>
    <fields>
        <fullName>Attachment_Check_Time__c</fullName>
        <description>Last Date Time, when the Workflow Checked for existence of Attachment on the Depostion Record based on Attachment ID</description>
        <inlineHelpText>Last Date Time, when the Workflow Checked for existence of Attachment on the Depostion Record based on Attachment ID</inlineHelpText>
        <label>Attachment Check Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deposition_Number__c</fullName>
        <label>Deposition Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Upload Files</relationshipLabel>
        <relationshipName>Upload_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Upload File</label>
    <nameField>
        <displayFormat>Upload-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UploadFileController_Test.cls
@isTest
private class UploadFileController_Test {
  
  @isTest
  private static void Test_UploadFile(){
    TestUtils tUtils = new TestUtils();
    Deposition__c deposition = tUtils.createDeposition();
    
    UploadFileController fileController = new UploadFileController();
    fileController.validateFile();
    
    fileController.uploadFile.Deposition_Number__c = 'aaaaa';
    fileController.saveFile();
    
    String name = [SELECT Name from Deposition__c WHERE ID = :deposition.Id].Name;
    fileController.uploadFile.Deposition_Number__c = name;
    fileController.getUploadDocument().Name = 'sss';
    fileController.getUploadDocument().Body = Blob.valueOf('hello');
    
    fileController.saveFile();
    
    Account account = tUtils.insertAccount();
    Contact contact = tUtils.insertContact(account.ID);
    tUtils.insertAttendee(contact.Id, deposition.ID);
    
    fileController.uploadFile.Email__c = contact.Email;
    fileController.saveFile();
  }
  
  
  @isTest
  private static void Test_UploadFile2(){
    TestUtils tUtils = new TestUtils();
    Deposition__c deposition = tUtils.createDeposition();
    
    UploadFileController fileController = new UploadFileController();
    String name = [SELECT Name from Deposition__c WHERE ID = :deposition.Id].Name;
    fileController.uploadFile.Deposition_Number__c = name;
    fileController.getUploadDocument().Name = 'sss';
    fileController.getUploadDocument().Body = Blob.valueOf('hello');
    
    Account account = tUtils.insertAccount();
    Contact contact = tUtils.insertContact(account.ID);
    tUtils.insertAttendee(contact.Id, deposition.ID);
    
    fileController.uploadFile.Email__c = contact.Email;
    fileController.saveFile();
    
    Upload_File__c uploadFile = [SELECT Attachment_Check_Time__c FROM Upload_File__c Limit 1];
    uploadFile.Attachment_Check_Time__c = System.now();
    update uploadFile;
    
  }
}