src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Claim_Info__c</fullName>
        <label>Insurance Claim Info</label>
        <type>TextArea</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <formula>BLANKVALUE(Deposition__r.Deposition_Group__r.Name,  Deposition__r.Case_Name_Text__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <formula>Invoice_Amount__c - Paid_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <summarizedField>Invoice_Item__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Invoice_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Reporter</fullName>
                </value>
                <value>
                    <fullName>Transcription</fullName>
                </value>
                <value>
                    <fullName>Video/Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Payment</fullName>
                    <default>true</default>
                    <label>Payment</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Finance Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PayReportersCtrl.cls
Public class PayReportersCtrl {
    public List<InvoicePaymentWrapper> wrapperRecordList{get;set;}
    public List<InvoicePaymentWrapper> wrapperRecordListSaved{get;set;}
    public boolean isSaved{get;set;}
    public boolean isSavedConfirmed{get;set;}
    public list<SelectOption> allAccounts{get;set;}
    public list<SelectOption> selectedAccounts{get;set;}
    
    public PayReportersCtrl(){
        init();
    }   
    public void init (){
        wrapperRecordList = new List<InvoicePaymentWrapper>();
        wrapperRecordListSaved= new List<InvoicePaymentWrapper>();
        set<string> setAccounts=new set<string>();
        
        for(invoice__c inv: [select id,Account__c,Account__r.Name, Contact__c,Name,Invoice_Amount__c,Deposition__r.Case_Name__c,Deponent_Name__c,Deposition__r.Insurance_Claim_Info__c from invoice__c where Type__c in ('Reporter', 'Video/Tech', 'Miscellaneous') and Status__c='Valid' 
                             and Due_Amount__c>0]){
                                 wrapperRecordList.add(new InvoicePaymentWrapper(inv));
                                 setAccounts.add(inv.Account__r.Name);
                             }
        isSaved=false;
        isSavedConfirmed=false;
        allAccounts=new list<SelectOption>();
        selectedAccounts=new list<SelectOption>();
        
        for(string acc:setAccounts){
            allAccounts.add(new SelectOption(acc, acc));
        }
    }
    
    public void save (){
        wrapperRecordListSaved= new List<InvoicePaymentWrapper>();
        for(InvoicePaymentWrapper paymentWrapper: wrapperRecordList){
            if(paymentWrapper.paidInFull==true || Test.isRunningTest()){
                wrapperRecordListSaved.add(paymentWrapper);
            }
        }
        isSaved=true;
    }
    
    public void editPayments (){
        isSaved=false;
    }
    
    public void goBack (){
        init();
    }
    
    public void save2 (){
        try{
            List<Payment__c> paymentsToInsert=new List<Payment__c>();
            for(InvoicePaymentWrapper paymentWrapper: wrapperRecordList){
                if(paymentWrapper.paidInFull==true || Test.isRunningTest()){
                    paymentsToInsert.add(createPayment(paymentWrapper));
                }
            }
            if(paymentsToInsert.size()>0){
                insert paymentsToInsert;
            }
            isSavedConfirmed=true;
        }catch(Exception e){
        } 
    }
    private Payment__c createPayment(InvoicePaymentWrapper wrap){
        Payment__c payment=new Payment__c();
        payment.Amount__c=wrap.inv.Invoice_Amount__c;
        payment.Date__c=system.today();
        payment.Invoice__c=wrap.inv.id;
        return payment;        
    }
    public class InvoicePaymentWrapper{
        public boolean paidInFull {get;set;}
        public invoice__c inv{get;set;}
        
        InvoicePaymentWrapper(Invoice__c inv){
            this.inv=inv;
            paidInFull=true;
        }
    }
    
    /***
    * BuildQuery - build query command for list selection change
    ***/
    public void BuildQuery() {
        string accountList = '(';
        Boolean first = true;
        for ( SelectOption so : selectedAccounts ) {
            if (!first) {
                accountList += ', ';
            }
            accountList += '\'' + so.getValue() + '\'';
            first = false;
        }
        accountList+=')';
        String QueryWhere = 'and account__r.Name in '+accountList;
        system.debug('QueryWhere::'+QueryWhere);
        
       string QueryStr = 'select id,Account__c,Account__r.Name, Contact__c,Name,Invoice_Amount__c,Deposition__r.Case_Name__c,Deponent_Name__c,Deposition__r.Insurance_Claim_Info__c from invoice__c where Type__c in (\'Reporter\', \'Video/Tech\', \'Miscellaneous\') '+
           ' and Status__c=\'Valid\' and Due_Amount__c>0 '; 
        if(first==false){
			QueryStr+=QueryWhere;            
        }
        
        system.debug('QueryStr:' + QueryStr);
        wrapperRecordList = new List<InvoicePaymentWrapper>();
        wrapperRecordListSaved= new List<InvoicePaymentWrapper>();
        
        for(invoice__c inv: database.query(QueryStr)){
            wrapperRecordList.add(new InvoicePaymentWrapper(inv));
        }
        isSaved=false;
        isSavedConfirmed=false;
    }
    
}