src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_Email_Address__c</fullName>
        <label>Accounting Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Billed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Notes__c</fullName>
        <label>Billing Notes</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Business_Days_Until_Transcript_is_Due__c</fullName>
        <formula>IF(Deposition_Date__c  &gt;= TODAY(),NULL,
IF(TEXT(Deposition_Status__c) = &quot;Production Complete&quot; ,NULL,
IF(TEXT(Deposition_Status__c) = &quot;Cancelled&quot; ,NULL,
Due_Date_To_The_Client_Computed__c - TODAY()
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Days Until Transcript is Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CR_Email_Address__c</fullName>
        <label>CR Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Cancelled_Date__c</fullName>
        <label>Cancelled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancelled_Time__c</fullName>
        <label>Cancelled Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Change_Log__c</fullName>
        <description>Captures the fields changed during updates, is not shown on the UI, used in Email templates</description>
        <inlineHelpText>Captures the fields changed during updates, is not shown on the UI, used in Email templates</inlineHelpText>
        <label>Change Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <label>Claims Professional</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Notes__c</fullName>
        <label>Client Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Completed_By__c</fullName>
        <label>Completed By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirm_Client__c</fullName>
        <label>Confirm - Client</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Reporter__c</fullName>
        <label>Confirm - Reporter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm_Video_Tech__c</fullName>
        <label>Confirm - Video Tech</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                    <default>true</default>
                    <label>Not Sent</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirm__c</fullName>
        <formula>IF(AND(TEXT(Deposition_Status__c) != &apos;Confirmed&apos;,TEXT(Deposition_Status__c) != &apos;Cancelled&apos;), HYPERLINK(&apos;http://nextgen.force.com/ConfirmDeposition?id=&apos;+ Name+&apos;&amp;code=&apos;+Id+&apos;&amp;type=C&apos;, &apos;Confirm&apos;) ,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Confirm</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Court_Reporter_Count__c</fullName>
        <description>Includes the count of Court Reporter for a Deposition</description>
        <inlineHelpText>Includes the count of Court Reporter for a Deposition</inlineHelpText>
        <label>Court Reporter Count</label>
        <summaryFilterItems>
            <field>Attendee__c.Role__c</field>
            <operation>equals</operation>
            <value>Court Reporter</value>
        </summaryFilterItems>
        <summaryForeignKey>Attendee__c.Deposition__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Day_Of_The_Week_Transcript_Due__c</fullName>
        <formula>CASE(MOD(Due_Date_To_The_Client_Computed__c - DATE(1900, 1, 6), 7), 0, &quot;Saturday&quot;, 1, &quot;Sunday&quot;, 2, &quot;Monday&quot;, 3, &quot;Tuesday&quot;, 4, &quot;Wednesday&quot;, 5, &quot;Thursday&quot;, 6, &quot;Friday&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day Of The Week Transcript Due to Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_Of_The_Week__c</fullName>
        <formula>CASE(MOD( Deposition_Date__c - DATE(1900, 1, 6), 7), 0, &quot;Saturday&quot;, 1, &quot;Sunday&quot;, 2, &quot;Monday&quot;, 3, &quot;Tuesday&quot;, 4, &quot;Wednesday&quot;, 5, &quot;Thursday&quot;, 6, &quot;Friday&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day Of The Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Until_Transcript_Due_Date__c</fullName>
        <description>The old formula was /*Due_date__c - TODAY() - 2*/  Now using the new field</description>
        <formula>/*OLD FORMULA*/
/*Due_date__c - TODAY() - 2*/ 
Due_Date_To_The_Client_Computed__c - TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Until Transcript Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GuestEmail__c</fullName>
        <label>Scheduler Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Email_Sent__c</fullName>
        <label>Last Email Sent</label>
        <type>Date</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchSendConfirmationEmail.cls
global with sharing class BatchSendConfirmationEmail implements Database.Stateful,Database.Batchable<sObject>
{
 global string query;
 global Set<string> DepositionSet=new Set<string>();
 
  global Database.QueryLocator start(Database.BatchableContext BC)   
  {
    return Database.getQueryLocator('Select name,id,Account__c,Accounting_Email_Address__c,BIlled__c,Billing_Notes__c,Business_Days_Until_Transcript_is_Due__c,Cancelled_Date__c,Cancelled_Time__c,Case_Name__c,'+
                                    'Change_Log__c,Claims_Professional__c,Client_Notes__c,Completed_By__c,Confirm__c,Confirm_Client__c,Confirm_Reporter__c,Confirm_Video_Tech__c,'+
                                    'Court_Reporter_Count__c,OwnerId,GuestEmail__c,CR_Email_Address__c,Day_Of_The_Week__c,Day_Of_The_Week_Transcript_Due__c,Days_Until_Transcript_Due_Date__c '+
                                    'from Deposition__c where id in:DepositionSet');  
  }
  
   global void execute(Database.BatchableContext BC,  List<Deposition__c> DepositionList){ 
   list<String>listOfAddresses=new list<String>();
   List<Deposition__c> depUpdateList=new List<Deposition__c>();
   EmailTemplate et = [select Id,Name,Subject,body from EmailTemplate where name =:'Legal staff - Confirmation - Tomorrow'];
       if(et!=null)
       {
       system.debug('!!!!!!!!!!!depositionset!!!!!!!!!!!'+depositionlist);
           for(Deposition__c dep:DepositionList)
           {
                 listOfAddresses.add(dep.GuestEmail__c);
                 ID whatID = dep.id;
                 List<Contact> cnts = [select id, Email from Contact where email != null limit 1];
                 List<Messaging.SingleEmailMessage> msgList= new List<Messaging.SingleEmailMessage>();
                 Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
                 msg.setTemplateId( et.id );
                 msg.setWhatId(whatID);
               if(!cnts.isEmpty() ){
                 msg.setTargetObjectId(cnts[0].id);
               }
                 msg.setToAddresses(listOfAddresses);
                 msgList.add(msg);
                // Send the emails in a transaction, then roll it back
                Savepoint sp = Database.setSavepoint();
                 if (!Test.isRunningTest())
                    Messaging.sendEmail(msgList); // Dummy email send   
                 Database.rollback(sp); // Email will not send as it is rolled Back
                // Send Actual email
                OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'schedule@nextgenreporting.com'];

                 List<Messaging.SingleEmailMessage> msgListToBeSend = new List<Messaging.SingleEmailMessage>();
                 for (Messaging.SingleEmailMessage email : msgList) {
                     Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
                     emailToSend.setToAddresses(email.getToAddresses());
                     if ( owea.size() > 0 ) {
                      emailToSend.setOrgWideEmailAddressId(owea.get(0).Id);
                      }
                     emailToSend.setPlainTextBody(email.getPlainTextBody());
                     emailToSend.setHTMLBody(email.getHTMLBody());
                     emailToSend.setSubject(email.getSubject());
                     emailToSend.setSaveAsActivity(true);
                     msgListToBeSend .add(emailToSend);
                 }
                 if (!Test.isRunningTest())
                    Messaging.sendEmail(msgListToBeSend);
                    
                dep.Last_Email_Sent__c=Date.Today();
                depUpdateList.add(dep);     
                
                
                
                 List<Task> tasks = new List<Task>();
                    tasks.add(new Task(
                    ActivityDate = Date.today(),
                    Subject='Online Application Sent',
                    WhatId = dep.Id,
                    OwnerId = UserInfo.getUserId(),
                    Status='Completed',description=String.valueof(msgListToBeSend[0])));
                 insert tasks;
                
           }
           if(!depUpdateList.isEmpty())
                update depUpdateList;
       }
   }
   
   global void finish(Database.BatchableContext info){
        
    }
    
}