src/objects/Deposition_Location__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>Kit Number</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kit 1</fullName>
                </value>
                <value>
                    <fullName>Kit 2</fullName>
                </value>
                <value>
                    <fullName>Kit 3</fullName>
                </value>
                <value>
                    <fullName>Kit 4</fullName>
                </value>
                <value>
                    <fullName>Kit 5</fullName>
                </value>
                <value>
                    <fullName>Kit 6</fullName>
                </value>
                <value>
                    <fullName>Kit 7</fullName>
                </value>
                <value>
                    <fullName>Kit 8</fullName>
                </value>
                <value>
                    <fullName>Kit 9</fullName>
                </value>
                <value>
                    <fullName>Kit 10</fullName>
                </value>
                <value>
                    <fullName>Kit 11</fullName>
                </value>
                <value>
                    <fullName>Kit 12</fullName>
                </value>
                <value>
                    <fullName>Kit 13</fullName>
                </value>
                <value>
                    <fullName>Kit 14</fullName>
                </value>
                <value>
                    <fullName>Kit 15</fullName>
                </value>
                <value>
                    <fullName>Kit 16</fullName>
                </value>
                <value>
                    <fullName>Kit 17</fullName>
                </value>
                <value>
                    <fullName>Kit 18</fullName>
                </value>
                <value>
                    <fullName>Kit 19</fullName>
                </value>
                <value>
                    <fullName>Kit 20</fullName>
                </value>
                <value>
                    <fullName>Kit 21</fullName>
                </value>
                <value>
                    <fullName>Kit 22</fullName>
                </value>
                <value>
                    <fullName>Kit 23</fullName>
                </value>
                <value>
                    <fullName>Kit 24</fullName>
                </value>
                <value>
                    <fullName>Kit 25</fullName>
                </value>
                <value>
                    <fullName>Kit 26</fullName>
                </value>
                <value>
                    <fullName>Kit 27</fullName>
                </value>
                <value>
                    <fullName>Kit 28</fullName>
                </value>
                <value>
                    <fullName>Kit 29</fullName>
                </value>
                <value>
                    <fullName>Kit 30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition Location</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposition Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <description>What gear are we using, and where is it?</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who currently has the equipment?</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Equipment</relationshipLabel>
        <relationshipName>Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposition_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposition Location</label>
        <referenceTo>Deposition_Location__c</referenceTo>
        <relationshipLabel>Equipment</relationshipLabel>
        <relationshipName>Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employees</fullName>
                    <default>true</default>
                    <label>Employees</label>
                </value>
                <value>
                    <fullName>In Transit</fullName>
                </value>
                <value>
                    <fullName>On Location</fullName>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Equipment</label>
    <nameField>
        <displayFormat>Kit {0}</displayFormat>
        <label>Kit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CheckInEquipmentExtension.cls
public with sharing class CheckInEquipmentExtension {
  Equipment__c equipment;
  
  public CheckInEquipmentExtension(ApexPages.StandardController controller) {
    this.equipment = (Equipment__c)controller.getRecord();
  }
  
  public Boolean getHasMessages() {
    return ApexPages.hasMessages();
  }
  
  
  public PageReference clearContact() {
    try {
      this.equipment.Contact__c = null;
      this.equipment.Deposition_Location__c = null;
      this.equipment.Status__c = 'In Our Office';
      
      update this.equipment;
    }
    catch(DmlException ex) {
      ApexPages.addMessages(ex);
      return null;
    }
    return new PageReference('/' + this.equipment.Id);
  }
  
  @isTest
  private static void Test_Equipment() {
    Equipment__c equipment = new Equipment__c();
    ApexPages.StandardController sController = new ApexPages.StandardController(equipment);
    
    CheckInEquipmentExtension ext = new CheckInEquipmentExtension(sController);
    ext.clearContact();
  }

}