src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice_Item__c.object
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DepositionReminderSchedulerTest.cls
@isTest
private class DepositionReminderSchedulerTest {
    
    private static testMethod void testSchedule() {
        TestFactory tFact = new TestFactory();
        List<Invoice_Item__c> items = tFact.invoiceItems;
        List<Deposition__c> depositions = tFact.depositions;
        Set<Id> depIds = new Set<Id>();
        for(Deposition__c deposition:depositions){
            depIds.add(deposition.Id);
            deposition.Deposition_Date__c = System.today().addDays(1);
        }
        update depositions;
        Test.startTest();
        DepositionReminderScheduler job = new DepositionReminderScheduler();
        String sch = '20 30 8 10 2 ?';
        String jobID = system.schedule('testDepositionReminderScheduler', sch, job);
        
        Test.stopTest();
    }
    
    
    
}