src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Change_Log__c</fullName>
        <description>Captures the fields changed during updates, is not shown on the UI, used in Email templates</description>
        <inlineHelpText>Captures the fields changed during updates, is not shown on the UI, used in Email templates</inlineHelpText>
        <label>Change Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <label>Claims Professional</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Notes__c</fullName>
        <label>Client Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Services__c</fullName>
        <label>Deposition Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Court Reporter</fullName>
                    <default>true</default>
                    <label>Court Reporter</label>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>LegalView (Remote Video)</fullName>
                </value>
                <value>
                    <fullName>Traditional Video</fullName>
                </value>
                <value>
                    <fullName>Realtime - Local</fullName>
                </value>
                <value>
                    <fullName>Realtime - Internet</fullName>
                </value>
                <value>
                    <fullName>Realtime - Possible</fullName>
                </value>
                <value>
                    <fullName>Rough Draft</fullName>
                </value>
                <value>
                    <fullName>Rough Draft - Possible</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Synchronized Video</fullName>
                </value>
                <value>
                    <fullName>Process Serving</fullName>
                </value>
                <value>
                    <fullName>Conference Room</fullName>
                </value>
                <value>
                    <fullName>Post Production</fullName>
                </value>
                <value>
                    <fullName>Advanced Video Services</fullName>
                </value>
                <value>
                    <fullName>Teleconference</fullName>
                </value>
                <value>
                    <fullName>Technical/medical/video/expert/interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Status__c</fullName>
        <label>Deposition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>In Production - Partially Complete</fullName>
                </value>
                <value>
                    <fullName>Production Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transcript on Hold – Sent to Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date_To_The_Client_Computed__c</fullName>
        <description>Due Date to the Client in Business Days computed automatically via Trigger</description>
        <label>Due Date To The Client</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Duration__c</fullName>
        <description>How long does the client expect this event to last?</description>
        <label>Estimated Duration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Deposition</fullName>
                    <default>true</default>
                    <label>Deposition</label>
                </value>
                <value>
                    <fullName>Examination Under Oath</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Statement Under Oath</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Video Playback</fullName>
                </value>
                <value>
                    <fullName>Client Meeting</fullName>
                </value>
                <value>
                    <fullName>Captioned Meeting</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Intra-co</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite Level (Business Days)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Same day turnaround</fullName>
                </value>
                <value>
                    <fullName>Next day turnaround</fullName>
                </value>
                <value>
                    <fullName>2 day turnaround</fullName>
                </value>
                <value>
                    <fullName>3 day turnaround</fullName>
                </value>
                <value>
                    <fullName>4 day turnaround</fullName>
                </value>
                <value>
                    <fullName>5 day turnaround</fullName>
                </value>
                <value>
                    <fullName>6 day turnaround</fullName>
                </value>
                <value>
                    <fullName>7 day turnaround</fullName>
                </value>
                <value>
                    <fullName>8 day turnaround</fullName>
                </value>
                <value>
                    <fullName>9 day turnaround</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Attorney__c</fullName>
        <label>Hiring Attorney Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Claim_Info__c</fullName>
        <label>Insurance Claim Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Matter_Number__c</fullName>
        <label>Matter Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DepositionEditExtn.cls
public class DepositionEditExtn{
    String firm= '';
    private final Deposition__c deposition;
    String oldStatus= '';
    String Deposition_Time = '';
    String Time_Zone= '';
    String Event_Location= '';
    String Case_Name= '';
    Date depDate ;
    
    String eventType='';
    String estimatedDuration = '';
    String matterNumber = ''; 
    String expedite_Level = '';
    String deponentName= '';
    String depositionServices = '';
    String hiringAttorney = '';
    String insuranceClaimInfo = '';
    String claimsProfessional = '';
    String clientNotes = '';
    Date dueDateToClient ;
    public DepositionEditExtn(ApexPages.StandardController cntrl) {
       deposition= (Deposition__c)cntrl.getRecord();
       oldStatus= deposition.Deposition_Status__c;
       Deposition_Time = deposition.Deposition_Time__c;
       Time_Zone= deposition.Time_Zone__c;
       Event_Location= deposition.Event_Location__c;
       Case_Name= deposition.Case_Name__c;
       depDate = deposition.Deposition_Date__c;
       dueDateToClient  = deposition.Due_Date_To_The_Client_Computed__c;
       eventType = deposition.Event_Type__c;
       estimatedDuration = deposition.Estimated_Duration__c;
       matterNumber = deposition.Matter_Number__c;
       expedite_Level = deposition.Expedite__c;
       
       deponentName = deposition.Deponent_Name__c;
       depositionServices = deposition.Deposition_Services__c;
       hiringAttorney = deposition.Hiring_Attorney__c;
       insuranceClaimInfo = deposition.Insurance_Claim_Info__c;
       claimsProfessional = deposition.Claims_Professional__c;
       clientNotes = deposition.Client_Notes__c;
       system.debug('$$$'+oldStatus);
    }
    
    public PageReference saveDeposition() {
       try {
           deposition.Change_Log__c = '';
           if(depDate !=deposition.Deposition_Date__c)
               deposition.Change_Log__c += 'The deposition date has been changed from '+ depDate +' to '+ deposition.Deposition_Date__c+'.\n';
           deposition.Change_Log__c = deposition.Change_Log__c.replaceAll(' 00:00:00','');
           if(Deposition_Time !=deposition.Deposition_Time__c)
               deposition.Change_Log__c += 'The deposition time has been changed from '+ Deposition_Time +' to '+ deposition.Deposition_Time__c+'.\n';
           if(Time_Zone!=deposition.Time_Zone__c)
               deposition.Change_Log__c += 'The deposition time zone has been changed from '+ Time_Zone+' to '+ deposition.Time_Zone__c+'.\n';
           if(Event_Location!=deposition.Event_Location__c )
               deposition.Change_Log__c += 'The event location has been changed from '+ Event_Location+' to '+ deposition.Event_Location__c +'.\n';
           
           if(Case_Name!=deposition.Case_Name__c )
               deposition.Change_Log__c += 'The case name has been changed from '+ Case_Name+' to '+ deposition.Case_Name__c +'.\n';
           if(oldStatus  !=deposition.Deposition_Status__c )
               deposition.Change_Log__c += 'The status has been changed from '+ oldStatus  +' to '+ deposition.Deposition_Status__c +'.\n';
           
           if(eventType!=deposition.Event_Type__c)
               deposition.Change_Log__c += 'The event type has been changed from '+ eventType+' to '+ deposition.Event_Type__c +'.\n';
           if(estimatedDuration!=deposition.Estimated_Duration__c)
               deposition.Change_Log__c += 'The estimated duration has been changed from '+ estimatedDuration+' to '+ deposition.Estimated_Duration__c+'.\n';
           if(matterNumber!=deposition.Matter_Number__c)
               deposition.Change_Log__c += 'The matter  number has been changed from '+ matterNumber+' to '+ deposition.Matter_Number__c+'.\n';
           if(expedite_Level!=deposition.Expedite__c)
               deposition.Change_Log__c += 'The expedite level has been changed from '+ expedite_Level+' to '+ deposition.Expedite__c+'.\n';    
           if(dueDateToClient  !=deposition.Due_Date_To_The_Client_Computed__c)
               deposition.Change_Log__c += 'The due date to the client has been changed from '+ dueDateToClient  +' to '+ deposition.Due_Date_To_The_Client_Computed__c+'.\n';    
           
           deposition.Change_Log__c = deposition.Change_Log__c.replaceAll(' 00:00:00','');
           
           if(deponentName !=deposition.Deponent_Name__c )
               deposition.Change_Log__c += 'The deponent name has been changed from '+ deponentName+' to '+ deposition.Deponent_Name__c +'.\n';
           if(depositionServices!=deposition.Deposition_Services__c )
               deposition.Change_Log__c += 'The deposition services has been changed from '+ depositionServices+' to '+ deposition.Deposition_Services__c +'.\n';
           if(hiringAttorney!=deposition.Hiring_Attorney__c )
               deposition.Change_Log__c += 'The hiring attorney has been changed from '+ hiringAttorney+' to '+ deposition.Hiring_Attorney__c +'.\n';
           if(insuranceClaimInfo!=deposition.Insurance_Claim_Info__c )
               deposition.Change_Log__c += 'The insurance claim info has been changed from '+ insuranceClaimInfo+' to '+ deposition.Insurance_Claim_Info__c +'.\n';
           if(claimsProfessional!=deposition.Claims_Professional__c )
               deposition.Change_Log__c += 'The claims professional has been changed from '+ claimsProfessional+' to '+ deposition.Claims_Professional__c +'.\n';
           if(clientNotes!=deposition.Client_Notes__c )
               deposition.Change_Log__c += 'The client notes has been changed from '+ clientNotes+' to '+ deposition.Client_Notes__c +'.\n';
           
           
           upsert(deposition);
       }
       catch(System.DMLException e) {
           ApexPages.addMessages(e);
           return null;
       }
       String pageURL= '' ;
       if(oldStatus!='Confirmed' && deposition.Deposition_Status__c=='Confirmed')
           pageURL +='&Confirmed=true';
       else if(oldStatus!='Cancelled' && deposition.Deposition_Status__c=='Cancelled'){
           pageURL +='&Cancelled=true';
       }
       
       
       if(Deposition_Time !=deposition.Deposition_Time__c  || Time_Zone!=deposition.Time_Zone__c|| 
          Event_Location!=deposition.Event_Location__c || Case_Name!=deposition.Case_Name__c || 
          (oldStatus !=deposition.Deposition_Status__c  && deposition.Deposition_Status__c!='Confirmed' && 
          deposition.Deposition_Status__c!='Cancelled') || depDate !=deposition.Deposition_Date__c ||
          expedite_Level!=deposition.Expedite__c || dueDateToClient  !=deposition.Due_Date_To_The_Client_Computed__c
           )
           pageURL +='&keyChanges=true';
       
               
       if(pageURL !=''){
           pageURL = '/apex/NotifyDepositionChanges?id='+deposition.id +pageURL ;
           return new PageReference(pageURL ).setRedirect(true);
       }
       return new PageReference ('/'+deposition.id);
    }

}