src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <label>Claims Professional</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Claim_Info__c</fullName>
        <label>Insurance Claim Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <formula>BLANKVALUE(Deposition__r.Deposition_Group__r.Name,  Deposition__r.Case_Name_Text__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <formula>Deposition__r.Claims_Professional__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claims Professional</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <summarizedField>Invoice_Item__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Invoice_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>IF(Paid_Amount__c&gt;= Invoice_Amount__c,&apos;Paid&apos;,IF(Paid_Amount__c==0,&apos;Unpaid&apos;,IF(Paid_Amount__c&gt;0,&apos;Partial&apos;,&apos;&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SearchInvoiceCtrl.cls
public with sharing class SearchInvoiceCtrl {
	  private String soql {get;set;}
	  public List<Invoice__c> invoices {get;set;}

      public String sortDir {
        get  { if (sortDir == null) {  sortDir = 'asc'; } return sortDir;  }
        set;
      }

      public String sortField {
        get  { if (sortField == null) {sortField = 'Invoice_Amount__c'; } return sortField;  }
        set;
      }

      public SearchInvoiceCtrl() {
        soql = 'select id,Account__r.name, Name,  Invoice_Amount__c, Deposition__r.Case_Name__c,'+
                                 'Deponent_Name__c,Deposition__r.Claims_Professional__c,Deposition__r.Primary_Court_Reporting_Firm__r.name,Deposition__r.Insurance_Claim_Info__c'+
                                    ' from invoice__c';
        runQuery();
      }

      // toggles the sorting of query from asc<-->desc
      public void toggleSort() {
        // simply toggle the direction
        sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
        // run the query again
        runQuery();
      }

      // runs the actual query
      public void runQuery() {
    	system.debug('soql::'+soql);
        try {
          invoices = Database.query(soql + ' order by ' + sortField + ' ' + sortDir + ' limit 20');
        } catch (Exception e) {
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Ooops!'));
        }

  }

  // runs the search with parameters passed via Javascript
  public PageReference runSearch() {
    String name = Apexpages.currentPage().getParameters().get('name');
    String amountLower = Apexpages.currentPage().getParameters().get('amountLower');
    String amountUpper = Apexpages.currentPage().getParameters().get('amountUpper');
    String onlyUnpaid = Apexpages.currentPage().getParameters().get('OnlyUnpaid');
      system.debug('onlyUnpaid::'+onlyUnpaid);

    soql = 'select id,Account__r.name, Name,  Invoice_Amount__c, Deposition__r.Case_Name__c,'+
                                 'Deponent_Name__c,Deposition__r.Claims_Professional__c,Deposition__r.Primary_Court_Reporting_Firm__r.name,Deposition__r.Insurance_Claim_Info__c'+
                                    ' from invoice__c where name!=null';
      if (!name.equals('')){
    	  soql += ' and name LIKE \'%'+ String.escapeSingleQuotes(name)+ '%\'';
      }
        if (!amountLower.equals('')){
            try{
	            Decimal d=decimal.valueOf(amountLower);
		      soql += ' and Invoice_Amount__c > '+d;
            }catch(Exception e){
            }
        }
      if (!amountUpper.equals('')){
            try{
	            Decimal d=decimal.valueOf(amountUpper);
		      soql += ' and Invoice_Amount__c < '+d;
            }catch(Exception e){
            }
        }
      if (!onlyUnpaid.equals('') && onlyUnpaid=='true'){
            try{
		      soql += ' and Payment_Status__c=\'Unpaid\''; 
            }catch(Exception e){
            }
        }
    // run the query again
    runQuery();
    return null;
  }
}