src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_CR_Firm__c</fullName>
        <description>The court reporting firm for which we&apos;re handling this deposition.</description>
        <label>Networking/Covering For</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestDepositionCalendarViewCntrl.cls
/**
                                    Name             : TestDepositionCalendarViewCntrl
                                    Date             : 05 Jan 2016
                                    Descripition     : Test Class for DepositionCalendarViewCntrl class.
*/                                   
@isTest
private class TestDepositionCalendarViewCntrl{

    @isTest
    private static void Test_DepositionCalendarViewCntrl() {
       
        TestUtils tUtils = new TestUtils();
        Deposition__c deposition = tUtils.createDeposition();
        deposition.Deposition_Date__c = System.today();
        
        Test.StartTest();
            DepositionCalendarViewCntrl  cntrl = new DepositionCalendarViewCntrl ();
            String dt = system.today().month()+'/'+system.today().day()+ '/'+system.today().year();
            for(Deposition__c  dep :cntrl.lstDepositions ){
                
                dep.Primary_CR_Firm__c = 'Nextgen Reportin';
            }
               
            cntrl.saveDepositions();
            DepositionCalendarViewCntrl.eventdata('','','Show all Jobs','');
            
            DepositionCalendarViewCntrl.eventdata(dt,dt,'test','NextGen Reporting');
            
       Test.StopTest();
    }


}