src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition_Time__c</fullName>
        <label>Deposition Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vidyo_Room__c</fullName>
        <label>Vidyo Room</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NextGen</fullName>
                </value>
                <value>
                    <fullName>Caren</fullName>
                </value>
                <value>
                    <fullName>Michele</fullName>
                </value>
                <value>
                    <fullName>Scot</fullName>
                </value>
                <value>
                    <fullName>Scott</fullName>
                </value>
                <value>
                    <fullName>Ken</fullName>
                </value>
                <value>
                    <fullName>Jason</fullName>
                </value>
                <value>
                    <fullName>Brennan</fullName>
                </value>
                <value>
                    <fullName>Jerry</fullName>
                </value>
                <value>
                    <fullName>Jeremy</fullName>
                </value>
                <value>
                    <fullName>Troy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_depositiontimezone.cls
@isTest
private class Test_depositiontimezone{
    
    static testMethod void myUnitTest3() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11:42 AM',Vidyo_Room__c='1');
        insert d;
    }
    static testMethod void myUnitTest8() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11 AM.',Vidyo_Room__c='2');
        insert d;
    }
    static testMethod void myUnitTest9() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11 P.M.',Vidyo_Room__c='3');
        insert d;
    }
    static testMethod void myUnitTest10() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11 PM.',Vidyo_Room__c='4');
        insert d;
    }
    static testMethod void myUnitTest11() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11:44',Vidyo_Room__c='5');
        insert d;
    }
    static testMethod void myUnitTest4() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11:42 A.M.',Vidyo_Room__c='6');
        insert d;
    }
    static testMethod void myUnitTest5() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11:42 A.M',Vidyo_Room__c='7');
        insert d;
    }
    static testMethod void myUnitTest7() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='9',Vidyo_Room__c='8');
        insert d;
    }
    static testMethod void myUnitTest6() {
        Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='21:42 P.M',Vidyo_Room__c='9');
        insert d;
        Deposition__c d1=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11:42 PM.',Vidyo_Room__c='10');
        insert d1;
    }
    static testMethod void myUnitTest() {
    Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11:42 PM',Vidyo_Room__c='11');
    insert d;
   
   
    }
    static testMethod void myUnitTest1() {
    Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Pecific',Deposition_Time__c='12:42',Vidyo_Room__c='17');
    insert d;
    Deposition__c d1=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11 AM',Vidyo_Room__c='18');
    insert d1;
    Deposition__c d11=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='5:42',Vidyo_Room__c='19');
    insert d11;
    d.Deposition_Time__c='03:40 PM';
    d.Time_Zone__c='Eastern';
    update d;
    d.Deposition_Time__c='03:40 a.M';
    d.Time_Zone__c='Mountain';
    update d;
    d.Deposition_Time__c='03:40 p.M';
    d.Time_Zone__c='Mountain';
    update d;
    }
    static testMethod void myUnitTest2() {
    Deposition__c d=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Pecific',Deposition_Time__c='12:42',Vidyo_Room__c='20');
    insert d;
    Deposition__c d1=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='11',Vidyo_Room__c='21');
    insert d1;
    Deposition__c d11=new Deposition__c(Deposition_Date__c=system.today(),Time_Zone__c='Central',Deposition_Time__c='5:42',Vidyo_Room__c='22');
    insert d11;
    d.Deposition_Time__c='9:40 A.M.';
    d.Deposition_Date__c=system.today();
    d.Time_Zone__c='Eastern';
    update d;
    d.Deposition_Time__c='9';
    d.Deposition_Date__c=system.today();
    d.Time_Zone__c='Eastern';
    update d;
    d.Deposition_Time__c='9 AM';
    d.Deposition_Date__c=system.today();
    d.Time_Zone__c='Eastern';
    update d;
    }
    }