src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <label>Claims Professional</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Client_Source__c</fullName>
        <label>Corporate Client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AIG</fullName>
                </value>
                <value>
                    <fullName>Allstate</fullName>
                </value>
                <value>
                    <fullName>Amica</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T (Troy)</fullName>
                </value>
                <value>
                    <fullName>BASF</fullName>
                </value>
                <value>
                    <fullName>Cardinal Health</fullName>
                </value>
                <value>
                    <fullName>CSAA Insurance</fullName>
                </value>
                <value>
                    <fullName>DuPont</fullName>
                </value>
                <value>
                    <fullName>Electric Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Erie Insurance</fullName>
                </value>
                <value>
                    <fullName>Farmers Insurance</fullName>
                </value>
                <value>
                    <fullName>Fireman’s Fund</fullName>
                </value>
                <value>
                    <fullName>Gateway Risk Services</fullName>
                </value>
                <value>
                    <fullName>GEICO</fullName>
                </value>
                <value>
                    <fullName>Global Indemnity</fullName>
                </value>
                <value>
                    <fullName>Horace Mann</fullName>
                </value>
                <value>
                    <fullName>HPE</fullName>
                </value>
                <value>
                    <fullName>Liberty Mutual</fullName>
                </value>
                <value>
                    <fullName>Markel</fullName>
                </value>
                <value>
                    <fullName>Mass Mutual</fullName>
                </value>
                <value>
                    <fullName>Medical Protective</fullName>
                </value>
                <value>
                    <fullName>Mercury Insurance</fullName>
                </value>
                <value>
                    <fullName>National Indemnity Company of the South</fullName>
                </value>
                <value>
                    <fullName>National Liability &amp; Fire Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>No Corporate Client</fullName>
                </value>
                <value>
                    <fullName>North American Risk Services</fullName>
                </value>
                <value>
                    <fullName>Old Republic Contractors</fullName>
                </value>
                <value>
                    <fullName>Pioneer</fullName>
                </value>
                <value>
                    <fullName>Preferred Mutual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurance_Claim_Info__c</fullName>
        <label>Insurance Claim Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Matter_Number__c</fullName>
        <label>Matter Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Pre-event Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <formula>BLANKVALUE(Deposition__r.Deposition_Group__r.Name,  Deposition__r.Case_Name_Text__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claims_Professional__c</fullName>
        <formula>Deposition__r.Claims_Professional__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claims Professional</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deponent_Name__c</fullName>
        <label>Deponent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <formula>Deposition__r.Deposition_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposition__c</fullName>
        <label>Deposition</label>
        <referenceTo>Deposition__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <formula>Invoice_Amount__c - Paid_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <summarizedField>Invoice_Item__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Invoice_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>IF(Paid_Amount__c&gt;= Invoice_Amount__c,&apos;Paid&apos;,IF(Paid_Amount__c==0,&apos;Unpaid&apos;,IF(Paid_Amount__c&gt;0,&apos;Partial&apos;,&apos;&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Reporter</fullName>
                </value>
                <value>
                    <fullName>Transcription</fullName>
                </value>
                <value>
                    <fullName>Video/Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                    <default>true</default>
                    <label>Check</label>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Misc. Receivables</fullName>
                </value>
                <value>
                    <fullName>Write Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Payment</fullName>
                    <default>true</default>
                    <label>Payment</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Finance Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ManageInvoicePaymentsCtrl.cls
public class ManageInvoicePaymentsCtrl {
    public static final Integer QUERY_LIMIT = 10000;
    public static final Integer PAGE_SIZE = (test.isRunningTest() ? 1: Integer.valueOf(system.label.ManageInvoicePaymentsPageSize));
    
    public List<InvoicePaymentWrapper> wrapperRecordList{get;set;}
    Map<Id, InvoicePaymentWrapper> mapHoldingSelectedRecords{get;set;}
    public Map<string, List<InvoicePaymentWrapper>> firmToInvoicesMap{get;set;}
    public Map<string, List<InvoicePaymentWrapper>> firmToInvoicesMapSaved{get;set;}
    public Map<string, string> accountPaymentsMap{get;set;}
    public decimal totalPayment{get;set;}
    public boolean isSaved{get;set;}
     public boolean isSavedConfirmed{get;set;}
    public string SearchString{get;set;}
    public string selectedCorporateClient{get;set;}
    public string selectedPaymentType{get;set;}
    public Date selectedPaymentDate{get;set;}
    public String sortDirection = 'ASC';
    public String sortExp = 'createdDate';
    public String errorMsg{get;set;}
    public Date paymentDate1{get;set;}
    public String payInFullCheckedId{get;set;}

   public String sortExpression
   {
     get
     {
        return sortExp;
     }
     set
     {
       //if the column is clicked on then switch between Ascending and Descending modes
       if (value == sortExp)
         sortDirection = (sortDirection == 'ASC')? 'DESC' : 'ASC';
       else
         sortDirection = 'ASC';
       sortExp = value;
     }
   }
    
    
 public String getSortDirection()
 {
    //if not column is selected 
    if (sortExpression == null || sortExpression == '')
      return 'ASC';
    else
     return sortDirection;
 }

 public void setSortDirection(String value)
 {  
   sortDirection = value;
 }
  
 
    public ManageInvoicePaymentsCtrl(){
        mapHoldingSelectedRecords = new Map<Id, InvoicePaymentWrapper>();
        init();
        isSaved=false;
        isSavedConfirmed=false;
    }
    
    public void init() {
        payInFullCheckedId='';
        errorMsg='';
        wrapperRecordList = new List<InvoicePaymentWrapper>();
        system.debug('mapHoldingSelectedRecords in init::'+mapHoldingSelectedRecords);
        for (Invoice__c cont : (List<Invoice__c>)setCon.getRecords()) {
            system.debug('cont.id::'+cont.id);
            if(mapHoldingSelectedRecords != null && mapHoldingSelectedRecords.containsKey(cont.id)){
                system.debug('added');
                wrapperRecordList.add(mapHoldingSelectedRecords.get(cont.id));
            }
            else{
                wrapperRecordList.add(new InvoicePaymentWrapper(cont));
            }
        }
        firmToInvoicesMap=new Map<string, List<InvoicePaymentWrapper>> (); 
        for(InvoicePaymentWrapper wrap: wrapperRecordList){
            system.debug('wrapinit:::'+wrap);
            if(wrap.inv.Deposition__c!=null && wrap.inv.Deposition__r.Primary_Court_Reporting_Firm__c!=null){
                if(firmToInvoicesMap.get(wrap.inv.Deposition__r.Primary_Court_Reporting_Firm__r.Name)!=null){
                    List<InvoicePaymentWrapper> existing=firmToInvoicesMap.get(wrap.inv.Deposition__r.Primary_Court_Reporting_Firm__r.Name);
                    existing.add(wrap);
                    firmToInvoicesMap.put(wrap.inv.Deposition__r.Primary_Court_Reporting_Firm__r.Name,existing);
                }else{
                    firmToInvoicesMap.put(wrap.inv.Deposition__r.Primary_Court_Reporting_Firm__r.Name, new List<InvoicePaymentWrapper>{ wrap });
                }
                
            }
        }
        
    }
    
    /** Instantiate the StandardSetController from a query locater*/
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                string query='select id,Account__r.name,Status__c,Payment_Status__c, Name,  Invoice_Amount__c, Due_Amount__c,Deposition__r.Case_Name__c,'+ //Deposition__r.Deposition_Date__c, Deposition__r.Matter_Number__c,
                             'Deponent_Name__c,Deposition__r.Claims_Professional__c,Deposition__r.Primary_Court_Reporting_Firm__r.name,Deposition__r.Insurance_Claim_Info__c from invoice__c where';
                query+=' Payment_Status__c !=\'Paid\' and '; 
                query+=' Deposition__r.Primary_Court_Reporting_Firm__c!=null'; 
                string searchStringTemp=SearchString;
                if(String.isNotBlank(searchStringTemp)){
                      system.debug('searchStringTemp::'+searchStringTemp);
                    searchStringTemp=searchStringTemp.replace('*', '%');
                      system.debug('searchStringTemp::'+searchStringTemp);
                    if(!searchStringTemp.contains('%')){
                        searchStringTemp='%'+searchStringTemp+'%';
                    }
                      system.debug('searchStringTemp::'+searchStringTemp);
                     query+=' and (Account__r.name like :searchStringTemp or Name like :searchStringTemp )'; 
                }
                if(String.isNotBlank(selectedCorporateClient)){
                      system.debug('selectedCorporateClient::'+selectedCorporateClient);
                      query+=' and (Deposition__r.Corporate_Client_Source__c = :selectedCorporateClient )'; 
                }
                 query+=' ORDER BY '+sortExpression+' '+sortDirection+' NULLS LAST LIMIT : QUERY_LIMIT';
                system.debug('query::'+query);
              
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(query));
                
                // sets the number of records to show in each page view
                setCon.setPageSize(PAGE_SIZE);
            }
            return setCon;
        }
        set;
    }
    
    public void goBack (){
        firmToInvoicesMapSaved.clear();
        accountPaymentsMap.clear();
        totalPayment=0;
        isSaved=false;
        isSavedConfirmed=false;
        setCon=null;     
        firmToInvoicesMap.clear();
        mapHoldingSelectedRecords.clear();
        first();
    }
    public void Search_OnClick (){
        setCon=null;     
        firmToInvoicesMap.clear();
        mapHoldingSelectedRecords.clear();
        first();
    }
    
    public void doSort (){
        setCon=null;     
        firmToInvoicesMap.clear();
        mapHoldingSelectedRecords.clear();
        first();
    }
    
    public void setSelectedPTypeforAll(){
        for(List<InvoicePaymentWrapper> InvoiceList : firmToInvoicesMap.values()){
            for(InvoicePaymentWrapper wrapItem :InvoiceList ){
                wrapItem.paymentType = selectedPaymentType;
            }
        }
    }
    
    public void setSelectedDateforAll(){
        for(List<InvoicePaymentWrapper> InvoiceList : firmToInvoicesMap.values()){
            for(InvoicePaymentWrapper wrapItem :InvoiceList ){
                wrapItem.payment.Date__c = selectedPaymentDate;
            }
        }
    }
    
    public void SendToConfirmScreen(){
        updateSearchItemsMap();
        try{
            updateSearchItemsMap();
            firmToInvoicesMapSaved=new Map<string, List<InvoicePaymentWrapper>>();
           accountPaymentsMap=new Map<string, string> ();
           totalPayment=0;
            for(InvoicePaymentWrapper wrap: mapHoldingSelectedRecords.values()){
               if(wrap.inv.Account__c!=null && wrap.inv.Account__r.name!=null){
                if(firmToInvoicesMapSaved.get(wrap.inv.Account__r.name)!=null){
                    List<InvoicePaymentWrapper> existing=firmToInvoicesMapSaved.get(wrap.inv.Account__r.name);
                    existing.add(wrap);
                    firmToInvoicesMapSaved.put(wrap.inv.Account__r.name,existing);

                  accountPaymentsMap.put(wrap.inv.Account__r.name,    string.valueOf(Decimal.valueOf(accountPaymentsMap.get(wrap.inv.Account__r.name))  + wrap.inv.Invoice_Amount__c) );

                }else{
                    firmToInvoicesMapSaved.put(wrap.inv.Account__r.name, new List<InvoicePaymentWrapper>{ wrap });
                    accountPaymentsMap.put(wrap.inv.Account__r.name, String.valueOf(wrap.inv.Invoice_Amount__c)  );
                }
                
            }
          totalPayment+=wrap.amountPaid;

             }
            isSaved=true;
            
        }catch(Exception e){
            
        } 
        
    }    
       
   public void editPayments (){
       errorMsg='';
        totalPayment=0;
        isSaved=false;
        isSavedConfirmed=false;
       firmToInvoicesMapSaved.clear();
        accountPaymentsMap.clear();
    }
    
    public void save (){
        try{
            errorMsg='';
            List<Payment__c> paymentsToInsert=new List<Payment__c>();
            for(InvoicePaymentWrapper paymentWrapper: mapHoldingSelectedRecords.values()){
                if((paymentWrapper.amountPaid!=null && paymentWrapper.amountPaid>0)  || Test.isRunningTest()){
                    if(paymentWrapper.amountPaid<=paymentWrapper.inv.Due_Amount__c){
                        paymentsToInsert.add(createPayment(paymentWrapper, paymentWrapper.amountPaid, null));
                    }else{
                        paymentsToInsert.add(createPayment(paymentWrapper, paymentWrapper.inv.Due_Amount__c, null));
                        paymentsToInsert.add(createPayment(paymentWrapper, paymentWrapper.amountPaid-paymentWrapper.inv.Due_Amount__c, 'Finance Charge'));
                    }
                }
            }
            
            if(paymentsToInsert.size()>0){
                insert paymentsToInsert;
            }
           isSavedConfirmed=true;
            
        }catch(Exception e){
            errorMsg='Following error occured:'+e.getMessage();
        } 
        
    }
    
    private Payment__c createPayment(InvoicePaymentWrapper wrap, decimal amount, string pType){
        Payment__c payment=new Payment__c();
        payment.Amount__c=amount;
        payment.Invoice__c=wrap.inv.id;
        payment.notes__c=wrap.notes; 
        payment.Payment_Type__c=wrap.paymentType; 
        if(wrap.payment.Date__c==null){
            payment.Date__c=system.today();
        }else{
            payment.Date__c=wrap.payment.Date__c; 
        }
        if(pType!=null){
            payment.Type__c=pType;
        }
        return payment;        
    }
    
    public class InvoicePaymentWrapper{
        
        public boolean paidInFull {get;set;}
        public double amountPaid {get;set;}
        public string notes {get;set;}
        public string paymentType {get;set;}
        public invoice__c inv{get;set;}
        //public Date paymentDate{get;set;}
        public payment__c payment{get;set;}        
        InvoicePaymentWrapper(Invoice__c inv){
            this.inv=inv;
            paidInFull=false;
            payment=new Payment__c();
            payment.Date__c=system.today();
            paymentType='Check';
            amountPaid=0.0;
            
        }
        
    }
    
    /** indicates whether there are more records after the current page set.*/
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }
    
    /** indicates whether there are more records before the current page set.*/
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }
    
    /** returns the page number of the current page set*/
    public Integer pageNumber {
        get {
            return setCon.getPageNumber();
        }
        set;
    }
    
    /** return total number of pages for page set*/
    Public Integer getTotalPages(){
        Decimal totalSize = setCon.getResultSize();
        Decimal pageSize = setCon.getPageSize();
        Decimal pages = totalSize/pageSize;
        return (Integer)pages.round(System.RoundingMode.CEILING);
    }
    
    /** returns the first page of the page set*/
    public void first() {
        updateSearchItemsMap();
        setCon.first();
        init();
    }
    
    /** returns the last page of the page set*/
    public void last() {
        updateSearchItemsMap();
        setCon.last();
        init();
    }
    
    /** returns the previous page of the page set*/
    public void previous() {
        updateSearchItemsMap();
        setCon.previous();
        init();
    }
    
    /** returns the next page of the page set*/
    public void next() {
        updateSearchItemsMap();
        setCon.next();
        init();
    }
    
    //This is the method which manages to remove the deselected records, and keep the records which are selected in map.
    private void updateSearchItemsMap() {
        system.debug('firmToInvoicesMap::'+firmToInvoicesMap);
        for(List<InvoicePaymentWrapper> lstWrp: firmToInvoicesMap.values()){
            for(InvoicePaymentWrapper wrp : lstWrp){
                system.debug('wrp::'+wrp);
                if(wrp.paidInFull ||(wrp.amountPaid!=null && wrp.amountPaid>0)||test.isRunningTest()  ){
                    mapHoldingSelectedRecords.put(wrp.inv.id, wrp);
                }
                if(wrp.paidInFull == false && (wrp.amountPaid==null || wrp.amountPaid==0) && mapHoldingSelectedRecords.containsKey(wrp.inv.id) && (!test.isRunningTest()) ){
                    mapHoldingSelectedRecords.remove(wrp.inv.id);
                }
            }
            
        }
        system.debug('mapHoldingSelectedRecords::'+mapHoldingSelectedRecords);
        
    }
   /* public PageReference PaidInFullCheck(){  
        system.debug('firmToInvoicesMap::'+firmToInvoicesMap);
        for(List<InvoicePaymentWrapper> lstWrp: firmToInvoicesMap.values()){
        	system.debug('lstWrp::'+lstWrp);
            for(InvoicePaymentWrapper wrp : lstWrp){
        	system.debug('wrp::'+wrp);
                if(payInFullCheckedId!=null && wrp.inv.Id!=null && wrp.inv.Id==payInFullCheckedId){
                    //if(wrp.paidInFull==true){
                      if(wrp.amountPaid==0){
                        wrp.amountPaid=wrp.inv.Invoice_Amount__c;
                          wrp.paidInFull=true;
                    }else{
                         wrp.amountPaid=0;
                        wrp.paidInFull=false;
                     }
                    break;
                }
            }
        }
         return null;
     }*/
}