src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCommunitiesAddAttendeeToDeposition.cls
/**************************************************
                Name        : TestCommunitiesAddAttendeeToDeposition
                Author      : Rajendra Rathore
                Purpose     : Test class for CommunitiesAddAttendeeToDepositionCntrl Apex class
                Created Date: 20 NOV 2016
                
                Modification History:
*****************************************************/
@isTest
public  class TestCommunitiesAddAttendeeToDeposition{
  @isTest
  private static void Test_AddAttendeeToDeposition(){
       Deposition__c  depo=TestUtility.createDeposition(null);
       depo.Case_Name__c = 'Test Case';
       insert depo;
       system.runAs(TestUtility.createCommunityUser()){
           Cookie cookie = new Cookie('firmCookie', 'NextGen Reporting', null, -1, false);
           ApexPages.currentPage().setCookies(new Cookie[]{cookie});
           ApexPages.StandardController SCont = new ApexPages.StandardController(depo);
           ApexPages.currentPage().getParameters().put('id', depo.Case_Name__c);
           PortalExtn ext = new PortalExtn (SCont);
           ext.saveDeposition();
           CommunitiesAddAttendeeToDepositionCntrl cntrl = new CommunitiesAddAttendeeToDepositionCntrl ();
           cntrl.searchDepositions();
           cntrl.lstDepositions = new List<Deposition__c>();
           cntrl.lstDepositions.add(depo);
           cntrl.addToMyAccount();
           for(Deposition__c dep : cntrl.lstDepositions){
               //dep.IsDeleted = true;
           }
           cntrl.addToMyAccount();
       }
  }
}