src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestDepositionClone.cls
@isTest
public class TestDepositionClone {

    public static void descObj() {
            
            List<Deposition__c> depositions = new List<Deposition__c>{};
            
            
            String companyString;

            Deposition__c testDeposition = new Deposition__c(Case_Name__c ='Test1');
            depositions.add(testDeposition);
            insert depositions;
            
            companyString = depositions[0].id;
            
        
             ApexPages.StandardController sc = new ApexPages.StandardController(depositions[0]);
             DepositionCloneCtrl testdeposi = new DepositionCloneCtrl(sc);
             testdeposi.onsave();
             testdeposi.recCount=0;
             testdeposi.onsave();
             testdeposi.recCount=2;
             testdeposi.onsave();
        
        
        }
        
        static testmethod void testDepositionsClone(){
            descObj();
        }
    
    
    

}