src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Corporate_Client_Source__c</fullName>
        <label>Corporate Client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AIG</fullName>
                </value>
                <value>
                    <fullName>Allstate</fullName>
                </value>
                <value>
                    <fullName>Amica</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T (Troy)</fullName>
                </value>
                <value>
                    <fullName>BASF</fullName>
                </value>
                <value>
                    <fullName>Cardinal Health</fullName>
                </value>
                <value>
                    <fullName>CSAA Insurance</fullName>
                </value>
                <value>
                    <fullName>DuPont</fullName>
                </value>
                <value>
                    <fullName>Electric Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Erie Insurance</fullName>
                </value>
                <value>
                    <fullName>Farmers Insurance</fullName>
                </value>
                <value>
                    <fullName>Fireman’s Fund</fullName>
                </value>
                <value>
                    <fullName>Gateway Risk Services</fullName>
                </value>
                <value>
                    <fullName>GEICO</fullName>
                </value>
                <value>
                    <fullName>Global Indemnity</fullName>
                </value>
                <value>
                    <fullName>Horace Mann</fullName>
                </value>
                <value>
                    <fullName>HPE</fullName>
                </value>
                <value>
                    <fullName>Liberty Mutual</fullName>
                </value>
                <value>
                    <fullName>Markel</fullName>
                </value>
                <value>
                    <fullName>Mass Mutual</fullName>
                </value>
                <value>
                    <fullName>Medical Protective</fullName>
                </value>
                <value>
                    <fullName>Mercury Insurance</fullName>
                </value>
                <value>
                    <fullName>National Indemnity Company of the South</fullName>
                </value>
                <value>
                    <fullName>National Liability &amp; Fire Insurance Co.</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>No Corporate Client</fullName>
                </value>
                <value>
                    <fullName>North American Risk Services</fullName>
                </value>
                <value>
                    <fullName>Old Republic Contractors</fullName>
                </value>
                <value>
                    <fullName>Pioneer</fullName>
                </value>
                <value>
                    <fullName>Preferred Mutual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposition_Date__c</fullName>
        <label>Deposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Court_Reporting_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Reporting Brand</label>
        <referenceTo>Firm__c</referenceTo>
        <relationshipLabel>Depositions</relationshipLabel>
        <relationshipName>Depositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDepositionAssignmentCntrl.cls
/**
                                    Name             : TestDepositionAssignmentCntrl
                                    Date             : 11 Jan 2016
                                    Descripition     : Test Class for DepositionAssignmentCntrl class.
*/                                   
@isTest
private class TestDepositionAssignmentCntrl{

    @isTest
    private static void Test_DepositionAssignmentCntrl() {
        /*Account account = TestUtility.createAccount('Test Account','Court Reporting');
        insert account;
        
        Deposition__c deposition = TestUtility.createDeposition(account.id);
        deposition.Event_Location__c= 'His Prison Cell Folsom, CA 94123';
        deposition.Corporate_Client_Source__c = 'Allstate';
        deposition.Deposition_Date__c = sytem.today();
        insert deposition;
        */
        TestUtils tUtils = new TestUtils();
        Account account = tUtils.insertAccount();
        Deposition__c deposition = tUtils.createDeposition();
        Contact contact = tUtils.insertContact(account.ID);
        Firm__c firm = new Firm__c(Name='NextGen Reporting');
        insert firm;
        deposition.Deposition_Date__c = System.today()+1;
        deposition.Primary_Court_Reporting_Firm__c =firm.id;
        update deposition;
        DepositionAssignmentCntrl cntrl = new DepositionAssignmentCntrl();
        
        for(DepositionAssignmentCntrl.DepositionModel depModel : cntrl.lstTomorrowDepositions){
            depModel.reporter.Court_Reporter__c  = depModel.videographer.Videographer__c = contact.id;
        }
        cntrl.saveDepositions();
        
        Test.StartTest();
           cntrl = new DepositionAssignmentCntrl(); 
        Test.StopTest();
    }


}