src/objects/Deposition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name/Caption</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deposition</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}-prelaunch</displayFormat>
        <label>Deposition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depositions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestPortalExtn.cls
/**************************************************
                Name        : TestPortalExtn
                Author      : Rajendra Rathore
                Purpose     : Test class for PortalExtn Apex class
                Created Date: 10 JULY 2016
                
                Modification History:
*****************************************************/
@isTest
public  class TestPortalExtn{
  @isTest
  private static void Test_PortalExtn(){
       Deposition__c  depo=TestUtility.createDeposition(null);
       depo.Case_Name__c = 'Test Case';
       insert depo;
       PageReference pageRef = new PageReference('/apex/Portal');
       ApexPages.currentPage().getParameters().put('id', depo.id);
       Test.setCurrentPage(pageRef);
       
       system.runAs(TestUtility.createCommunityUser()){
           Cookie cookie = new Cookie('firmCookie', 'NextGen Reporting', null, -1, false);
           ApexPages.currentPage().setCookies(new Cookie[]{cookie});
           ApexPages.StandardController SCont = new ApexPages.StandardController(depo);
           
           PortalExtn ext = new PortalExtn (SCont);
           ext.depSearchText = depo.Case_Name__c;
           ext.searchDepositionsRecord();
           ext.saveDeposition();
           ext.confirmDeposition();
       }
  }
}