src/objects/Firm__c.object
<CustomObject>
    <fields>
        <fullName>Community_Footer__c</fullName>
        <label>Community Footer</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Community_Header__c</fullName>
        <label>Community Header</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Production_Email_Address__c</fullName>
        <label>Production Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Scheduling_Email_Address__c</fullName>
        <label>Scheduling Email Address</label>
        <type>Email</type>
    </fields>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FirmInfoCntrl.cls
/**************************************************
                Name        : FirmInfoCntrl
                Author      : Rajendra Rathore
                Purpose     : That class are used for getting firm information.
                Created Date: 09 JUNE 2016
                
                Modification History:
*****************************************************/
public class FirmInfoCntrl{
    public FirmInfoCntrl(){   
    }
    public Firm__c getFirm(){
        Firm__c firm = new Firm__c();
        String firmName = '';
        Cookie firmCookie = ApexPages.currentPage().getCookies().get('firmCookie');
        
        firmName = 'NextGen Reporting';
        if(firmCookie != null && firmCookie.getValue()!= null){
            firmName = firmCookie.getValue(); 
            
        }
       
        List<Firm__c>lstFirms = [select Id,Name,Phone__c,Community_Header__c,Community_Footer__c,Scheduling_Email_Address__c,Production_Email_Address__c
                                   From Firm__c WHERE Name =:firmName];
        if(lstFirms.size()>0){
            firm = lstFirms[0];
        }
        
        return firm;
    }
    
}