src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Sheet__c.object
<CustomObject>
    <label>Rate Sheet</label>
    <nameField>
        <label>Rate Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Sheet_Item__c.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <label>Default</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Default Original</fullName>
                </value>
                <value>
                    <fullName>Default Copy</fullName>
                </value>
                <value>
                    <fullName>Default Exhibit</fullName>
                </value>
                <value>
                    <fullName>Default Expedite</fullName>
                </value>
                <value>
                    <fullName>Default Video</fullName>
                </value>
                <value>
                    <fullName>Default Realtime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Rate Sheet Items</relationshipLabel>
        <relationshipName>Rate_Sheet_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Rate Sheet Items</relationshipLabel>
        <relationshipName>Rate_Sheet_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Units_of_Measure__c</fullName>
        <label>Units of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Per Page</fullName>
                </value>
                <value>
                    <fullName>Per Transcript</fullName>
                </value>
                <value>
                    <fullName>Per Hour</fullName>
                </value>
                <value>
                    <fullName>Per Person</fullName>
                </value>
                <value>
                    <fullName>Per Job</fullName>
                </value>
                <value>
                    <fullName>Per Day</fullName>
                </value>
                <value>
                    <fullName>Per Half Day</fullName>
                </value>
                <value>
                    <fullName>Per Kit</fullName>
                </value>
                <value>
                    <fullName>Per Session</fullName>
                </value>
                <value>
                    <fullName>Per Disk</fullName>
                </value>
                <value>
                    <fullName>Per Mile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rate Sheet Item</label>
    <nameField>
        <displayFormat>RSI-{00000}</displayFormat>
        <label>Rate Sheet Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Sheet Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RateSheetItemsDetailsCntrl.cls
public class RateSheetItemsDetailsCntrl{
    public string rateSheetRecordId{get;set;}
    public List<Rate_Sheet_Item__c>getRateSheetItems(){
        return [select id,Item__c,Item__r.name,Price__c,Units_of_Measure__c From Rate_Sheet_Item__c 
                WHERE Rate_Sheet__c=:rateSheetRecordId 
                ORDER By Default__c DESC NULLS Last,  Item__r.Name ASC];
    }
    
    public Firm__c getFrimRecord(){
         List<user>lstUsers = [select id,Default_CR_Firm__c From User WHERE Id=:UserInfo.getUserId()];
         if(lstUsers.size()>0){
           return DepositionHelper.fetchFirm(lstUsers[0].Default_CR_Firm__c );
           
         }
         return new Firm__c ();
    }
     
}