src/objects/Firm__c.object
<CustomObject>
    <label>Firm</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Past_Due_Bucket__c</fullName>
        <formula>IF( Days_Past_Due__c &lt;=30,&apos;0-30&apos;,
IF(Days_Past_Due__c &lt;=60,&apos;30-60&apos;,
IF(Days_Past_Due__c &lt;=90,&apos;60-90&apos;,
IF(Days_Past_Due__c &lt;=120,&apos;90-120&apos;,
IF(Days_Past_Due__c &lt;=150,&apos;120-150&apos;,
IF(Days_Past_Due__c &lt;=180,&apos;150-180&apos;,

&apos;Over 180&apos;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Past Due (Bucket)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <formula>Invoice_Amount__c - Paid_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>IF(Paid_Amount__c&gt;= Invoice_Amount__c,&apos;Paid&apos;,IF(Paid_Amount__c==0,&apos;Unpaid&apos;,IF(Paid_Amount__c&gt;0,&apos;Partial&apos;,&apos;&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Reporter</fullName>
                </value>
                <value>
                    <fullName>Transcription</fullName>
                </value>
                <value>
                    <fullName>Video/Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SelectFirmExtn.cls
public class SelectFirmExtn {
    public List<SelectOption>lstFirms{get;set;}
    public String selectedFirm{get;set;}
    public Account accnt = new Account();
    public SelectFirmExtn(ApexPages.StandardController controller) {
        lstFirms = new List<SelectOption>();
        accnt = (account)controller.getRecord();
        //User usr = [select Default_CR_Firm__c FROM User WHERE Id=:Userinfo.getUserid()];
        for(Firm__c firm: [select id,Name
                                 FROM Firm__c ]){
            lstFirms.add(new SelectOption(firm.id,firm.Name));
            if(firm.Name =='Lexitas')
                selectedFirm = firm.id;
        }
    }
    public void updateAccountDueAmountsFromInvoice(){
        try{
            accnt.X0_30__c = 0;
            accnt.X30_60__c= 0;
            accnt.X60_90__c= 0;
            accnt.X90_120__c= 0;
            accnt.X120_150__c = 0;
            accnt.X150_180__c= 0;
            accnt.Over_180__c= 0;
            for(Invoice__c invoice:[select Id,Due_Amount__c,Days_Past_Due_Bucket__c FROM Invoice__c WHERE 
                                 Type__c='Client' AND  Account__c =:accnt.id AND Due_Amount__c >=0 AND Status__c='Valid'
                                 AND Payment_Status__c!='Paid']){
                if(invoice.Days_Past_Due_Bucket__c == '0-30')
                    accnt.X0_30__c += invoice.Due_Amount__c;
                else if(invoice.Days_Past_Due_Bucket__c == '30-60')
                    accnt.X30_60__c+= invoice.Due_Amount__c;
                else if(invoice.Days_Past_Due_Bucket__c == '60-90')
                    accnt.X60_90__c+= invoice.Due_Amount__c;
                else if(invoice.Days_Past_Due_Bucket__c == '90-120')
                    accnt.X90_120__c+= invoice.Due_Amount__c;
                else if(invoice.Days_Past_Due_Bucket__c == '120-150')
                    accnt.X120_150__c += invoice.Due_Amount__c;
                else if(invoice.Days_Past_Due_Bucket__c == '150-180')
                    accnt.X150_180__c+= invoice.Due_Amount__c;
                else if(invoice.Days_Past_Due_Bucket__c == 'Over 180')
                    accnt.Over_180__c+= invoice.Due_Amount__c;
                
            }
            update accnt;
        }Catch(Exception e){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
        }
    }

}