src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <formula>Invoice_Amount__c - Paid_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RestInvoiceAmountDue.cls
@RestResource(urlMapping='/invoice/amountdue/*')
global with sharing class RestInvoiceAmountDue {
    
    // https://instance.salesforce.com/services/apexrest/invoice/amountdue/

    @HttpGet
    global static Decimal doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String invoiceNo = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        List<Invoice__c> invoices = [SELECT Id,name, Due_Amount__c FROM Invoice__c WHERE Name=:invoiceNo ];
        if(!invoices.isEmpty()){
            return invoices[0].Due_Amount__c!=null ? invoices[0].Due_Amount__c:0;
        }
        return 0;
    }
    
}