src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CloneInvoiceExtn.cls
public class CloneInvoiceExtn {
    ApexPages.StandardController sc;
    public CloneInvoiceExtn(ApexPages.StandardController controller) {
        sc = controller;
    }
    public PageReference cloneInvoiceRecord(){
        Savepoint mysavepointt = Database.setSavepoint();
        try{
            Sobject clonedRec = CloneHelper.cloneObject('Invoice__c', sc.getId(), 'Invoice__c', 'Invoice_Item__c');
            return new PageReference ('/'+clonedRec.id);
        }Catch(Exception e){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Fatal,e.getMessage()));
             Database.rollback(mysavepointt);
             return null;
        }
    }
}