src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>After_Due_Date_Invoice_Amount__c</fullName>
        <formula>Invoice_Amount__c +((Invoice_Amount__c *15)/100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Late Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <formula>Invoice_Amount__c - Paid_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Reporter</fullName>
                </value>
                <value>
                    <fullName>Transcription</fullName>
                </value>
                <value>
                    <fullName>Video/Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                    <default>true</default>
                    <label>Check</label>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Misc. Receivables</fullName>
                </value>
                <value>
                    <fullName>Write Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Payment</fullName>
                    <default>true</default>
                    <label>Payment</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Finance Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreatePaymentExtension.cls
public class CreatePaymentExtension {
    public Payment__c payment;
    public Payment__c payment2{get;set;}
    private ApexPages.StandardController stdCtrl;
    public boolean extraPayment{get;set;}
    public String selectedOption {get;set;}
    public String errorMsg {get;set;}
    public decimal extraAmount{get;set;}
    public decimal dueAmount{get;set;}
    public boolean payment2Invoice{get;set;}
    public String afterDueDateMsg {get;set;}
    
    
    public CreatePaymentExtension(ApexPages.StandardController stdController) {
        this.payment = (Payment__c)stdController.getRecord();
        stdCtrl=stdController;
        extraAmount=0;
        afterDueDateMsg='';
    }
    
    public List<SelectOption> getOptionsToShow() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('option1','Edit the payment'));
        options.add(new SelectOption('option2','Add this overpayment as a finance charge'));
        options.add(new SelectOption('option3','Apply the credit to another invoice'));
        
        return options;
    }
    
    public pagereference Save2(){
        List<Invoice__c> lst= [select id,Due_Amount__c,After_Due_Date_Invoice_Amount__c from  Invoice__c where id=:payment.Invoice__c ];
        if(lst.size()>0 && payment.Amount__c!=null && payment.Amount__c!=0 && lst[0].Due_Amount__c<payment.Amount__c  ){
            extraPayment=true; 
            extraAmount=payment.Amount__c-lst[0].Due_Amount__c;
            dueAmount=lst[0].Due_Amount__c;
            
            if(payment.Amount__c==lst[0].After_Due_Date_Invoice_Amount__c){
                afterDueDateMsg='This matches the amount of the late payment penalty on the invoice.';
            }else{
                afterDueDateMsg='This does not match the amount of the late payment penalty on the invoice. The late payment amount on this invoice is '+ lst[0].After_Due_Date_Invoice_Amount__c;
            }
            return null;
        }else{
            return stdCtrl.save();
            
        }
        
    }
    
    public pagereference confirm(){
        system.debug('selectedOption::'+selectedOption);
        payment2Invoice=false;
        if(string.isBlank(selectedOption)){
            errorMsg='please select at least one option.';
        }else{
            errorMsg='';
            afterDueDateMsg='';
            if(selectedOption=='option1'){
                extraPayment=false;
                return null;
            }else if(selectedOption=='option2'){
                payment__c p1=new payment__c(Amount__c=extraAmount, Invoice__c=payment.Invoice__c, 
                                             Date__c=system.today(), Type__c='Finance Charge', Payment_Type__c=payment.Payment_Type__c);
                insert p1;
                payment.Amount__c=dueAmount;
                return stdCtrl.save();                
            }else if(selectedOption=='option3'){
                payment2=new payment__c(Amount__c=extraAmount,  
                                             Date__c=system.today(),Payment_Type__c=payment.Payment_Type__c);
                payment.Amount__c=dueAmount;
                payment2Invoice=true;
                return null;
            }
        }
		return null;        
    }
    
    public pagereference confirm2(){
        insert payment2;
        return stdCtrl.save();  
    }
}