src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Appearance Fee</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Exhibits</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Rate__c</fullName>
        <label>Commission Rate</label>
        <precision>4</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Reporter</fullName>
                </value>
                <value>
                    <fullName>Video/Tech</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rate Sheet</label>
    <nameField>
        <label>Rate Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Sheet_Item__c.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <label>Default</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Default Original</fullName>
                </value>
                <value>
                    <fullName>Default Copy</fullName>
                </value>
                <value>
                    <fullName>Default Exhibit</fullName>
                </value>
                <value>
                    <fullName>Default Expedite</fullName>
                </value>
                <value>
                    <fullName>Default Video</fullName>
                </value>
                <value>
                    <fullName>Default Realtime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Text__c</fullName>
        <description>Text to include on every invoice</description>
        <label>Invoice Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Rate Sheet Items</relationshipLabel>
        <relationshipName>Rate_Sheet_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Rate Sheet Items</relationshipLabel>
        <relationshipName>Rate_Sheet_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All States</fullName>
                    <default>true</default>
                    <label>All States</label>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT( Item__r.Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units_of_Measure__c</fullName>
        <label>Units of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Per Page</fullName>
                </value>
                <value>
                    <fullName>Per Transcript</fullName>
                </value>
                <value>
                    <fullName>Per Hour</fullName>
                </value>
                <value>
                    <fullName>Per Person</fullName>
                </value>
                <value>
                    <fullName>Per Job</fullName>
                </value>
                <value>
                    <fullName>Per Day</fullName>
                </value>
                <value>
                    <fullName>Per Half Day</fullName>
                </value>
                <value>
                    <fullName>Per Kit</fullName>
                </value>
                <value>
                    <fullName>Per Session</fullName>
                </value>
                <value>
                    <fullName>Per Disk</fullName>
                </value>
                <value>
                    <fullName>Per Mile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rate Sheet Item</label>
    <nameField>
        <displayFormat>RSI-{00000}</displayFormat>
        <label>Rate Sheet Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Sheet Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RateSheetCloneExtn.cls
/**
                        Name             : RateSheetCloneExtn
                        Date             : 05/11/2015
                        Description      : That class is used by RateSheetClone VF page for clone
                                            Rate sheet record as well as their child rate sheet item records
*/                                             
public class RateSheetCloneExtn {
    //added an instance varaible for the standard controller
    private ApexPages.StandardController controller {get; set;}
     // add the instance for the variables being passed by id on the url
    public  Rate_Sheet__c rateSheet {get;set;}
    // set the id of the record that is created -- ONLY USED BY THE TEST CLASS
    public ID newRecordId {get;set;}

    // initialize the controller
    public RateSheetCloneExtn(ApexPages.StandardController sc) {

        //initialize the stanrdard controller
        this.controller = sc;
        // load the current record
        List<Rate_Sheet__c>lstRateSheets = [select Id, Name,Notes__c,Commission_Rate__c,Type__c
                                             from Rate_Sheet__c where id = :sc.getId()];
        if(lstRateSheets.size()>0){
            rateSheet =lstRateSheets[0].clone(false);
            rateSheet.OwnerId= UserInfo.getUserId();
        }
    }

    // method called from the VF's action attribute to clone the po
    public PageReference cloneWithItems() {

         // setup the save point for rollback
         Savepoint sp = Database.setSavepoint();
         try {
             if(!Test.isRunningTest()){
                upsert rateSheet;
            }
            // set the id of the new rate sheet created for testing
            newRecordId = rateSheet.id;

             // copy over the line items
             List<Rate_Sheet_Item__c> lstRateSheetItems = new List<Rate_Sheet_Item__c>();
             for (Rate_Sheet_Item__c item : [Select id,name,Item__c,Notes__c,Invoice_Text__c,
                                            Price__c,Units_of_Measure__c,Default__c,State__c
                                            From Rate_Sheet_Item__c 
                                            WHERE   Rate_sheet__c=:controller.getId() ]) {
                  Rate_Sheet_Item__c newRateSheetItem = item.clone(false);
                  newRateSheetItem.Rate_Sheet__c = rateSheet.id;
                  lstRateSheetItems.add(newRateSheetItem);
             }
             insert lstRateSheetItems;
         } catch (Exception e){
             // roll everything back in case of error
             system.debug('***** exception '+e);
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
         }

        return new PageReference('/'+rateSheet.id);
    }

}