src/objects/Promo_Email__c.object
<CustomObject>
    <description>Object to manage customized email blasts to specific clients on specific cases.</description>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Remote</fullName>
                </value>
                <value>
                    <fullName>Discovery Alert from CL</fullName>
                    <default>true</default>
                    <label>Discovery Alert from CL</label>
                </value>
                <value>
                    <fullName>Plaintiff Special Offer</fullName>
                </value>
                <value>
                    <fullName>Multi-party IP Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Promo Emails</relationshipLabel>
        <relationshipName>Promo_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date1__c</fullName>
        <formula>DATEVALUE(   CreatedDate )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_After_Created_Date__c</fullName>
        <formula>Today()-Created_Date1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days After Created Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Send_Promo_Email__c</fullName>
        <formula>IF(TEXT(Case_Type__c)==&apos;Multi-party IP Case&apos;,true, NOT(OR( Contact__r.Attendee_Count__c &gt;0 , TEXT(Contact__r.VIP_Level__c)=&apos;VIP 1&apos;,TEXT( Contact__r.Account.VIP_Level__c) =&apos;VIP 1&apos;, Contact__r.HasOptedOutOfEmail )))</formula>
        <label>Send Promo Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Promo Email</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Promo Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleBatchSendPromoEmails.cls
global with sharing class ScheduleBatchSendPromoEmails implements Schedulable{
     global void execute(SchedulableContext sc)
     {
            String query='Select End_Date__c, Date__c,contact__r.email,Days_After_Created_Date__c ,'+
                         'Created_Date1__c From Promo_Email__c  where Send_Promo_Email__c=true AND  End_Date__c!=null and'+
                         ' End_Date__c>TODAY  AND Case_Type__c!=\'Multi-party IP Case\' and (Days_After_Created_Date__c= 30 or '+
                         +'Days_After_Created_Date__c=60 or Days_After_Created_Date__c = 90 or Days_After_Created_Date__c=120)';
       
            BatchSendPromoEmails brd = new BatchSendPromoEmails();
            brd.query          = query;
            
            Database.executebatch(brd,1);

     }   
}